In [1]:
from scripts import mapping
import pandas as pd

In [2]:
ranges_continuous = mapping.get_ranges2()

In [ ]:
preds = pd.read_csv("notebooks/06_cb_regression/preds.csv")
preds

     SamplingOperations_code   IBD_pred  region
0         S02000010_20080811  15.062039      18
1         S02000010_20100719  15.438521      18
2         S02000010_20150811  13.819270      18
3         S02000010_20160825  15.086803      18
4         S02000010_20170703  16.036757      18
...                      ...        ...     ...
5658      S06700075_20120611  20.008280       2
5659      S06700094_20210830  18.611227       2
5660      S06700590_20210830  18.366359       2
5661      S06710014_20210823  19.538874       2
5662      S06820089_20120217  19.969627       2

[5663 rows x 3 columns]

In [ ]:
# rename the column
preds = preds.rename(columns={"IBD_pred": "JAJJA MIS PREDICCIONES LOLAZAS", "region": "UN LOLAZO DE REGIONES"})
preds

,SamplingOperations_code,JAJJA MIS PREDICCIONES LOLAZAS,UN LOLAZO DE REGIONES
0,S02000010_20080811,15.062039,18
1,S02000010_20100719,15.438521,18
2,S02000010_20150811,13.819270,18
3,S02000010_20160825,15.086803,18
4,S02000010_20170703,16.036757,18
...,...,...,...
5658,S06700075_20120611,20.008280,2
5659,S06700094_20210830,18.611227,2
5660,S06700590_20210830,18.366359,2
5661,S06710014_20210823,19.538874,2
5662,S06820089_20120217,19.969627,2

In [6]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="JAJJA MIS PREDICCIONES LOLAZAS", output_file="holanuria.csv")
send_results

Assigned groups based on HERlvl1Name.
Saved predictions to holanuria.csv

     IBD_EQR_Status
0              Good
1              Good
2          Moderate
3              Good
4              Good
...             ...
5658           High
5659           Good
5660           Good
5661           High
5662           High

[5663 rows x 1 columns]