# Random Forest Prediction USING ALL TRAINING DATA

In [1]:
# Standard libraries
import os

# Data manipulation and numerical computation
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn utilities
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

In [2]:
sns.set(style="ticks", context="notebook", palette="deep")
pd.set_option('display.max_columns', None)
palette = {'Bad':'#b2182b','Poor':'#d6604d','Moderate':'#f1a340','Good':'#5aae61','High':'#1b7837'}

In [9]:
path = "../../data/processed/"
dfs = {}

# read 03_CLEAN_COMPLETE_DF.parquet
cleandf = pd.read_parquet(os.path.join(path, "03_CLEAN_COMPLETE_DF.parquet"))
cleandf

,TotalAbundance_SamplingOperation,Achat02,Achca02,Achco02,Achde03,Achdr01,Acheu01,Achge01,Achla02,Achla04,Achli03,Achmi02,Achob01,Achpy01,Achri01,Achst03,Achsu01,Achsu03,Achth01,Ampat01,Ampin01,Ampin02,Ampov01,Amppe02,Aulam01,Calae01,Calba01,Coceu01,Cocli01,Cocpe01,Cocpl01,Crasu01,Cycat01,Cycdu01,Cycme02,Cycps01,Cymex01,Cymmi01,Cymsi01,Cymve01,Dente01,Diavu01,Dipse01,Exiva01,Fragr01,Frape01,Frave01,Fruco01,Fruvu01,Geiac01,Gombo02,Gomcu02,Gomel01,Gomex01,Gomin06,Gommi05,Gomol04,Gompa06,Gompu02,Gomte02,Gyrat01,Hipca02,Karcl01,Lutgo01,Melpu01,Melva01,Merci01,Navan05,Navat02,Navca07,Navca08,Navca11,Navco05,Navcr04,Navcr05,Navcr09,Navcr10,Navge02,Navgr01,Navla04,Navle02,Navmi09,Navmo05,Navoc01,Navpe05,Navre04,Navrh02,Navsa03,Navsi04,Navsu03,Navsu07,Navsu08,Navsu09,Navtr05,Navve03,Navvi01,Nitac04,Nitam01,Nitar01,Nitca03,Nitco07,Nitde03,Nitdi04,Nitfo01,Nitin02,Nitli03,Nitme01,Nitpa01,Nitpa02,Nitpu04,Nitre01,Nitso01,Nitso04,Nitsu01,Nitsu09,Plala02,Plaro04,Plesc01,Psebr01,Reisi01,Reiun01,Rhoab01,Selat01,Selni01,Selpu01,Selsa02,Stapi02,Steha01,Stein01,Suran01,Surbr01,Surla01,Synde01,Synul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D,Uncommon_Taxons,IBD,IBD_EQR,IBD_EQR_Status
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,NaN,88.888889,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,187.654321,NaN,2.469136,NaN,44.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,2.469136,NaN,NaN,NaN,NaN,NaN,NaN,32.098765,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.728395,NaN,NaN,283.950617,NaN,NaN,NaN,NaN,19.753086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,7.407407,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,14.814815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.283951,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Moderate,High,High,High,None,None,None,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,0.000000,9.6,0.502924,Poor
S02000008_20200708,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,12.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,10.000000,NaN,5.000000,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,NaN,NaN,NaN,NaN,7.5,137.500000,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,195.000000,10.0,NaN,432.500000,NaN,NaN,NaN,NaN,NaN,5.0,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,15.000000,12.5,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,22.500000,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,Good,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,5.000000,8.0,0.409357,Poor
S02000010_20070906,400,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,12.500000,2.5,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,2.500000,NaN,NaN,NaN,NaN,15.000000,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,7.500000,5.000000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,27.5,NaN,10.000000,10.000000,35.00000,67.500000,NaN,NaN,NaN,NaN,117.500000,NaN,NaN,52.5,5.0,NaN,NaN,NaN,NaN,2.500000,25.0,NaN,17.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,147.500000,5.000000,NaN,NaN,12.5,75.0,NaN,NaN,NaN,25.000000,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,2.500000,155.000000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,80.000000,14.3,0.777778,Moderate
S02000010_20090721,400,NaN,NaN,NaN,NaN,NaN,20.000000,2.5,15.000000,5.0,NaN,135.000000,NaN,7.500000,NaN,NaN,2.500000,NaN,NaN,5.0,NaN,NaN,NaN,47.500000,22.5,NaN,7.500000,72.500000,NaN,32.500000,NaN,NaN,NaN,2.5,10.0,27.5,NaN,NaN,NaN,15.0,NaN,15.0,NaN,2.500000,NaN,NaN,10.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,65.0,2.5,2.5,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.500000,NaN,NaN,22.5,2.5,NaN,NaN,NaN,NaN,12.500000,NaN,NaN,7.500000,NaN,2.5,NaN,NaN,5.000000,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.500000,2.500000,NaN,NaN,NaN,NaN,32.5,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,7.5,NaN,2.500000,10.000000,NaN,32.500000,NaN,22.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,55.000000,15.0,0.818713,Good
S02000010_20110723,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.075377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.562814,NaN,5.025126,120.603015,NaN,NaN,5.025126,17.587940,NaN,NaN,7.537688,NaN,NaN,NaN,NaN,NaN,NaN,35.175879,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,22.613065,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,17.58794,2.512563,NaN,NaN,NaN,NaN,50.251256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,10.050251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.663317,10.050251,2.512563,5.025126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.703518,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Good,55.276382,16.0,0.877193,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.132420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,363.013699,NaN,NaN,11.415525,95.890411,NaN,4.566210,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.981735,NaN,66.210046,NaN,NaN,189.497717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.415525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,NaN,82.191781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,89.041096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.963470,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,Good,Good,Good,Good,Good,Good,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,2.283105,NaN,NaN,None
S06940940_20230623,408,NaN,NaN,NaN,NaN,NaN,4.901961,NaN,NaN,NaN,NaN,375.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.803922,NaN,22.058824,NaN,NaN,NaN,58.823529,NaN,4.901961,14.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.764706,17.156863,NaN,115.196078,2.450980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.019608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.313725,NaN,NaN,34.313725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.156863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,19.607843,NaN,NaN,None
S06960950_20160629,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.281796,NaN,812.967581,NaN,NaN,12.468828,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.443890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,High,High,High,High,Good,Good,Good,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,24.937656,NaN,NaN,None
S06960950_20180719,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.076923,NaN,598.557692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.807692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.480769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.615385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,33.653846,NaN,NaN,None
S06970900_20150601,432,6.944444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.611111,NaN,706.018519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.092593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.407407,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.777778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,NaN,894594.0,6580272.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,309.0,M,High,High,High,Good,Good,Good,High,High,Good,High,High,High,Moderate,None,None,Bad,Bad,Good,Moderate,Good,Moderate,None,None,Good,None,None,0.000000,NaN,NaN,None

In [ ]:
# lets drop the rows that have NaN in IBD
TRAIN = cleandf[cleandf['IBD'].notna()]
y = TRAIN['IBD']
X = TRAIN.drop(columns=['IBD','IBD_EQR','IBD_EQR_Status'])

In [ ]:
X

,TotalAbundance_SamplingOperation,Achat02,Achca02,Achco02,Achde03,Achdr01,Acheu01,Achge01,Achla02,Achla04,Achli03,Achmi02,Achob01,Achpy01,Achri01,Achst03,Achsu01,Achsu03,Achth01,Ampat01,Ampin01,Ampin02,Ampov01,Amppe02,Aulam01,Calae01,Calba01,Coceu01,Cocli01,Cocpe01,Cocpl01,Crasu01,Cycat01,Cycdu01,Cycme02,Cycps01,Cymex01,Cymmi01,Cymsi01,Cymve01,Dente01,Diavu01,Dipse01,Exiva01,Fragr01,Frape01,Frave01,Fruco01,Fruvu01,Geiac01,Gombo02,Gomcu02,Gomel01,Gomex01,Gomin06,Gommi05,Gomol04,Gompa06,Gompu02,Gomte02,Gyrat01,Hipca02,Karcl01,Lutgo01,Melpu01,Melva01,Merci01,Navan05,Navat02,Navca07,Navca08,Navca11,Navco05,Navcr04,Navcr05,Navcr09,Navcr10,Navge02,Navgr01,Navla04,Navle02,Navmi09,Navmo05,Navoc01,Navpe05,Navre04,Navrh02,Navsa03,Navsi04,Navsu03,Navsu07,Navsu08,Navsu09,Navtr05,Navve03,Navvi01,Nitac04,Nitam01,Nitar01,Nitca03,Nitco07,Nitde03,Nitdi04,Nitfo01,Nitin02,Nitli03,Nitme01,Nitpa01,Nitpa02,Nitpu04,Nitre01,Nitso01,Nitso04,Nitsu01,Nitsu09,Plala02,Plaro04,Plesc01,Psebr01,Reisi01,Reiun01,Rhoab01,Selat01,Selni01,Selpu01,Selsa02,Stapi02,Steha01,Stein01,Suran01,Surbr01,Surla01,Synde01,Synul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D,Uncommon_Taxons
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,NaN,88.888889,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,187.654321,NaN,2.469136,NaN,44.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,2.469136,NaN,NaN,NaN,NaN,NaN,NaN,32.098765,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.728395,NaN,NaN,283.950617,NaN,NaN,NaN,NaN,19.753086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,7.407407,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,14.814815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.283951,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Moderate,High,High,High,None,None,None,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,0.000000
S02000008_20200708,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,12.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,10.000000,NaN,5.00000,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,NaN,NaN,NaN,NaN,7.5,137.500000,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,195.000000,10.000000,NaN,432.500000,NaN,NaN,NaN,NaN,NaN,5.0,12.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,15.000000,12.5,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,22.500000,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,Good,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,5.000000
S02000010_20070906,400,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,12.500000,2.5,2.50000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,2.500000,NaN,NaN,NaN,NaN,15.000000,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,7.500000,5.000000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,27.500000,NaN,10.000000,10.000000,35.00000,67.500000,NaN,NaN,NaN,NaN,117.500000,NaN,NaN,52.50000,5.0,NaN,NaN,NaN,NaN,2.500000,25.000000,NaN,17.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,147.500000,5.000000,NaN,NaN,12.5,75.000000,NaN,NaN,NaN,25.000000,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,NaN,2.5,155.000000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,80.000000
S02000010_20090721,400,NaN,NaN,NaN,NaN,NaN,20.0,2.5,15.000000,5.0,NaN,135.000000,NaN,7.500000,NaN,NaN,2.5,NaN,NaN,5.0,NaN,NaN,NaN,47.500000,22.5,NaN,7.500000,72.500000,NaN,32.50000,NaN,NaN,NaN,2.5,10.000000,27.5,NaN,NaN,NaN,15.00000,NaN,15.0,NaN,2.500000,NaN,NaN,10.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,NaN,NaN,NaN,7.5,NaN,NaN,NaN,NaN,65.0,2.500000,2.5,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.500000,NaN,NaN,22.50000,2.5,NaN,NaN,NaN,NaN,12.500000,NaN,NaN,7.500000,NaN,2.5,NaN,NaN,5.000000,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.500000,2.500000,NaN,NaN,NaN,NaN,32.5,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,7.5,NaN,2.500000,10.000000,NaN,32.500000,NaN,22.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,55.000000
S02000010_20110723,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.075377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.562814,NaN,5.025126,120.603015,NaN,NaN,5.025126,17.587940,NaN,NaN,7.537688,NaN,NaN,NaN,NaN,NaN,NaN,35.175879,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,22.613065,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,17.58794,2.512563,NaN,NaN,NaN,NaN,50.251256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,10.050251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.663317,10.050251,2.512563,5.025126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.703518,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Good,55.276382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06999141_20160928,403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.146402,NaN,12.406948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.248139,NaN,7.444169,NaN,307.692308,NaN,2.48139,116.625310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.739454,NaN,NaN,NaN,NaN,NaN,4.962779,NaN,NaN,2.481390,9.925558,NaN,NaN,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.406948,7.444169,2.481390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,57.071960,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.627792,939726.0,6583451.0,Rhône-Méditerranée,01,5,JURA-PREALPES DU NORD,76,457.0,TP,Good,Good,Good,Good,Good,Moderate,High,High,High,High,High,High,None,None,None,Bad,Bad,High,High,High,Good,Good,Good,None,None,None,7.444169
S06999179_20230628,409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.904645,437.652812,NaN,251.833741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.114914,NaN,7.334963,NaN,4.889976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.889976,9.779951,22.00489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.009780,NaN,9.779951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.449878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.889976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.889976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.334963,935630.0,6584385.0,Rhône-Méditerranée,01,5,JURA-PREALPES DU NORD,76,540.0,TP,High,High,High,Good,Good,Good,High,High,High,Good,Good,High,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,73.349633
S06999180_20160928,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.633663,NaN,309.405941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.306931,NaN,7.425743,NaN,12.376238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.950495,NaN,4.950495,9.90099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.475248,NaN,NaN,NaN,NaN,NaN,NaN,24.752475,NaN,NaN,NaN,4.950495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.475248,NaN,NaN,2.475248,NaN,NaN,NaN,NaN,44.554455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.475248,NaN,NaN,NaN,NaN,7.425743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.900990,269.801980,NaN,NaN,2.475248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.950495,NaN,2.475248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.475248,NaN,NaN,NaN,NaN,91.584158,934863.0,6578148.0,Rhône-Méditerranée,01,5,JURA-PREALPES DU NORD,76,453.0,TP,High,High,High,Good,Good,Moderate,High,High,High,High,High,High,None,None,None,Bad,Bad,High,High,High,Good,Good,Good,None,None,None,12.376238
S06999189_20160928,403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.478908,NaN,27.295285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.406948,NaN,635.235732,NaN,NaN,NaN,22.332506,NaN,2.48139,4.962779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.481390,NaN,NaN,NaN,NaN,NaN,NaN,12.406948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.146402,NaN,NaN,2.48139,NaN,NaN,2.481390,NaN,NaN,NaN,9.925558,NaN,NaN,NaN,NaN,2.481390,12.406948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.590571,17.369727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.444169,2.481390,NaN,NaN,12.406948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.258065,939337.0,6583035.0,Rhône-Méditerranée,01,5,JURA-PREALPES DU NORD,76,460.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,High,High,High,High,High,High,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,4.962779
S06999189_20220920,406,4.926108,NaN,NaN,4.926108,NaN,NaN,NaN,NaN,NaN,NaN,160.098522,NaN,46.798030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,219.211823,NaN,9.852217,NaN,19.704433,NaN,NaN,4.926108,NaN,NaN,NaN,2.463054,NaN,NaN,7.389163,NaN,NaN,NaN,NaN,9.852217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.167488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.724138,NaN,NaN,NaN,NaN,NaN,2.463054,NaN,NaN,19.704433,24.630542,NaN,NaN,NaN,NaN,2.463054,NaN,NaN,NaN,2.463054,NaN,NaN,NaN,NaN,NaN,4.926108,7.389163,118.226601,2.463054,NaN,NaN,NaN,22.167488,NaN,NaN,9.852217,9.852217,4.926108,NaN,NaN,2.463054,NaN,2.463054,NaN,17.241379,NaN,19.704433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.926108,NaN,NaN,NaN,133.004926,939337.0,6583035.0,Rhône-Méditerranée,01,5,JURA-PREALPES DU NORD,76,460.0,TP,High,High,High,Moderate,Moderate,Moderate,High,High,High,High,High,High,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,24.630542

In [12]:
y

SamplingOperations_code
S02000008_20170703     9.6
S02000008_20200708     8.0
S02000010_20070906    14.3
S02000010_20090721    15.0
S02000010_20110723    16.0
                      ...
S06999141_20160928    15.6
S06999179_20230628    20.0
S06999180_20160928    19.5
S06999189_20160928    16.1
S06999189_20220920    16.6
Name: IBD, Length: 44205, dtype: float64

In [14]:
TEST = cleandf[cleandf['IBD'].isna()]
TEST = TEST.drop(columns=['IBD','IBD_EQR','IBD_EQR_Status'])
TEST

,TotalAbundance_SamplingOperation,Achat02,Achca02,Achco02,Achde03,Achdr01,Acheu01,Achge01,Achla02,Achla04,Achli03,Achmi02,Achob01,Achpy01,Achri01,Achst03,Achsu01,Achsu03,Achth01,Ampat01,Ampin01,Ampin02,Ampov01,Amppe02,Aulam01,Calae01,Calba01,Coceu01,Cocli01,Cocpe01,Cocpl01,Crasu01,Cycat01,Cycdu01,Cycme02,Cycps01,Cymex01,Cymmi01,Cymsi01,Cymve01,Dente01,Diavu01,Dipse01,Exiva01,Fragr01,Frape01,Frave01,Fruco01,Fruvu01,Geiac01,Gombo02,Gomcu02,Gomel01,Gomex01,Gomin06,Gommi05,Gomol04,Gompa06,Gompu02,Gomte02,Gyrat01,Hipca02,Karcl01,Lutgo01,Melpu01,Melva01,Merci01,Navan05,Navat02,Navca07,Navca08,Navca11,Navco05,Navcr04,Navcr05,Navcr09,Navcr10,Navge02,Navgr01,Navla04,Navle02,Navmi09,Navmo05,Navoc01,Navpe05,Navre04,Navrh02,Navsa03,Navsi04,Navsu03,Navsu07,Navsu08,Navsu09,Navtr05,Navve03,Navvi01,Nitac04,Nitam01,Nitar01,Nitca03,Nitco07,Nitde03,Nitdi04,Nitfo01,Nitin02,Nitli03,Nitme01,Nitpa01,Nitpa02,Nitpu04,Nitre01,Nitso01,Nitso04,Nitsu01,Nitsu09,Plala02,Plaro04,Plesc01,Psebr01,Reisi01,Reiun01,Rhoab01,Selat01,Selni01,Selpu01,Selsa02,Stapi02,Steha01,Stein01,Suran01,Surbr01,Surla01,Synde01,Synul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D,Uncommon_Taxons
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000010_20080811,400,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.500000,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.500000,NaN,NaN,NaN,35.000000,NaN,2.500000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,32.500000,NaN,17.500000,NaN,NaN,NaN,82.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,15.000000,NaN,80.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,232.500000,95.000000,NaN,NaN,NaN,37.500000,72.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,5.000000,10.000000,NaN,5.000000,NaN,NaN,NaN,2.5,NaN,NaN,NaN,7.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,Good,High,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,150.000000
S02000010_20100719,404,9.900990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.108911,NaN,4.950495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.306931,NaN,NaN,2.475248,32.178218,2.475248,12.376238,27.227723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.376238,4.950495,NaN,24.752475,NaN,NaN,7.425743,NaN,NaN,7.425743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.851485,17.326733,NaN,12.376238,4.950495,NaN,NaN,NaN,NaN,NaN,7.425743,NaN,32.178218,NaN,14.851485,NaN,NaN,4.950495,NaN,NaN,64.356436,NaN,NaN,2.475248,NaN,NaN,NaN,NaN,NaN,4.950495,NaN,NaN,4.950495,NaN,NaN,2.475248,NaN,2.475248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.554455,44.554455,NaN,NaN,NaN,7.425743,27.227723,NaN,NaN,2.475248,NaN,NaN,2.475248,NaN,7.425743,NaN,NaN,4.950495,2.475248,2.475248,NaN,9.900990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.475248,NaN,12.376238,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,Good,High,High,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,141.089109
S02000010_20150811,400,NaN,NaN,NaN,62.500000,NaN,NaN,NaN,5.0,NaN,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,17.500000,NaN,NaN,NaN,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,275.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,5.000000,7.500000,NaN,120.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.000000,120.000000,NaN,NaN,NaN,67.500000,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,High,High,Moderate,Moderate,Moderate,Bad,Bad,Good,High,High,Moderate,Moderate,Moderate,Good,Good,Good,45.000000
S02000010_20160825,397,NaN,NaN,2.518892,269.521411,NaN,2.518892,NaN,NaN,NaN,NaN,68.010076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.113350,NaN,17.632242,NaN,7.556675,NaN,32.745592,NaN,10.075567,7.556675,NaN,NaN,NaN,NaN,5.037783,5.037783,5.037783,NaN,12.594458,NaN,5.037783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.075567,5.037783,NaN,12.594458,2.518892,NaN,NaN,NaN,NaN,NaN,2.518892,NaN,12.594458,NaN,22.670025,2.518892,7.556675,NaN,NaN,NaN,62.972292,7.556675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.037783,2.518892,NaN,25.188917,NaN,NaN,NaN,NaN,2.518892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.340050,60.453401,7.556675,NaN,NaN,10.075567,20.151134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.037783,2.518892,NaN,12.594458,2.518892,NaN,2.518892,NaN,NaN,2.518892,NaN,NaN,5.037783,2.518892,10.075567,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,High,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Moderate,118.387909
S02000010_20170703,410,NaN,NaN,NaN,290.243902,NaN,NaN,NaN,NaN,NaN,NaN,109.756098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.195122,NaN,29.268293,NaN,4.878049,NaN,19.512195,NaN,4.878049,4.878049,NaN,NaN,NaN,7.317073,4.878049,4.878049,NaN,19.512195,21.951220,NaN,7.317073,NaN,NaN,NaN,NaN,2.439024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.756098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.439024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190.243902,17.073171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.878049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.073171,65.853659,NaN,NaN,4.878049,9.756098,17.073171,NaN,NaN,2.439024,NaN,NaN,4.878049,NaN,NaN,NaN,NaN,NaN,NaN,4.878049,NaN,NaN,4.878049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.585366,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Good,Good,Good,Good,Good,51.219512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.132420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.56621,NaN,NaN,363.013699,NaN,NaN,11.415525,95.890411,NaN,4.566210,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.981735,NaN,66.210046,NaN,NaN,189.497717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.415525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,NaN,82.191781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,89.041096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.963470,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,Good,Good,Good,Good,Good,Good,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,2.283105
S06940940_20230623,408,NaN,NaN,NaN,NaN,NaN,4.901961,NaN,NaN,NaN,NaN,375.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.803922,NaN,22.058824,NaN,NaN,NaN,58.823529,NaN,4.901961,14.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.764706,17.156863,NaN,115.196078,2.450980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.019608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.313725,NaN,NaN,34.313725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.156863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,19.607843
S06960950_20160629,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.281796,NaN,812.967581,NaN,NaN,12.468828,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.443890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,High,High,High,High,Good,Good,Good,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,24.937656
S06960950_20180719,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.076923,NaN,598.557692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.807692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.480769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.615385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,None,None,None,Bad,Bad,High,High,High,None,None,None,None,None,None,33.653846
S06970900_20150601,432,6.944444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.611111,NaN,706.018519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.092593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.407407,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.777778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,NaN,894594.0,6580272.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,309.0,M,High,High,High,Good,Good,Good,High,High,Good,High,High,High,Moderate,None,None,Bad,Bad,Good,Moderate,Good,Moderate,None,None,Good,None,None,0.000000

# Random Forest Classifier for IBD (se supone que cargamos un modelo ya entrenado, pero equis)

In [15]:
# 2) Identify column types
num_cols = X.select_dtypes(include=['number']).columns
cat_cols = X.columns.difference(num_cols)

# 3) Preprocess
# this preprocessor can handle missing values   
pre = ColumnTransformer([
    # numerical features
    ('num', Pipeline([
        # imputation and scaling
        ('imp', SimpleImputer(strategy='median')),
        # scaling (RF doesn't need it, but other models might)
        # ('scaler', StandardScaler(with_mean=False))  # stays sparse with OHE
    ]), num_cols),
    # categorical features
    ('cat', Pipeline([
        # imputation as None being another category
        ('imp', SimpleImputer(strategy='constant', fill_value='None')),
        # one-hot encoding, ignoring unknown categories during inference
        ('ohe', OneHotEncoder(handle_unknown='ignore'))
    ]), cat_cols)

])

# 4) Model
clf = Pipeline([
    ('pre', pre),
    ('model', RandomForestRegressor(n_estimators=100, random_state=42))  # for regression
])

In [16]:
clf.fit(X, y)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['TotalAbundance_SamplingOperation', 'Achat02', 'Achca02', 'Achco02',
       'Achde03', 'Achdr01', 'Acheu01', 'Achge01', 'Achla02', 'Achla04',
       ...
       'Surla01', 'Synde01', 'Synul01', 'Vibtr01', 'Longitude_Lambert93',
       'Latitude_Lambert93', 'HERlvl1Cod...
       'OrganicMicropollutants_Status1Y', 'OrganicMicropollutants_Status90D',
       'PAH_Status180D', 'PAH_Status1Y', 'PAH_Status90D',
       'Phosphorouscompounds_Status180D', 'Phosphorouscompounds_Status1Y',
       'Phosphorouscompounds_Status90D', 'Streamsize',
       'SuspendedMatter_Status180D', 'SuspendedMatter_Status1Y',
       'SuspendedMatter_Status90D', 'Watershed'],
      dtype='object'))])),
                ('model', RandomForestRegressor(random_state=42))])

# get ibd

In [19]:
yhat = clf.predict(TEST)
yhat = pd.Series(yhat, index=TEST.index, name='IBD_Predicted')
yhat

SamplingOperations_code
S02000010_20080811    13.644
S02000010_20100719    15.866
S02000010_20150811    11.814
S02000010_20160825    15.186
S02000010_20170703    16.003
                       ...
S06940940_20100708    14.501
S06940940_20230623    16.304
S06960950_20160629    20.000
S06960950_20180719    20.000
S06970900_20150601    20.000
Name: IBD_Predicted, Length: 5658, dtype: float64

In [20]:
# can i know if S04207000_20130812 is in the training set?
code = "S04207000_20130812"
code in yhat.index

True

# get status

In [29]:
# load ranges
    # save to csv
ranges = pd.read_csv("../../data/processed/ibd_eqr_ranges_by_herlvl1_continuous_midpoint.csv")
ranges.head(20)

       HERlvl1Name IBD_EQR_Status  IBD_min  IBD_max  IBD_mid
0   ALPES INTERNES            Bad    0.000    9.800     9.30
1   ALPES INTERNES           Poor    9.800   13.225    10.30
2   ALPES INTERNES       Moderate   13.225   17.025    16.15
3   ALPES INTERNES           Good   17.025   18.725    17.90
4   ALPES INTERNES           High   18.725   20.000    19.55
5           ALSACE            Bad    0.000    6.925     5.40
6           ALSACE           Poor    6.925   10.425     8.45
7           ALSACE       Moderate   10.425   14.050    12.40
8           ALSACE           Good   14.050   17.125    15.70
9           ALSACE           High   17.125   20.000    18.55
10        ARDENNES            Bad    0.000    6.700     4.25
11        ARDENNES           Poor    6.700   10.775     9.15
12        ARDENNES       Moderate   10.775   13.750    12.40
13        ARDENNES           Good   13.750   16.725    15.10
14        ARDENNES           High   16.725   20.000    18.35
15      ARMORICAIN            Bad    0.000    6.650     5.15
16      ARMORICAIN           Poor    6.650   10.025     8.15
17      ARMORICAIN       Moderate   10.025   13.500    11.90
18      ARMORICAIN           Good   13.500   16.675    15.10
19      ARMORICAIN           High   16.675   20.000    18.25

In [23]:
# complete df
COMPLETE_TRAIN = pd.read_parquet(os.path.join(path, "03_COMPLETE_TRAIN.parquet"))
COMPLETE_TRAIN

                        CodeSite_SamplingOperations Date_SamplingOperation  \
SamplingOperations_code
S02000008_20170703                        S02000008             2017-07-03
S02000008_20200708                        S02000008             2020-07-08
S02000010_20070906                        S02000010             2007-09-06
S02000010_20090721                        S02000010             2009-07-21
S02000010_20110723                        S02000010             2011-07-23
...                                             ...                    ...
S06940940_20100708                        S06940940             2010-07-08
S06940940_20230623                        S06940940             2023-06-23
S06960950_20160629                        S06960950             2016-06-29
S06960950_20180719                        S06960950             2018-07-19
S06970900_20150601                        S06970900             2015-06-01

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06940940_20100708                                    438      NaN      NaN
S06940940_20230623                                    408      NaN      NaN
S06960950_20160629                                    401      NaN      NaN
S06960950_20180719                                    416      NaN      NaN
S06970900_20150601                                    432      NaN      NaN

                         Achaf01    Achaf02  Achal01  Acham01  Achan01  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN      NaN      NaN
S02000008_20200708           NaN        NaN      NaN      NaN      NaN
S02000010_20070906           NaN        NaN      NaN      NaN      NaN
S02000010_20090721           NaN        NaN      NaN      NaN      NaN
S02000010_20110723           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN        NaN      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN  19.230769      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achat01   Achat02  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN       NaN      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN  6.944444      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca02  Achca03  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achde02  Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achen01    Acheu01  Achex01   Achex02  Achex03  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN       NaN      NaN
S02000008_20200708           NaN        NaN      NaN       NaN      NaN
S02000010_20070906           NaN   2.500000      NaN       NaN      NaN
S02000010_20090721           NaN  20.000000      5.0       NaN      NaN
S02000010_20110723           NaN        NaN      NaN       NaN      NaN
...                          ...        ...      ...       ...      ...
S06940940_20100708           NaN        NaN      NaN       NaN      NaN
S06940940_20230623           NaN   4.901961      NaN       NaN      NaN
S06960950_20160629           NaN        NaN      NaN  2.493766      NaN
S06960950_20180719           NaN        NaN      NaN       NaN      NaN
S06970900_20150601           NaN        NaN      NaN       NaN      NaN

                         Achfl01  Achfr01  Achfu01  Achge01  Achgr01  Achgr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      2.5      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achho03  Achhu01  Achim01  Achim02  Achim03  Achin01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achin02  Achja01  Achja02  Achjo01  Achko01  Achkr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                          Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708       5.000000      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623       4.901961      NaN      NaN      NaN      NaN
S06960950_20160629            NaN      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                           Achla02  Achla03  Achla04  Achla05  Achla06  \
SamplingOperations_code
S02000008_20170703        7.407407      NaN      NaN      NaN      NaN
S02000008_20200708        7.500000      NaN      NaN      NaN      NaN
S02000010_20070906             NaN      NaN      NaN      NaN      NaN
S02000010_20090721       15.000000      NaN      5.0      NaN      NaN
S02000010_20110723             NaN      NaN      NaN      NaN      NaN
...                            ...      ...      ...      ...      ...
S06940940_20100708             NaN      NaN      NaN      NaN      NaN
S06940940_20230623             NaN      NaN      NaN      NaN      NaN
S06960950_20160629             NaN      NaN      NaN      NaN      NaN
S06960950_20180719             NaN      NaN      NaN      NaN      NaN
S06970900_20150601             NaN      NaN      NaN      NaN      NaN

                         Achle01  Achle02  Achli01  Achli02  Achli03  Achli04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achlo01  Achlu01  Achlu02  Achma01  Achmi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN

                            Achmi02    Achmi03  Achmo01  Achmo02  Achna01  \
SamplingOperations_code
S02000008_20170703        88.888889        NaN      NaN      NaN      NaN
S02000008_20200708        12.500000        NaN      NaN      NaN      NaN
S02000010_20070906              NaN        NaN      NaN      NaN      NaN
S02000010_20090721       135.000000        NaN      NaN      NaN      NaN
S02000010_20110723        15.075377        NaN      NaN      NaN      NaN
...                             ...        ...      ...      ...      ...
S06940940_20100708         9.132420        NaN      NaN      NaN      NaN
S06940940_20230623       375.000000  14.705882      NaN      NaN      NaN
S06960950_20160629        87.281796        NaN      NaN      NaN      NaN
S06960950_20180719       298.076923        NaN      NaN      NaN      NaN
S06970900_20150601       173.611111        NaN      NaN      NaN      NaN

                         Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpe01  Achpe02  Achpf01  Achpl01  Achpo01  Achpr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpr02  Achps01  Achps02  Achps03  Achps04  Achpu01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                            Achpy01  Achre01  Achri01  Achro01  Achro02  \
SamplingOperations_code
S02000008_20170703              NaN      NaN      NaN      NaN      NaN
S02000008_20200708              NaN      NaN      NaN      NaN      NaN
S02000010_20070906              NaN      NaN      NaN      NaN      NaN
S02000010_20090721         7.500000      NaN      NaN      NaN      NaN
S02000010_20110723              NaN      NaN      NaN      NaN      NaN

In [25]:
# COMPLETE_TRAIN["HERlvl1Name"]
# CodeSite_SamplingOperations

names = COMPLETE_TRAIN.loc[yhat.index, ['HERlvl1Name']]
names

                                   HERlvl1Name
SamplingOperations_code
S02000010_20080811                      ALSACE
S02000010_20100719                      ALSACE
S02000010_20150811                      ALSACE
S02000010_20160825                      ALSACE
S02000010_20170703                      ALSACE
...                                        ...
S06940940_20100708       JURA-PREALPES DU NORD
S06940940_20230623       JURA-PREALPES DU NORD
S06960950_20160629       JURA-PREALPES DU NORD
S06960950_20180719       JURA-PREALPES DU NORD
S06970900_20150601       JURA-PREALPES DU NORD

[5658 rows x 1 columns]

In [26]:
# add names to yhat
yhat = pd.concat([yhat, names], axis=1)
yhat

                         IBD_Predicted            HERlvl1Name
SamplingOperations_code
S02000010_20080811              13.644                 ALSACE
S02000010_20100719              15.866                 ALSACE
S02000010_20150811              11.814                 ALSACE
S02000010_20160825              15.186                 ALSACE
S02000010_20170703              16.003                 ALSACE
...                                ...                    ...
S06940940_20100708              14.501  JURA-PREALPES DU NORD
S06940940_20230623              16.304  JURA-PREALPES DU NORD
S06960950_20160629              20.000  JURA-PREALPES DU NORD
S06960950_20180719              20.000  JURA-PREALPES DU NORD
S06970900_20150601              20.000  JURA-PREALPES DU NORD

[5658 rows x 2 columns]

In [ ]:
def add_eqr_status(yhat: pd.DataFrame, ranges: pd.DataFrame) -> pd.DataFrame:
    """
    Adds the column 'IBD_EQR_Status_Predicted' to the `yhat` DataFrame by mapping the predicted IBD values 
    ('IBD_Predicted') into the appropriate bin defined by the [IBD_min, IBD_max) intervals in the `ranges` DataFrame 
    for the corresponding 'HERlvl1Name'. The topmost bin per region also includes its right endpoint.

    Parameters:
    ----------
    yhat : pd.DataFrame
        A DataFrame containing the predicted IBD values ('IBD_Predicted') and the corresponding 'HERlvl1Name'.
    ranges : pd.DataFrame
        A DataFrame containing the bin definitions for each 'HERlvl1Name', including columns:
        - 'HERlvl1Name': The region name.
        - 'IBD_EQR_Status': The status corresponding to the bin.
        - 'IBD_min': The lower bound of the bin (inclusive).
        - 'IBD_max': The upper bound of the bin (exclusive, except for the topmost bin).

    Returns:
    -------
    pd.DataFrame
        A copy of the `yhat` DataFrame with an additional column 'IBD_EQR_Status_Predicted', which contains the 
        mapped status for each prediction.

    Notes:
    -----
    - The function performs a cartesian merge between `yhat` and `ranges` based on 'HERlvl1Name'.
    - Each predicted value is matched to the bin where it falls within the [IBD_min, IBD_max) interval.
    - For the topmost bin in each region, the right endpoint (IBD_max) is included.
    - In case of ties (multiple bins matching a prediction), the first match is kept.
    """
    out = yhat.copy()
    out['__ix__'] = np.arange(len(out))

    # Copy ranges and calculate the maximum right endpoint for each region
    r = ranges[['HERlvl1Name', 'IBD_EQR_Status', 'IBD_min', 'IBD_max']].copy()
    r['__max_right__'] = r.groupby('HERlvl1Name')['IBD_max'].transform('max')

    # Cartesian merge by region, then keep the single interval that matches each prediction
    m = out.merge(r, on='HERlvl1Name', how='left')

    # Check if predictions fall within the bin intervals
    pred = m['IBD_Predicted'].astype(float)
    left_ok  = pred >= m['IBD_min']
    right_ok = (pred <  m['IBD_max']) | ((pred == m['IBD_max']) & (m['IBD_max'].eq(m['__max_right__'])))
    m = m[left_ok & right_ok]

    # In case of any ties, keep the first match; then map back to original rows
    m = m.sort_values(['__ix__', 'IBD_min', 'IBD_max']).drop_duplicates('__ix__', keep='first')
    status = m.set_index('__ix__')['IBD_EQR_Status']

    # Map the status back to the original DataFrame
    out['IBD_EQR_Status_Predicted'] = out['__ix__'].map(status)
    out = out.drop(columns='__ix__')
    return out

In [32]:
yhat2 = add_eqr_status(yhat, ranges)
yhat2

,IBD_Predicted,HERlvl1Name,IBD_EQR_Status_Predicted
SamplingOperations_code,,,
S02000010_20080811,13.644,ALSACE,Moderate
S02000010_20100719,15.866,ALSACE,Good
S02000010_20150811,11.814,ALSACE,Moderate
S02000010_20160825,15.186,ALSACE,Good
S02000010_20170703,16.003,ALSACE,Good
...,...,...,...
S06940940_20100708,14.501,JURA-PREALPES DU NORD,Moderate
S06940940_20230623,16.304,JURA-PREALPES DU NORD,Moderate
S06960950_20160629,20.000,JURA-PREALPES DU NORD,High
S06960950_20180719,20.000,JURA-PREALPES DU NORD,High
S06970900_20150601,20.000,JURA-PREALPES DU NORD,High

In [ ]:
send_predictions = yhat2['IBD_EQR_Status_Predicted']

In [1]:
import pandas as pd
read_example = pd.read_csv("..\\..\\results\\000 example\\random_predictions.csv")

In [40]:
# sort by SamplingOperations_code
read_example = read_example.set_index('SamplingOperations_code')
read_example = read_example.sort_index()
read_example

                        IBD_EQR_Status
SamplingOperations_code
S02000010_20080811                High
S02000010_20100719                High
S02000010_20150811                Good
S02000010_20170703                Good
S02000011_20100719                Good
...                                ...
S06940940_20100708                Good
S06940940_20230623                High
S06960950_20160629            Moderate
S06960950_20180719                Good
S06970900_20150601            Moderate

[5063 rows x 1 columns]

In [37]:
send_predictions

SamplingOperations_code
S02000010_20080811    Moderate
S02000010_20100719        Good
S02000010_20150811    Moderate
S02000010_20160825        Good
S02000010_20170703        Good
                        ...
S06940940_20100708    Moderate
S06940940_20230623    Moderate
S06960950_20160629        High
S06960950_20180719        High
S06970900_20150601        High
Name: IBD_EQR_Status_Predicted, Length: 5658, dtype: object

In [ ]:
# inner join to see if they are the same
innerjoin = send_predictions.to_frame().merge(read_example, left_index=True, right_index=True, how='inner', suffixes=('_predicted', '_example'))
innerjoin

                        IBD_EQR_Status_Predicted IBD_EQR_Status
SamplingOperations_code
S02000010_20080811                      Moderate           High
S02000010_20100719                          Good           High
S02000010_20150811                      Moderate           Good
S02000010_20170703                          Good           Good
S02000011_20100719                          Good           Good
...                                          ...            ...
S06940940_20100708                      Moderate           Good
S06940940_20230623                      Moderate           High
S06960950_20160629                          High       Moderate
S06960950_20180719                          High           Good
S06970900_20150601                          High       Moderate

[5063 rows x 2 columns]

In [44]:
# count how many are the same
innerjoin['same'] = innerjoin['IBD_EQR_Status_Predicted'] == innerjoin['IBD_EQR_Status']
innerjoin['same'].value_counts()

same
False    3438
True     1625
Name: count, dtype: int64

In [45]:
# proportion of same
innerjoin['same'].value_counts(normalize=True)

same
False    0.679044
True     0.320956
Name: proportion, dtype: float64

In [48]:
truesend = innerjoin["IBD_EQR_Status_Predicted"]

# change the name to "IBD_EQR_Status"
truesend = truesend.rename("IBD_EQR_Status")
truesend.to_csv("un_lolazo_submission.csv")
truesend

SamplingOperations_code
S02000010_20080811    Moderate
S02000010_20100719        Good
S02000010_20150811    Moderate
S02000010_20170703        Good
S02000011_20100719        Good
                        ...
S06940940_20100708    Moderate
S06940940_20230623    Moderate
S06960950_20160629        High
S06960950_20180719        High
S06970900_20150601        High
Name: IBD_EQR_Status, Length: 5063, dtype: object

In [ ]:
def process_predictions(yhat: pd.DataFrame, ranges: pd.DataFrame, read_example: pd.DataFrame, output_file: str) -> pd.Series:
    """
    Processes predictions by adding EQR status, comparing with an example dataset, and saving the results.

    Parameters:
    ----------
    yhat : pd.DataFrame
        DataFrame containing predicted IBD values and corresponding HERlvl1Name.
    ranges : pd.DataFrame
        DataFrame containing bin definitions for mapping IBD values to EQR status.
    read_example : pd.DataFrame
        DataFrame containing example predictions for comparison.
    output_file : str
        Path to save the processed predictions as a CSV file.

    Returns:
    -------
    pd.Series
        Processed predictions with the name 'IBD_EQR_Status'.
    """
    # Add EQR status to predictions
    yhat2 = add_eqr_status(yhat, ranges)
    send_predictions = yhat2['IBD_EQR_Status_Predicted']

    # Inner join to compare with example predictions
    innerjoin = send_predictions.to_frame().merge(
        read_example.set_index('SamplingOperations_code'),
        left_index=True,
        right_index=True,
        how='inner',
        suffixes=('_predicted', '_example')
    )

    # Extract the predicted status
    truesend = innerjoin["IBD_EQR_Status_Predicted"]

    # Rename and save to CSV
    truesend = truesend.rename("IBD_EQR_Status")
    truesend.to_csv(output_file)

    return truesend