In [100]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [101]:
sns.set(style="ticks", context="notebook", palette="deep")
pd.set_option('display.max_columns', None)
palette = {'Bad':'#b2182b','Poor':'#d6604d','Moderate':'#f1a340','Good':'#5aae61','High':'#1b7837'}

In [102]:
path = "../../data/processed/"
dfs = {}

# read all dataframes and keep them in dfs
for parquet in os.listdir(path):  # List all files in the directory
    if parquet.endswith(".parquet"):
        name = parquet.split(".parquet")[0]  # Get name without extension
        dfs[name] = pd.read_parquet(os.path.join(path, parquet))  # Use os.path.join for paths
        print(f"Loaded {name} with shape {dfs[name].shape}")

Loaded 03_COMPLETE_TEST with shape (43783, 3)
Loaded 03_COMPLETE_TRAIN with shape (49441, 2332)
Loaded clean_df with shape (44205, 174)
Loaded clean_df_train with shape (44205, 174)
Loaded taxones_pressure_predict with shape (5658, 2333)
Loaded taxones_pressure_train with shape (43783, 2336)

In [103]:
df = dfs[f"taxones_pressure_train"]
df

      SamplingOperations_code CodeSite_SamplingOperations  \
0          S02000008_20170703                   S02000008
1          S02000008_20200708                   S02000008
2          S02000010_20070906                   S02000010
3          S02000010_20090721                   S02000010
4          S02000010_20110723                   S02000010
...                       ...                         ...
43778      S06999141_20160928                   S06999141
43779      S06999179_20230628                   S06999179
43780      S06999180_20160928                   S06999180
43781      S06999189_20160928                   S06999189
43782      S06999189_20220920                   S06999189

      Date_SamplingOperation  TotalAbundance_SamplingOperation  Achaa01  \
0                 2017-07-03                               405      NaN
1                 2020-07-08                               400      NaN
2                 2007-09-06                               400      NaN
3                 2009-07-21                               400      NaN
4                 2011-07-23                               398      NaN
...                      ...                               ...      ...
43778             2016-09-28                               403      NaN
43779             2023-06-28                               409      NaN
43780             2016-09-28                               404      NaN
43781             2016-09-28                               403      NaN
43782             2022-09-20                               406      NaN

       Achac01  Achaf01  Achaf02  Achal01  Acham01  Achan01  Achat01  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN  2.48139      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN

        Achat02  Achat03  Achba01  Achbi01  Achbi02  Achbr01  Achca01  \
0           NaN      NaN      NaN      NaN      NaN      NaN      NaN
1           NaN      NaN      NaN      NaN      NaN      NaN      NaN
2           NaN      NaN      NaN      NaN      NaN      NaN      NaN
3           NaN      NaN      NaN      NaN      NaN      NaN      NaN
4           NaN      NaN      NaN      NaN      NaN      NaN      NaN
...         ...      ...      ...      ...      ...      ...      ...
43778       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782  4.926108      NaN      NaN      NaN      NaN      NaN      NaN

       Achca02  Achca03  Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  Achde02  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN

        Achde03  Achdi01  Achdi02  Achdr01  Achel01  Achen01  Acheu01  \
0           NaN      NaN      NaN      NaN      NaN      NaN      NaN
1           NaN      NaN      NaN      NaN      NaN      NaN      NaN
2           NaN      NaN      NaN      NaN      NaN      NaN      2.5
3           NaN      NaN      NaN      NaN      NaN      NaN     20.0
4           NaN      NaN      NaN      NaN      NaN      NaN      NaN
...         ...      ...      ...      ...      ...      ...      ...
43778       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781       NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782  4.926108      NaN      NaN      NaN      NaN      NaN      NaN

       Achex01  Achex02  Achex03  Achfl01  Achfr01  Achfu01  Achge01  Achgr01  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          5.0      NaN      NaN      NaN      NaN      NaN      2.5      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achgr02  Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  Achho03  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achhu01  Achim01  Achim02  Achim03  Achin01  Achin02  Achja01  Achja02  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achjo01  Achko01  Achkr01  Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      5.0      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

         Achla02  Achla03  Achla04  Achla05  Achla06  Achle01  Achle02  \
0       7.407407      NaN      NaN      NaN      NaN      NaN      NaN
1       7.500000      NaN      NaN      NaN      NaN      NaN      NaN
2            NaN      NaN      NaN      NaN      NaN      NaN      NaN
3      15.000000      NaN      5.0      NaN      NaN      NaN      NaN
4            NaN      NaN      NaN      NaN      NaN      NaN      NaN
...          ...      ...      ...      ...      ...      ...      ...
43778        NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779        NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780        NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781        NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782        NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achli01  Achli02    Achli03  Achli04  Achlo01  Achlu01  Achlu02  \
0          NaN      NaN        NaN      NaN      NaN      NaN      NaN
1          NaN      NaN        NaN      NaN      NaN      NaN      NaN
2          NaN      NaN        NaN      NaN      NaN      NaN      NaN
3          NaN      NaN        NaN      NaN      NaN      NaN      NaN
4          NaN      NaN        NaN      NaN      NaN      NaN      NaN
...        ...      ...        ...      ...      ...      ...      ...
43778      NaN      NaN        NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN  70.904645      NaN      NaN      NaN      NaN
43780      NaN      NaN        NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN        NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN        NaN      NaN      NaN      NaN      NaN

       Achma01  Achmi01     Achmi02  Achmi03  Achmo01  Achmo02  Achna01  \
0          NaN      NaN   88.888889      NaN      NaN      NaN      NaN
1          NaN      NaN   12.500000      NaN      NaN      NaN      NaN
2          NaN      NaN         NaN      NaN      NaN      NaN      NaN
3          NaN      NaN  135.000000      NaN      NaN      NaN      NaN
4          NaN      NaN   15.075377      NaN      NaN      NaN      NaN
...        ...      ...         ...      ...      ...      ...      ...
43778      NaN      NaN   47.146402      NaN      NaN      NaN      NaN
43779      NaN      NaN  437.652812      NaN      NaN      NaN      NaN
43780      NaN      NaN   86.633663      NaN      NaN      NaN      NaN
43781      NaN      NaN   69.478908      NaN      NaN      NaN      NaN
43782      NaN      NaN  160.098522      NaN      NaN      NaN      NaN

       Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  Achpe01  Achpe02  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achpf01  Achpl01  Achpo01  Achpr01  Achpr02  Achps01  Achps02  Achps03  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achps04  Achpu01     Achpy01  Achre01  Achri01  Achro01  Achro02  \
0          NaN      NaN         NaN      NaN      NaN      NaN      NaN
1          NaN      NaN         NaN      NaN      NaN      NaN      NaN
2          NaN      NaN         NaN      NaN      NaN      NaN      NaN
3          NaN      NaN    7.500000      NaN      NaN      NaN      NaN
4          NaN      NaN         NaN      NaN      NaN      NaN      NaN
...        ...      ...         ...      ...      ...      ...      ...
43778      NaN      NaN   12.406948      NaN      NaN      NaN      NaN
43779      NaN      NaN  251.833741      NaN      NaN      NaN      NaN
43780      NaN      NaN  309.405941      NaN      NaN      NaN      NaN
43781      NaN      NaN   27.295285      NaN      NaN      NaN      NaN
43782      NaN      NaN   46.798030      NaN      NaN      NaN      NaN

       Achro03  Achro04  Achru01  Achru02  Achsa01  Achsc01  Achse01  Achse02  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achsi01  Achst01  Achst02   Achst03  Achst04  Achsu01  Achsu02  \
0          NaN      NaN      NaN  2.469136      NaN      NaN      NaN
1          NaN      NaN      NaN       NaN      NaN      NaN      NaN
2          NaN      NaN      NaN       NaN      NaN      NaN      NaN
3          NaN      NaN      NaN       NaN      NaN      2.5      NaN
4          NaN      NaN      NaN       NaN      NaN      NaN      NaN
...        ...      ...      ...       ...      ...      ...      ...
43778      NaN      NaN      NaN       NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN       NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN       NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN       NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN       NaN      NaN      NaN      NaN

       Achsu03  Achsu04  Achsu05  Achsu06  Achsu07  Achte01  Achth01  Achtr01  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Achtr02  Achtr03  Achtu01  Achzh01  Achzi01  Actde01  Actno01  Actro01  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Actse01  Actsp01  Actsu01  Actvu01  Adlaq01  Adlba01  Adlbr01  Adlbr02  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
...        ...      ...      ...      ...      ...      ...      ...      ...
43778      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43779      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43780      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43781      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
43782      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Adlmi01  Adlmu01  Adlmu02  Adlpa01  Adlsu01  Afrre01  Ampae01  Ampaf01  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

In [104]:
# drop Longitude_Lambert93_x	Latitude_Lambert93_x	Watershed_x	CodeDepartement_x	HERlvl1Code_x	HERlvl1Name_x	HERlvl2Code_x	HERlvl2Name_x	Altitude_x	Streamsize_x
df = df.set_index('SamplingOperations_code')
df

                        CodeSite_SamplingOperations Date_SamplingOperation  \
SamplingOperations_code
S02000008_20170703                        S02000008             2017-07-03
S02000008_20200708                        S02000008             2020-07-08
S02000010_20070906                        S02000010             2007-09-06
S02000010_20090721                        S02000010             2009-07-21
S02000010_20110723                        S02000010             2011-07-23
...                                             ...                    ...
S06999141_20160928                        S06999141             2016-09-28
S06999179_20230628                        S06999179             2023-06-28
S06999180_20160928                        S06999180             2016-09-28
S06999189_20160928                        S06999189             2016-09-28
S06999189_20220920                        S06999189             2022-09-20

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06999141_20160928                                    403      NaN      NaN
S06999179_20230628                                    409      NaN      NaN
S06999180_20160928                                    404      NaN      NaN
S06999189_20160928                                    403      NaN      NaN
S06999189_20220920                                    406      NaN      NaN

                         Achaf01  Achaf02  Achal01  Acham01  Achan01  Achat01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN  2.48139      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                          Achat02  Achat03  Achba01  Achbi01  Achbi02  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708            NaN      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06999141_20160928            NaN      NaN      NaN      NaN      NaN
S06999179_20230628            NaN      NaN      NaN      NaN      NaN
S06999180_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20220920       4.926108      NaN      NaN      NaN      NaN

                         Achbr01  Achca01  Achca02  Achca03  Achca04  Achch01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achcl01  Achco01  Achco02  Achco03  Achco04  Achcr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achcy01  Achda01  Achda02  Achde01  Achde02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN

                          Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708            NaN      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06999141_20160928            NaN      NaN      NaN      NaN      NaN
S06999179_20230628            NaN      NaN      NaN      NaN      NaN
S06999180_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20220920       4.926108      NaN      NaN      NaN      NaN

                         Achen01  Acheu01  Achex01  Achex02  Achex03  Achfl01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      2.5      NaN      NaN      NaN      NaN
S02000010_20090721           NaN     20.0      5.0      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achfr01  Achfu01  Achge01  Achgr01  Achgr02  Achgr03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      2.5      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achha01  Achhe01  Achhi01  Achho01  Achho02  Achho03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achhu01  Achim01  Achim02  Achim03  Achin01  Achin02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achja01  Achja02  Achjo01  Achko01  Achkr01  Achkr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      5.0
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achkr03  Achkr04  Achku01  Achla01    Achla02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN   7.407407
S02000008_20200708           NaN      NaN      NaN      NaN   7.500000
S02000010_20070906           NaN      NaN      NaN      NaN        NaN
S02000010_20090721           NaN      NaN      NaN      NaN  15.000000
S02000010_20110723           NaN      NaN      NaN      NaN        NaN
...                          ...      ...      ...      ...        ...
S06999141_20160928           NaN      NaN      NaN      NaN        NaN
S06999179_20230628           NaN      NaN      NaN      NaN        NaN
S06999180_20160928           NaN      NaN      NaN      NaN        NaN
S06999189_20160928           NaN      NaN      NaN      NaN        NaN
S06999189_20220920           NaN      NaN      NaN      NaN        NaN

                         Achla03  Achla04  Achla05  Achla06  Achle01  Achle02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      5.0      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achli01  Achli02    Achli03  Achli04  Achlo01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN        NaN      NaN      NaN
S02000008_20200708           NaN      NaN        NaN      NaN      NaN
S02000010_20070906           NaN      NaN        NaN      NaN      NaN
S02000010_20090721           NaN      NaN        NaN      NaN      NaN
S02000010_20110723           NaN      NaN        NaN      NaN      NaN
...                          ...      ...        ...      ...      ...
S06999141_20160928           NaN      NaN        NaN      NaN      NaN
S06999179_20230628           NaN      NaN  70.904645      NaN      NaN
S06999180_20160928           NaN      NaN        NaN      NaN      NaN
S06999189_20160928           NaN      NaN        NaN      NaN      NaN
S06999189_20220920           NaN      NaN        NaN      NaN      NaN

                         Achlu01  Achlu02  Achma01  Achmi01     Achmi02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN   88.888889
S02000008_20200708           NaN      NaN      NaN      NaN   12.500000
S02000010_20070906           NaN      NaN      NaN      NaN         NaN
S02000010_20090721           NaN      NaN      NaN      NaN  135.000000
S02000010_20110723           NaN      NaN      NaN      NaN   15.075377
...                          ...      ...      ...      ...         ...
S06999141_20160928           NaN      NaN      NaN      NaN   47.146402
S06999179_20230628           NaN      NaN      NaN      NaN  437.652812
S06999180_20160928           NaN      NaN      NaN      NaN   86.633663
S06999189_20160928           NaN      NaN      NaN      NaN   69.478908
S06999189_20220920           NaN      NaN      NaN      NaN  160.098522

                         Achmi03  Achmo01  Achmo02  Achna01  Achna02  Achne01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achni01  Achno01  Achob01  Achpa01  Achpe01  Achpe02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpf01  Achpl01  Achpo01  Achpr01  Achpr02  Achps01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achps02  Achps03  Achps04  Achpu01     Achpy01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN         NaN
S02000008_20200708           NaN      NaN      NaN      NaN         NaN
S02000010_20070906           NaN      NaN      NaN      NaN         NaN
S02000010_20090721           NaN      NaN      NaN      NaN    7.500000
S02000010_20110723           NaN      NaN      NaN      NaN         NaN
...                          ...      ...      ...      ...         ...
S06999141_20160928           NaN      NaN      NaN      NaN   12.406948
S06999179_20230628           NaN      NaN      NaN      NaN  251.833741
S06999180_20160928           NaN      NaN      NaN      NaN  309.405941
S06999189_20160928           NaN      NaN      NaN      NaN   27.295285
S06999189_20220920           NaN      NaN      NaN      NaN   46.798030

                         Achre01  Achri01  Achro01  Achro02  Achro03  Achro04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN

In [108]:
Xtr = df.drop(columns=['IBD', 'IBD_EQR', 'IBD_EQR_Status'])
Y = df[['IBD', 'IBD_EQR', 'IBD_EQR_Status']]
y = df[['IBD']]
Xtr

                        CodeSite_SamplingOperations Date_SamplingOperation  \
SamplingOperations_code
S02000008_20170703                        S02000008             2017-07-03
S02000008_20200708                        S02000008             2020-07-08
S02000010_20070906                        S02000010             2007-09-06
S02000010_20090721                        S02000010             2009-07-21
S02000010_20110723                        S02000010             2011-07-23
...                                             ...                    ...
S06999141_20160928                        S06999141             2016-09-28
S06999179_20230628                        S06999179             2023-06-28
S06999180_20160928                        S06999180             2016-09-28
S06999189_20160928                        S06999189             2016-09-28
S06999189_20220920                        S06999189             2022-09-20

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06999141_20160928                                    403      NaN      NaN
S06999179_20230628                                    409      NaN      NaN
S06999180_20160928                                    404      NaN      NaN
S06999189_20160928                                    403      NaN      NaN
S06999189_20220920                                    406      NaN      NaN

                         Achaf01  Achaf02  Achal01  Acham01  Achan01  Achat01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN  2.48139      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                          Achat02  Achat03  Achba01  Achbi01  Achbi02  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708            NaN      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06999141_20160928            NaN      NaN      NaN      NaN      NaN
S06999179_20230628            NaN      NaN      NaN      NaN      NaN
S06999180_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20220920       4.926108      NaN      NaN      NaN      NaN

                         Achbr01  Achca01  Achca02  Achca03  Achca04  Achch01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achcl01  Achco01  Achco02  Achco03  Achco04  Achcr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achcy01  Achda01  Achda02  Achde01  Achde02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN

                          Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708            NaN      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06999141_20160928            NaN      NaN      NaN      NaN      NaN
S06999179_20230628            NaN      NaN      NaN      NaN      NaN
S06999180_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20160928            NaN      NaN      NaN      NaN      NaN
S06999189_20220920       4.926108      NaN      NaN      NaN      NaN

                         Achen01  Acheu01  Achex01  Achex02  Achex03  Achfl01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      2.5      NaN      NaN      NaN      NaN
S02000010_20090721           NaN     20.0      5.0      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achfr01  Achfu01  Achge01  Achgr01  Achgr02  Achgr03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      2.5      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achha01  Achhe01  Achhi01  Achho01  Achho02  Achho03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achhu01  Achim01  Achim02  Achim03  Achin01  Achin02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achja01  Achja02  Achjo01  Achko01  Achkr01  Achkr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      5.0
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achkr03  Achkr04  Achku01  Achla01    Achla02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN   7.407407
S02000008_20200708           NaN      NaN      NaN      NaN   7.500000
S02000010_20070906           NaN      NaN      NaN      NaN        NaN
S02000010_20090721           NaN      NaN      NaN      NaN  15.000000
S02000010_20110723           NaN      NaN      NaN      NaN        NaN
...                          ...      ...      ...      ...        ...
S06999141_20160928           NaN      NaN      NaN      NaN        NaN
S06999179_20230628           NaN      NaN      NaN      NaN        NaN
S06999180_20160928           NaN      NaN      NaN      NaN        NaN
S06999189_20160928           NaN      NaN      NaN      NaN        NaN
S06999189_20220920           NaN      NaN      NaN      NaN        NaN

                         Achla03  Achla04  Achla05  Achla06  Achle01  Achle02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      5.0      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achli01  Achli02    Achli03  Achli04  Achlo01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN        NaN      NaN      NaN
S02000008_20200708           NaN      NaN        NaN      NaN      NaN
S02000010_20070906           NaN      NaN        NaN      NaN      NaN
S02000010_20090721           NaN      NaN        NaN      NaN      NaN
S02000010_20110723           NaN      NaN        NaN      NaN      NaN
...                          ...      ...        ...      ...      ...
S06999141_20160928           NaN      NaN        NaN      NaN      NaN
S06999179_20230628           NaN      NaN  70.904645      NaN      NaN
S06999180_20160928           NaN      NaN        NaN      NaN      NaN
S06999189_20160928           NaN      NaN        NaN      NaN      NaN
S06999189_20220920           NaN      NaN        NaN      NaN      NaN

                         Achlu01  Achlu02  Achma01  Achmi01     Achmi02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN   88.888889
S02000008_20200708           NaN      NaN      NaN      NaN   12.500000
S02000010_20070906           NaN      NaN      NaN      NaN         NaN
S02000010_20090721           NaN      NaN      NaN      NaN  135.000000
S02000010_20110723           NaN      NaN      NaN      NaN   15.075377
...                          ...      ...      ...      ...         ...
S06999141_20160928           NaN      NaN      NaN      NaN   47.146402
S06999179_20230628           NaN      NaN      NaN      NaN  437.652812
S06999180_20160928           NaN      NaN      NaN      NaN   86.633663
S06999189_20160928           NaN      NaN      NaN      NaN   69.478908
S06999189_20220920           NaN      NaN      NaN      NaN  160.098522

                         Achmi03  Achmo01  Achmo02  Achna01  Achna02  Achne01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achni01  Achno01  Achob01  Achpa01  Achpe01  Achpe02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpf01  Achpl01  Achpo01  Achpr01  Achpr02  Achps01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06999141_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999179_20230628           NaN      NaN      NaN      NaN      NaN      NaN
S06999180_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20160928           NaN      NaN      NaN      NaN      NaN      NaN
S06999189_20220920           NaN      NaN      NaN      NaN      NaN      NaN

                         Achps02  Achps03  Achps04  Achpu01     Achpy01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN         NaN
S02000008_20200708           NaN      NaN      NaN      NaN         NaN
S02000010_20070906           NaN      NaN      NaN      NaN         NaN
S02000010_20090721           NaN      NaN      NaN      NaN    7.500000
S02000010_20110723           NaN      NaN      NaN      NaN         NaN
...                          ...      ...      ...      ...         ...
S06999141_20160928           NaN      NaN      NaN      NaN   12.406948
S06999179_20230628           NaN      NaN      NaN      NaN  251.833741
S06999180_20160928           NaN      NaN      NaN      NaN  309.405941
S06999189_20160928           NaN      NaN      NaN      NaN   27.295285
S06999189_20220920           NaN      NaN      NaN      NaN   46.798030

                         Achre01  Achri01  Achro01  Achro02  Achro03  Achro04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN

In [113]:
Xte = dfs[f"taxones_pressure_predict"].set_index('SamplingOperations_code')
Xte

                        CodeSite_SamplingOperations Date_SamplingOperation  \
SamplingOperations_code
S02000010_20080811                        S02000010             2008-08-11
S02000010_20100719                        S02000010             2010-07-19
S02000010_20150811                        S02000010             2015-08-11
S02000010_20160825                        S02000010             2016-08-25
S02000010_20170703                        S02000010             2017-07-03
...                                             ...                    ...
S06940940_20100708                        S06940940             2010-07-08
S06940940_20230623                        S06940940             2023-06-23
S06960950_20160629                        S06960950             2016-06-29
S06960950_20180719                        S06960950             2018-07-19
S06970900_20150601                        S06970900             2015-06-01

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000010_20080811                                    400      NaN      NaN
S02000010_20100719                                    404      NaN      NaN
S02000010_20150811                                    400      NaN      NaN
S02000010_20160825                                    397      NaN      NaN
S02000010_20170703                                    410      NaN      NaN
...                                                   ...      ...      ...
S06940940_20100708                                    438      NaN      NaN
S06940940_20230623                                    408      NaN      NaN
S06960950_20160629                                    401      NaN      NaN
S06960950_20180719                                    416      NaN      NaN
S06970900_20150601                                    432      NaN      NaN

                         Achaf01    Achaf02  Achal01  Acham01  Achan01  \
SamplingOperations_code
S02000010_20080811           NaN        NaN      NaN      NaN      NaN
S02000010_20100719           NaN        NaN      NaN      NaN      NaN
S02000010_20150811           NaN        NaN      NaN      NaN      NaN
S02000010_20160825           NaN        NaN      NaN      NaN      NaN
S02000010_20170703           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN        NaN      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN  19.230769      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achat01   Achat02  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000010_20080811           NaN  2.500000      NaN      NaN      NaN
S02000010_20100719           NaN  9.900990      NaN      NaN      NaN
S02000010_20150811           NaN       NaN      NaN      NaN      NaN
S02000010_20160825           NaN       NaN      NaN      NaN      NaN
S02000010_20170703           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN       NaN      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN  6.944444      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca02  Achca03  \
SamplingOperations_code
S02000010_20080811           NaN       NaN      NaN      NaN      NaN
S02000010_20100719           NaN       NaN      NaN      NaN      NaN
S02000010_20150811           NaN       NaN      NaN      NaN      NaN
S02000010_20160825           NaN       NaN      NaN      NaN      NaN
S02000010_20170703           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achca04  Achch01  Achcl01  Achco01   Achco02  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN       NaN
S02000010_20100719           NaN      NaN      NaN      NaN       NaN
S02000010_20150811           NaN      NaN      NaN      NaN       NaN
S02000010_20160825           NaN      NaN      NaN      NaN  2.518892
S02000010_20170703           NaN      NaN      NaN      NaN       NaN
...                          ...      ...      ...      ...       ...
S06940940_20100708           NaN      NaN      NaN      NaN       NaN
S06940940_20230623           NaN      NaN      NaN      NaN       NaN
S06960950_20160629           NaN      NaN      NaN      NaN       NaN
S06960950_20180719           NaN      NaN      NaN      NaN       NaN
S06970900_20150601           NaN      NaN      NaN      NaN       NaN

                         Achco03  Achco04  Achcr01  Achcy01  Achda01  Achda02  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achde01  Achde02     Achde03  Achdi01  Achdi02  \
SamplingOperations_code
S02000010_20080811           NaN      NaN         NaN      NaN      NaN
S02000010_20100719           NaN      NaN         NaN      NaN      NaN
S02000010_20150811           NaN      NaN   62.500000      NaN      NaN
S02000010_20160825           NaN      NaN  269.521411      NaN      NaN
S02000010_20170703           NaN      NaN  290.243902      NaN      NaN
...                          ...      ...         ...      ...      ...
S06940940_20100708           NaN      NaN         NaN      NaN      NaN
S06940940_20230623           NaN      NaN         NaN      NaN      NaN
S06960950_20160629           NaN      NaN         NaN      NaN      NaN
S06960950_20180719           NaN      NaN         NaN      NaN      NaN
S06970900_20150601           NaN      NaN         NaN      NaN      NaN

                         Achdr01  Achel01  Achen01   Acheu01  Achex01  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN       NaN      NaN
S02000010_20100719           NaN      NaN      NaN       NaN      NaN
S02000010_20150811           NaN      NaN      NaN       NaN      NaN
S02000010_20160825           NaN      NaN      NaN  2.518892      NaN
S02000010_20170703           NaN      NaN      NaN       NaN      NaN
...                          ...      ...      ...       ...      ...
S06940940_20100708           NaN      NaN      NaN       NaN      NaN
S06940940_20230623           NaN      NaN      NaN  4.901961      NaN
S06960950_20160629           NaN      NaN      NaN       NaN      NaN
S06960950_20180719           NaN      NaN      NaN       NaN      NaN
S06970900_20150601           NaN      NaN      NaN       NaN      NaN

                          Achex02  Achex03  Achfl01  Achfr01  Achfu01  \
SamplingOperations_code
S02000010_20080811            NaN      NaN      NaN      NaN      NaN
S02000010_20100719            NaN      NaN      NaN      NaN      NaN
S02000010_20150811            NaN      NaN      NaN      NaN      NaN
S02000010_20160825            NaN      NaN      NaN      NaN      NaN
S02000010_20170703            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623            NaN      NaN      NaN      NaN      NaN
S06960950_20160629       2.493766      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                         Achge01  Achgr01  Achgr02  Achgr03  Achha01  Achhe01  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achhi01  Achho01  Achho02  Achho03  Achhu01  Achim01  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achim02  Achim03  Achin01  Achin02  Achja01  Achja02  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achjo01  Achko01  Achkr01   Achkr02  Achkr03  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN       NaN      NaN
S02000010_20100719           NaN      NaN      NaN       NaN      NaN
S02000010_20150811           NaN      NaN      NaN       NaN      NaN
S02000010_20160825           NaN      NaN      NaN       NaN      NaN
S02000010_20170703           NaN      NaN      NaN       NaN      NaN
...                          ...      ...      ...       ...      ...
S06940940_20100708           NaN      NaN      NaN       NaN      NaN
S06940940_20230623           NaN      NaN      NaN  4.901961      NaN
S06960950_20160629           NaN      NaN      NaN       NaN      NaN
S06960950_20180719           NaN      NaN      NaN       NaN      NaN
S06970900_20150601           NaN      NaN      NaN       NaN      NaN

                         Achkr04  Achku01  Achla01  Achla02  Achla03  Achla04  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      5.0      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achla05  Achla06  Achle01  Achle02  Achli01  Achli02  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achli03  Achli04  Achlo01  Achlu01  Achlu02  Achma01  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achmi01     Achmi02    Achmi03  Achmo01  Achmo02  \
SamplingOperations_code
S02000010_20080811           NaN   47.500000        NaN      NaN      NaN
S02000010_20100719           NaN   89.108911        NaN      NaN      NaN
S02000010_20150811           NaN   25.000000        NaN      NaN      NaN
S02000010_20160825           NaN   68.010076        NaN      NaN      NaN
S02000010_20170703           NaN  109.756098        NaN      NaN      NaN
...                          ...         ...        ...      ...      ...
S06940940_20100708           NaN    9.132420        NaN      NaN      NaN
S06940940_20230623           NaN  375.000000  14.705882      NaN      NaN
S06960950_20160629           NaN   87.281796        NaN      NaN      NaN
S06960950_20180719           NaN  298.076923        NaN      NaN      NaN
S06970900_20150601           NaN  173.611111        NaN      NaN      NaN

                         Achna01  Achna02  Achne01  Achni01  Achno01  Achob01  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpa01  Achpe01  Achpe02  Achpf01  Achpl01  Achpo01  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpr01  Achpr02  Achps01  Achps02  Achps03  Achps04  \
SamplingOperations_code
S02000010_20080811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20100719           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20150811           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20160825           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20170703           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpu01     Achpy01  Achre01  Achri01  Achro01  \
SamplingOperations_code
S02000010_20080811           NaN         NaN      NaN      NaN      NaN
S02000010_20100719           NaN    4.950495      NaN      NaN      NaN
S02000010_20150811           NaN         NaN      NaN      NaN      NaN
S02000010_20160825           NaN         NaN      NaN      NaN      NaN
S02000010_20170703           NaN         NaN      NaN      NaN      NaN
...                          ...         ...      ...      ...      ...

In [111]:
# X is concat of Xtr and Xte, preserving the common index
X = pd.concat([Xtr, Xte], axis=0)
X.to_parquet(f"../../data/processed/03_COMPLETE_TRAIN.parquet", index=True)
COMPLETE_X = X.copy()
X

                        CodeSite_SamplingOperations Date_SamplingOperation  \
SamplingOperations_code
S02000008_20170703                        S02000008             2017-07-03
S02000008_20200708                        S02000008             2020-07-08
S02000010_20070906                        S02000010             2007-09-06
S02000010_20090721                        S02000010             2009-07-21
S02000010_20110723                        S02000010             2011-07-23
...                                             ...                    ...
S06940940_20100708                        S06940940             2010-07-08
S06940940_20230623                        S06940940             2023-06-23
S06960950_20160629                        S06960950             2016-06-29
S06960950_20180719                        S06960950             2018-07-19
S06970900_20150601                        S06970900             2015-06-01

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06940940_20100708                                    438      NaN      NaN
S06940940_20230623                                    408      NaN      NaN
S06960950_20160629                                    401      NaN      NaN
S06960950_20180719                                    416      NaN      NaN
S06970900_20150601                                    432      NaN      NaN

                         Achaf01    Achaf02  Achal01  Acham01  Achan01  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN      NaN      NaN
S02000008_20200708           NaN        NaN      NaN      NaN      NaN
S02000010_20070906           NaN        NaN      NaN      NaN      NaN
S02000010_20090721           NaN        NaN      NaN      NaN      NaN
S02000010_20110723           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN        NaN      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN  19.230769      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achat01   Achat02  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN       NaN      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN  6.944444      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca02  Achca03  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achde02  Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achen01    Acheu01  Achex01   Achex02  Achex03  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN       NaN      NaN
S02000008_20200708           NaN        NaN      NaN       NaN      NaN
S02000010_20070906           NaN   2.500000      NaN       NaN      NaN
S02000010_20090721           NaN  20.000000      5.0       NaN      NaN
S02000010_20110723           NaN        NaN      NaN       NaN      NaN
...                          ...        ...      ...       ...      ...
S06940940_20100708           NaN        NaN      NaN       NaN      NaN
S06940940_20230623           NaN   4.901961      NaN       NaN      NaN
S06960950_20160629           NaN        NaN      NaN  2.493766      NaN
S06960950_20180719           NaN        NaN      NaN       NaN      NaN
S06970900_20150601           NaN        NaN      NaN       NaN      NaN

                         Achfl01  Achfr01  Achfu01  Achge01  Achgr01  Achgr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      2.5      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achho03  Achhu01  Achim01  Achim02  Achim03  Achin01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achin02  Achja01  Achja02  Achjo01  Achko01  Achkr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                          Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708       5.000000      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623       4.901961      NaN      NaN      NaN      NaN
S06960950_20160629            NaN      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                           Achla02  Achla03  Achla04  Achla05  Achla06  \
SamplingOperations_code
S02000008_20170703        7.407407      NaN      NaN      NaN      NaN
S02000008_20200708        7.500000      NaN      NaN      NaN      NaN
S02000010_20070906             NaN      NaN      NaN      NaN      NaN
S02000010_20090721       15.000000      NaN      5.0      NaN      NaN
S02000010_20110723             NaN      NaN      NaN      NaN      NaN
...                            ...      ...      ...      ...      ...
S06940940_20100708             NaN      NaN      NaN      NaN      NaN
S06940940_20230623             NaN      NaN      NaN      NaN      NaN
S06960950_20160629             NaN      NaN      NaN      NaN      NaN
S06960950_20180719             NaN      NaN      NaN      NaN      NaN
S06970900_20150601             NaN      NaN      NaN      NaN      NaN

                         Achle01  Achle02  Achli01  Achli02  Achli03  Achli04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achlo01  Achlu01  Achlu02  Achma01  Achmi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN

                            Achmi02    Achmi03  Achmo01  Achmo02  Achna01  \
SamplingOperations_code
S02000008_20170703        88.888889        NaN      NaN      NaN      NaN
S02000008_20200708        12.500000        NaN      NaN      NaN      NaN
S02000010_20070906              NaN        NaN      NaN      NaN      NaN
S02000010_20090721       135.000000        NaN      NaN      NaN      NaN
S02000010_20110723        15.075377        NaN      NaN      NaN      NaN
...                             ...        ...      ...      ...      ...
S06940940_20100708         9.132420        NaN      NaN      NaN      NaN
S06940940_20230623       375.000000  14.705882      NaN      NaN      NaN
S06960950_20160629        87.281796        NaN      NaN      NaN      NaN
S06960950_20180719       298.076923        NaN      NaN      NaN      NaN
S06970900_20150601       173.611111        NaN      NaN      NaN      NaN

                         Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpe01  Achpe02  Achpf01  Achpl01  Achpo01  Achpr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpr02  Achps01  Achps02  Achps03  Achps04  Achpu01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                            Achpy01  Achre01  Achri01  Achro01  Achro02  \
SamplingOperations_code
S02000008_20170703              NaN      NaN      NaN      NaN      NaN
S02000008_20200708              NaN      NaN      NaN      NaN      NaN
S02000010_20070906              NaN      NaN      NaN      NaN      NaN
S02000010_20090721         7.500000      NaN      NaN      NaN      NaN
S02000010_20110723              NaN      NaN      NaN      NaN      NaN

In [112]:
Y.to_parquet(f"../../data/processed/03_COMPLETE_TEST.parquet", index=True)
Y

                          IBD   IBD_EQR IBD_EQR_Status
SamplingOperations_code
S02000008_20170703        9.6  0.502924           Poor
S02000008_20200708        8.0  0.409357           Poor
S02000010_20070906       14.3  0.777778       Moderate
S02000010_20090721       15.0  0.818713           Good
S02000010_20110723       16.0  0.877193           Good
...                       ...       ...            ...
S06999141_20160928       15.6  0.706667       Moderate
S06999179_20230628       20.0  1.000000           High
S06999180_20160928       19.5  0.966667           High
S06999189_20160928       16.1  0.740000       Moderate
S06999189_20220920       16.6  0.773333       Moderate

[43783 rows x 3 columns]

# Estaria muy interesante hacer uno con dates

In [114]:
X = X.drop(columns=['Date_SamplingOperation'])

# Cleaning the wide df

In [115]:
# Standard libraries
from typing import List, Tuple

# Data manipulation and numerical computation
import numpy as np
import pandas as pd

# Scikit-learn utilities
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import VarianceThreshold, f_classif, f_regression

In [116]:
def drop_exact_duplicates(X: pd.DataFrame) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drop exact duplicate columns from a DataFrame.

    This function identifies and removes columns in the DataFrame that are exact duplicates 
    of other columns. Duplicate columns are those that have identical values across all rows.

    Parameters:
    ----------
    X : pd.DataFrame
        The input DataFrame containing the features.

    Returns:
    -------
    Tuple[pd.DataFrame, List[str]]
        - A DataFrame with duplicate columns removed.
        - A list of the names of the dropped duplicate columns.

    Notes:
    -----
    - The function computes a hash signature for each column to efficiently identify duplicates.
    - If two columns have the same hash and their values are identical, one of them is dropped.

    Example Usage:
    --------------
    X, dropped_dup_cols = drop_exact_duplicates(X)
    print(f"Dropped exact duplicate columns: {dropped_dup_cols}")
    """
    sig = X.apply(lambda s: pd.util.hash_pandas_object(s, index=False).sum())
    seen = {}
    dup = []
    for c, h in sig.items():
        if h in seen and X[c].equals(X[seen[h]]):
            dup.append(c)
        else:
            seen[h] = c
    return X.drop(columns=dup), dup

# # Example usage:
# X, dropped_dup_cols = drop_exact_duplicates(X)
# print(f"Dropped exact duplicate columns: {dropped_dup_cols}")

In [117]:
def drop_high_missing(X: pd.DataFrame, thresh: float = 0.40) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drop columns with a high proportion of missing values from a DataFrame.

    This function identifies columns in the DataFrame where the proportion of missing values 
    exceeds a specified threshold and removes them. Missing values are identified as NaN 
    or the string "Unassessed", which is replaced with NaN before processing.

    Parameters:
    ----------
    X : pd.DataFrame
        The input DataFrame containing the features.
    thresh : float, optional
        The proportion threshold above which a column is considered to have high missing values 
        and is dropped. Default is 0.40 (40%).

    Returns:
    -------
    Tuple[pd.DataFrame, List[str]]
        - A DataFrame with high-missing columns removed.
        - A list of the names of the dropped columns.

    Notes:
    -----
    - The function replaces the string "Unassessed" with NaN before calculating the proportion 
      of missing values.
    - Columns with a proportion of missing values greater than `thresh` are dropped.

    Example Usage:
    --------------
    X, dropped_cols = drop_high_missing(X, thresh=0.40)
    print(f"Dropped columns with >40% missing: {dropped_cols}")
    """
    # Replace "Unassessed" with NaN
    X = X.replace("Unassessed", np.nan)

    # Identify columns with a high proportion of missing values
    to_drop = X.columns[X.isna().mean() > thresh].tolist()

    # Drop the identified columns
    X2 = X.drop(columns=to_drop)

    return X2, to_drop


# # Example usage:
# X, dropped_cols = drop_high_missing(X, thresh=0.40)
# print(f"Dropped columns with >40% missing: {dropped_cols}")

In [118]:
def drop_quasi_constant_cat(
    X: pd.DataFrame, 
    cat_cols: List[str], 
    p: float = 0.99
) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drop quasi-constant categorical columns from a DataFrame.

    This function identifies categorical columns where the most frequent value 
    accounts for at least `p` proportion of the data and removes them from the DataFrame. 
    Quasi-constant columns are those that provide little variability and are unlikely 
    to be useful for modeling.

    Parameters:
    ----------
    X : pd.DataFrame
        The input DataFrame containing the features.
    cat_cols : List[str]
        A list of categorical column names to consider for quasi-constant checking.
    p : float, optional
        The proportion threshold above which a column is considered quasi-constant.
        Default is 0.99.

    Returns:
    -------
    Tuple[pd.DataFrame, List[str]]
        - A DataFrame with quasi-constant categorical columns removed.
        - A list of the names of the dropped quasi-constant categorical columns.

    Notes:
    -----
    - The function ensures that only columns present in the DataFrame are processed.
    - Missing values are included in the value counts when determining the most frequent value.

    Example Usage:
    --------------
    cat_cols = X.select_dtypes(exclude=['number']).columns
    X, dropped_cat_cols = drop_quasi_constant_cat(X, cat_cols.tolist(), p=0.99)
    print(f"Dropped quasi-constant categorical columns: {dropped_cat_cols}")
    """
    dropped = []
    for c in cat_cols:
        # Calculate the normalized value counts (including NaNs)
        vc = X[c].value_counts(normalize=True, dropna=False)
        
        # Check if the most frequent value exceeds the threshold
        if len(vc) and vc.iloc[0] >= p:
            dropped.append(c)
    
    # Drop the identified quasi-constant columns
    X2 = X.drop(columns=dropped)
    return X2, dropped


# # Example usage:
# cat_cols = X.select_dtypes(exclude=['number']).columns
# X, dropped_cat_cols = drop_quasi_constant_cat(X, cat_cols.tolist(), p=0.99)
# print(f"Dropped quasi-constant categorical columns: {dropped_cat_cols}")

In [119]:
def drop_high_cardinality_cat(
    X: pd.DataFrame, 
    cat_cols: List[str], 
    max_unique: int = 100, 
    ratio: float = 0.50
) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drop high-cardinality categorical columns from a DataFrame.

    This function identifies categorical columns with a high number of unique values 
    (cardinality) and removes them from the DataFrame. High-cardinality columns can 
    increase the complexity of the model and may not provide significant value.

    Parameters:
    ----------
    X : pd.DataFrame
        The input DataFrame containing the features.
    cat_cols : List[str]
        A list of categorical column names to consider for cardinality checking.
    max_unique : int, optional
        The maximum number of unique values allowed in a categorical column. 
        Default is 100.
    ratio : float, optional
        The maximum ratio of unique values to the total number of rows in the DataFrame.
        Default is 0.50.

    Returns:
    -------
    Tuple[pd.DataFrame, List[str]]
        - A DataFrame with high-cardinality categorical columns removed.
        - A list of the names of the dropped high-cardinality categorical columns.

    Notes:
    -----
    - A column is considered high-cardinality if the number of unique values exceeds 
      `max_unique` or if the ratio of unique values to the total number of rows exceeds `ratio`.
    - The function ensures that only columns present in the DataFrame are processed.

    Example Usage:
    --------------
    cat_cols = X.select_dtypes(exclude=['number']).columns
    X, dropped_high_card_cols = drop_high_cardinality_cat(X, cat_cols.tolist(), max_unique=100, ratio=0.50)
    print(f"Dropped high-cardinality categorical columns: {dropped_high_card_cols}")
    """
    n = len(X)
    lim = min(max_unique, int(ratio * n))
    dropped = [c for c in cat_cols if c in X.columns and X[c].nunique(dropna=False) > lim]
    X2 = X.drop(columns=dropped)
    return X2, dropped

# # Example usage:
# cat_cols = X.select_dtypes(exclude=['number']).columns
# X, dropped_high_card_cols = drop_high_cardinality_cat(X, cat_cols.tolist(), max_unique=100, ratio=0.50)
# print(f"Dropped high-cardinality categorical columns: {dropped_high_card_cols}")

In [120]:
def drop_quasi_constant_num(
    X: pd.DataFrame, num_cols: List[str], thresh: float = 1e-5
) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drop quasi-constant numeric columns from a DataFrame.

    This function identifies numeric columns with very low variance (below a specified threshold)
    and removes them from the DataFrame. Quasi-constant columns are those that have almost the same
    value across all rows, which makes them uninformative for modeling.

    Parameters:
    ----------
    X : pd.DataFrame
        The input DataFrame containing the features.
    num_cols : List[str]
        A list of numeric column names to consider for variance checking.
    thresh : float, optional
        The variance threshold below which columns are considered quasi-constant.
        Default is 1e-5.

    Returns:
    -------
    Tuple[pd.DataFrame, List[str]]
        - A DataFrame with quasi-constant numeric columns removed.
        - A list of the names of the dropped quasi-constant numeric columns.

    Notes:
    -----
    - Missing values in the numeric columns are imputed using the median before calculating variance.
    - The VarianceThreshold from sklearn is used to identify quasi-constant columns.
    """
    if not num_cols:
        return X, []

    # Impute missing values with the median
    imp = SimpleImputer(strategy="median")
    Xn = pd.DataFrame(imp.fit_transform(X[num_cols]), columns=num_cols, index=X.index)

    # Apply VarianceThreshold to identify columns with low variance
    vt = VarianceThreshold(threshold=thresh)
    vt.fit(Xn)

    # Identify kept and dropped columns
    kept = [c for c, k in zip(num_cols, vt.get_support()) if k]
    dropped = [c for c in num_cols if c not in kept]

    # Drop the quasi-constant columns from the original DataFrame
    X2 = X.drop(columns=dropped)
    return X2, dropped


# # Example usage:
# num_cols = X.select_dtypes(include=['number']).columns  # Select numeric columns
# X, dropped_num_cols = drop_quasi_constant_num(X, num_cols.tolist(), thresh=1e-5)
# print(f"Dropped quasi-constant numeric columns: {dropped_num_cols}")

In [121]:
def prefilter_num_univariate(
    X: pd.DataFrame, y: pd.Series, num_cols: List[str], k: int = 300
) -> Tuple[pd.DataFrame, List[str], pd.Series]:
    """
    Perform a univariate feature selection for numeric columns based on their relationship with the target variable.

    This function selects the top `k` numeric features that have the highest scores in a univariate statistical test 
    (ANOVA F-value for classification or F-statistic for regression) with respect to the target variable `y`.

    Parameters:
    ----------
    X : pd.DataFrame
        The input dataframe containing features.
    y : pd.Series
        The target variable.
    num_cols : List[str]
        A list of numeric column names to consider for feature selection.
    k : int, optional
        The number of top features to keep, by default 300.

    Returns:
    -------
    Tuple[pd.DataFrame, List[str], pd.Series]
        - A dataframe containing the top `k` numeric features.
        - A list of the names of the selected top `k` numeric features.
        - A pandas Series containing the scores of all numeric features, sorted in descending order.

    Notes:
    -----
    - If the target variable `y` is numeric and has more than 20 unique values, the function uses `f_regression`.
      Otherwise, it uses `f_classif`.
    - Missing values in the numeric columns are imputed using the median before calculating the scores.
    """
    # Filter numeric columns that exist in the dataframe
    keep = [c for c in num_cols if c in X.columns]
    if not keep:
        return X, [], pd.Series(dtype=float)

    # Impute missing values with the median
    Xi = pd.DataFrame(
        SimpleImputer(strategy="median").fit_transform(X[keep]),
        columns=keep, index=X.index
    )

    # Select the appropriate statistical test based on the target variable type
    if np.issubdtype(y.dtype, np.number) and y.nunique() > 20:
        scores, _ = f_regression(Xi, y.to_numpy())
    else:
        scores, _ = f_classif(Xi, y.to_numpy())

    # Create a pandas Series of scores, sort them in descending order
    s = pd.Series(scores, index=keep).fillna(0.0).sort_values(ascending=False)

    # Select the top `k` features
    top = s.index[: min(k, len(s))].tolist()

    # Return the top features, their names, and the scores
    return pd.concat([Xi[top]], axis=1), top, s

# # Example usage:
# Xnum, top_num_cols, f_scores = prefilter_num_univariate(X, y, num_cols.tolist(), k=300)

In [122]:
def drop_zeros(X: pd.DataFrame, thresh: float = 0.95) -> Tuple[pd.DataFrame, List[str]]:
    """
    Drop columns with a high proportion of zero values from a DataFrame.

    This function identifies columns in the DataFrame where the proportion of zero values 
    exceeds a specified threshold and removes them. Columns with a high proportion of zeros 
    are often uninformative and can be excluded from further analysis.

    Parameters:
    ----------
    X : pd.DataFrame
        The input DataFrame containing the features.
    thresh : float, optional
        The proportion threshold above which a column is considered to have high zero values 
        and is dropped. Default is 0.95 (95%).

    Returns:
    -------
    Tuple[pd.DataFrame, List[str]]
        - A DataFrame with high-zero columns removed.
        - A list of the names of the dropped columns.

    Notes:
    -----
    - The function calculates the proportion of zero values in each column.
    - Columns with a proportion of zero values greater than `thresh` are dropped.

    Example Usage:
    --------------
    Xnum, dropped_cols = drop_zeros(Xnum, thresh=0.95)
    print(f"Dropped columns with >95% zeros: {dropped_cols}")
    """
    # Identify columns with a high proportion of zero values
    to_drop = X.columns[(X == 0).mean() > thresh].tolist()

    # Drop the identified columns
    X = X.drop(columns=to_drop)

    return X, to_drop


# # Example usage:
# Xnum, dropped_cols = drop_zeros(Xnum, thresh=0.95)
# print(f"Dropped columns with >95% zeros: {dropped_cols}")

# Procedimiento

In [123]:
X, dropped_dup_cols = drop_exact_duplicates(X)
print(f"Dropped exact duplicate columns: {dropped_dup_cols}")

X, dropped_cols = drop_high_missing(X, thresh=0.95)
print(f"Dropped columns with >95% missing: {dropped_cols}")

cat_cols = X.select_dtypes(exclude=['number']).columns
X, dropped_cat_cols = drop_quasi_constant_cat(X, cat_cols.tolist(), p=0.99)
print(f"Dropped quasi-constant categorical columns: {dropped_cat_cols}")

cat_cols = X.select_dtypes(exclude=['number']).columns
X, dropped_high_card_cols = drop_high_cardinality_cat(X, cat_cols.tolist(), max_unique=100, ratio=0.50)
print(f"Dropped high-cardinality categorical columns: {dropped_high_card_cols}")

num_cols = X.select_dtypes(include=['number']).columns  # Select numeric columns
X, dropped_num_cols = drop_quasi_constant_num(X, num_cols.tolist(), thresh=1e-5)
print(f"Dropped quasi-constant numeric columns: {dropped_num_cols}")

# Xnum, top_num_cols, f_scores = prefilter_num_univariate(X, y, num_cols.tolist(), k=300)

Dropped exact duplicate columns: ['Cocps01', 'Dipde01', 'Dippa01', 'Encsu01', 'Encsu02', 'Ethpu01', 'Grama01', 'Navpa06', 'Navth01', 'Navtr01', 'Nitth01', 'Opemi01', 'Parhe01', 'Plata01', 'Semro01', 'Synaf01', 'Thani01']

# Quedarnos ron info de las columnas que quitamos

In [124]:
COMPLETE_X[dropped_cols]

                         Achaa01  Achac01  Achaf01    Achaf02  Achal01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN        NaN      NaN
S02000008_20200708           NaN      NaN      NaN        NaN      NaN
S02000010_20070906           NaN      NaN      NaN        NaN      NaN
S02000010_20090721           NaN      NaN      NaN        NaN      NaN
S02000010_20110723           NaN      NaN      NaN        NaN      NaN
...                          ...      ...      ...        ...      ...
S06940940_20100708           NaN      NaN      NaN        NaN      NaN
S06940940_20230623           NaN      NaN      NaN        NaN      NaN
S06960950_20160629           NaN      NaN      NaN        NaN      NaN
S06960950_20180719           NaN      NaN      NaN  19.230769      NaN
S06970900_20150601           NaN      NaN      NaN        NaN      NaN

                         Acham01  Achan01  Achat01  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca03  Achca04  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achch01  Achcl01  Achco01  Achco03  Achco04  Achcr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achcy01  Achda01  Achda02  Achde01  Achde02  Achdi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achdi02  Achel01  Achen01  Achex01   Achex02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN       NaN
S02000008_20200708           NaN      NaN      NaN      NaN       NaN
S02000010_20070906           NaN      NaN      NaN      NaN       NaN
S02000010_20090721           NaN      NaN      NaN      5.0       NaN
S02000010_20110723           NaN      NaN      NaN      NaN       NaN
...                          ...      ...      ...      ...       ...
S06940940_20100708           NaN      NaN      NaN      NaN       NaN
S06940940_20230623           NaN      NaN      NaN      NaN       NaN
S06960950_20160629           NaN      NaN      NaN      NaN  2.493766
S06960950_20180719           NaN      NaN      NaN      NaN       NaN
S06970900_20150601           NaN      NaN      NaN      NaN       NaN

                         Achex03  Achfl01  Achfr01  Achfu01  Achgr01  Achgr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achho03  Achhu01  Achim01  Achim02  Achim03  Achin01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achin02  Achja01  Achja02  Achjo01  Achko01  Achkr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                          Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708       5.000000      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623       4.901961      NaN      NaN      NaN      NaN
S06960950_20160629            NaN      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                         Achla03  Achla05  Achla06  Achle01  Achle02  Achli01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achli02  Achli04  Achlo01  Achlu01  Achlu02  Achma01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achmi01    Achmi03  Achmo01  Achmo02  Achna01  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN      NaN      NaN
S02000008_20200708           NaN        NaN      NaN      NaN      NaN
S02000010_20070906           NaN        NaN      NaN      NaN      NaN
S02000010_20090721           NaN        NaN      NaN      NaN      NaN
S02000010_20110723           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN  14.705882      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN        NaN      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achna02  Achne01  Achni01  Achno01  Achpa01  Achpe01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpe02  Achpf01  Achpl01  Achpo01  Achpr01  Achpr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achps01  Achps02  Achps03  Achps04  Achpu01  Achre01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achro01  Achro02  Achro03  Achro04  Achru01  Achru02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achsa01  Achsc01  Achse01  Achse02  Achsi01  Achst01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achst02  Achst04  Achsu02  Achsu04  Achsu05  Achsu06  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achsu07  Achte01  Achtr01  Achtr02  Achtr03  Achtu01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achzh01  Achzi01  Actde01  Actno01  Actro01  Actse01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN

In [125]:
# sum the value per row of the dropped columns
uncommon_taxons = COMPLETE_X[dropped_cols].sum(axis=1)
uncommon_taxons = uncommon_taxons.rename("Uncommon_Taxons")
uncommon_taxons

SamplingOperations_code
S02000008_20170703     0.000000
S02000008_20200708     5.000000
S02000010_20070906    80.000000
S02000010_20090721    55.000000
S02000010_20110723    55.276382
                        ...
S06940940_20100708     2.283105
S06940940_20230623    19.607843
S06960950_20160629    24.937656
S06960950_20180719    33.653846
S06970900_20150601     0.000000
Name: Uncommon_Taxons, Length: 49441, dtype: float64

In [126]:
num_cols = X.select_dtypes(include=['number']).columns
cat_cols = X.columns.difference(num_cols)

## entropia de las categoricas por los jajas

In [127]:
X[cat_cols]

,Acidification_Status180D,Acidification_Status1Y,Acidification_Status90D,CodeDepartement,HERlvl1Name,MineralMicropollutants_Status180D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status90D,Nitrates_Status180D,Nitrates_Status1Y,Nitrates_Status90D,Nitrogencompounds_Status180D,Nitrogencompounds_Status1Y,Nitrogencompounds_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status90D,PAH_Status180D,PAH_Status1Y,PAH_Status90D,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status90D,Streamsize,SuspendedMatter_Status180D,SuspendedMatter_Status1Y,SuspendedMatter_Status90D,Watershed
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,High,High,High,68,ALSACE,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Good,Bad,Bad,Good,Good,Good,NaN,NaN,NaN,Good,Good,Moderate,TP,High,High,High,Rhin-Meuse
S02000008_20200708,Good,Good,High,68,ALSACE,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Good,Bad,Bad,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,TP,High,High,High,Rhin-Meuse
S02000010_20070906,Good,High,High,68,ALSACE,Good,Good,Good,Good,Good,Good,Good,Good,Good,Bad,Bad,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,High,High,High,None,High,High,High,Rhin-Meuse
S02000010_20090721,High,High,Good,68,ALSACE,Moderate,Moderate,Moderate,Good,Good,Good,Good,Good,Good,Bad,Bad,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,High,Good,High,None,High,High,High,Rhin-Meuse
S02000010_20110723,Good,High,High,68,ALSACE,Moderate,Moderate,Good,Good,Good,Good,Good,Good,Good,Bad,Bad,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,High,Good,High,None,High,High,High,Rhin-Meuse
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,Good,Good,Good,39,JURA-PREALPES DU NORD,NaN,NaN,NaN,Good,Good,Good,High,High,High,Bad,Bad,NaN,NaN,NaN,NaN,NaN,NaN,Good,Good,Good,P,High,High,High,Rhône-Méditerranée
S06940940_20230623,Good,Good,Good,39,JURA-PREALPES DU NORD,Good,Good,Good,Good,Good,Good,High,High,High,Bad,Bad,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,High,High,High,P,High,High,High,Rhône-Méditerranée
S06960950_20160629,Good,Good,Good,39,JURA-PREALPES DU NORD,NaN,NaN,NaN,Good,Good,High,High,High,High,Bad,Bad,NaN,NaN,NaN,NaN,NaN,NaN,High,High,High,TP,High,High,High,Rhône-Méditerranée
S06960950_20180719,Good,Good,Good,39,JURA-PREALPES DU NORD,NaN,NaN,NaN,Good,Good,Good,High,High,High,Bad,Bad,NaN,NaN,NaN,NaN,NaN,NaN,High,High,High,TP,High,High,High,Rhône-Méditerranée
S06970900_20150601,High,High,High,39,JURA-PREALPES DU NORD,NaN,Good,NaN,Good,Good,Good,High,High,High,Bad,Bad,NaN,Moderate,NaN,NaN,Moderate,NaN,High,High,Good,M,Moderate,Good,Good,Rhône-Méditerranée

In [128]:
def norm_entropy(s, *, base=2, dropna=True):
    p = s.value_counts(normalize=True, dropna=dropna).to_numpy()
    if p.size <= 1:  # constant or empty → zero entropy
        return 0.0
    H = -(p * np.log(p)).sum() / np.log(base)
    Hmax = np.log(p.size) / np.log(base)           # = log_base(k)
    return H / Hmax                                # ∈ [0,1]

# 1) compute entropy for categorical columns
ent = X[cat_cols].apply(lambda col: norm_entropy(col, dropna=False))  # treat NaN as a category
ent = ent.sort_values(ascending=False)
ent

CodeDepartement                      0.962192
Watershed                            0.857897
HERlvl1Name                          0.834808
Nitrates_Status90D                   0.808662
Nitrates_Status180D                  0.793232
Nitrates_Status1Y                    0.751677
Streamsize                           0.739976
OrganicMicropollutants_Status180D    0.727132
OrganicMicropollutants_Status90D     0.723519
OrganicMicropollutants_Status1Y      0.691784
MineralMicropollutants_Status1Y      0.664896
Phosphorouscompounds_Status90D       0.644542
MineralMicropollutants_Status180D    0.612089
MineralMicropollutants_Status90D     0.597034
Phosphorouscompounds_Status180D      0.592786
Phosphorouscompounds_Status1Y        0.578248
Nitrogencompounds_Status90D          0.575648
Nitrogencompounds_Status180D         0.535036
Nitrogencompounds_Status1Y           0.506293
PAH_Status1Y                         0.484678
SuspendedMatter_Status90D            0.472234
SuspendedMatter_Status180D           0.469656
PAH_Status180D                       0.461170
PAH_Status90D                        0.455505
SuspendedMatter_Status1Y             0.445102
Acidification_Status180D             0.358681
Acidification_Status90D              0.346520
Acidification_Status1Y               0.302926
OrganicMatter_Status90D              0.090637
OrganicMatter_Status180D             0.069234
dtype: float64

# Merge

In [129]:
X

,TotalAbundance_SamplingOperation,Achat02,Achca02,Achco02,Achde03,Achdr01,Acheu01,Achge01,Achla02,Achla04,Achli03,Achmi02,Achob01,Achpy01,Achri01,Achst03,Achsu01,Achsu03,Achth01,Ampat01,Ampin01,Ampin02,Ampov01,Amppe02,Aulam01,Calae01,Calba01,Coceu01,Cocli01,Cocpe01,Cocpl01,Crasu01,Cycat01,Cycdu01,Cycme02,Cycps01,Cymex01,Cymmi01,Cymsi01,Cymve01,Dente01,Diavu01,Dipse01,Exiva01,Fragr01,Frape01,Frave01,Fruco01,Fruvu01,Geiac01,Gombo02,Gomcu02,Gomel01,Gomex01,Gomin06,Gommi05,Gomol04,Gompa06,Gompu02,Gomte02,Gyrat01,Hipca02,Karcl01,Lutgo01,Melpu01,Melva01,Merci01,Navan05,Navat02,Navca07,Navca08,Navca11,Navco05,Navcr04,Navcr05,Navcr09,Navcr10,Navge02,Navgr01,Navla04,Navle02,Navmi09,Navmo05,Navoc01,Navpe05,Navre04,Navrh02,Navsa03,Navsi04,Navsu03,Navsu07,Navsu08,Navsu09,Navtr05,Navve03,Navvi01,Nitac04,Nitam01,Nitar01,Nitca03,Nitco07,Nitde03,Nitdi04,Nitfo01,Nitin02,Nitli03,Nitme01,Nitpa01,Nitpa02,Nitpu04,Nitre01,Nitso01,Nitso04,Nitsu01,Nitsu09,Plala02,Plaro04,Plesc01,Psebr01,Reisi01,Reiun01,Rhoab01,Selat01,Selni01,Selpu01,Selsa02,Stapi02,Steha01,Stein01,Suran01,Surbr01,Surla01,Synde01,Synul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,NaN,88.888889,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,187.654321,NaN,2.469136,NaN,44.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,2.469136,NaN,NaN,NaN,NaN,NaN,NaN,32.098765,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.728395,NaN,NaN,283.950617,NaN,NaN,NaN,NaN,19.753086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,7.407407,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,14.814815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.283951,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Moderate,High,High,High,NaN,NaN,NaN,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good
S02000008_20200708,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,12.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,10.000000,NaN,5.000000,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,NaN,NaN,NaN,NaN,7.5,137.500000,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,195.000000,10.0,NaN,432.500000,NaN,NaN,NaN,NaN,NaN,5.0,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,15.000000,12.5,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,22.500000,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,Good,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good
S02000010_20070906,400,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,12.500000,2.5,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,2.500000,NaN,NaN,NaN,NaN,15.000000,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,7.500000,5.000000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,27.5,NaN,10.000000,10.000000,35.00000,67.500000,NaN,NaN,NaN,NaN,117.500000,NaN,NaN,52.5,5.0,NaN,NaN,NaN,NaN,2.500000,25.0,NaN,17.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,147.500000,5.000000,NaN,NaN,12.5,75.0,NaN,NaN,NaN,25.000000,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,2.500000,155.000000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good
S02000010_20090721,400,NaN,NaN,NaN,NaN,NaN,20.000000,2.5,15.000000,5.0,NaN,135.000000,NaN,7.500000,NaN,NaN,2.500000,NaN,NaN,5.0,NaN,NaN,NaN,47.500000,22.5,NaN,7.500000,72.500000,NaN,32.500000,NaN,NaN,NaN,2.5,10.0,27.5,NaN,NaN,NaN,15.0,NaN,15.0,NaN,2.500000,NaN,NaN,10.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,65.0,2.5,2.5,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.500000,NaN,NaN,22.5,2.5,NaN,NaN,NaN,NaN,12.500000,NaN,NaN,7.500000,NaN,2.5,NaN,NaN,5.000000,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.500000,2.500000,NaN,NaN,NaN,NaN,32.5,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,7.5,NaN,2.500000,10.000000,NaN,32.500000,NaN,22.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate
S02000010_20110723,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.075377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.562814,NaN,5.025126,120.603015,NaN,NaN,5.025126,17.587940,NaN,NaN,7.537688,NaN,NaN,NaN,NaN,NaN,NaN,35.175879,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,22.613065,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,17.58794,2.512563,NaN,NaN,NaN,NaN,50.251256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,10.050251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.663317,10.050251,2.512563,5.025126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.703518,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.132420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,363.013699,NaN,NaN,11.415525,95.890411,NaN,4.566210,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.981735,NaN,66.210046,NaN,NaN,189.497717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.415525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,NaN,82.191781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,89.041096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.963470,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,Good,Good,Good,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN
S06940940_20230623,408,NaN,NaN,NaN,NaN,NaN,4.901961,NaN,NaN,NaN,NaN,375.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.803922,NaN,22.058824,NaN,NaN,NaN,58.823529,NaN,4.901961,14.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.764706,17.156863,NaN,115.196078,2.450980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.019608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.313725,NaN,NaN,34.313725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.156863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good
S06960950_20160629,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.281796,NaN,812.967581,NaN,NaN,12.468828,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.443890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,High,High,High,High,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN
S06960950_20180719,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.076923,NaN,598.557692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.807692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.480769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.615385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN
S06970900_20150601,432,6.944444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.611111,NaN,706.018519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.092593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.407407,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.777778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,NaN,894594.0,6580272.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,309.0,M,High,High,High,Good,Good,Good,High,High,Good,High,High,High,Moderate,NaN,NaN,Bad,Bad,Good,Moderate,Good,Moderate,NaN,NaN,Good,NaN,NaN

In [133]:
# merge both that have the same index
Xclean = pd.concat([X, uncommon_taxons], axis=1)
Xclean

,TotalAbundance_SamplingOperation,Achat02,Achca02,Achco02,Achde03,Achdr01,Acheu01,Achge01,Achla02,Achla04,Achli03,Achmi02,Achob01,Achpy01,Achri01,Achst03,Achsu01,Achsu03,Achth01,Ampat01,Ampin01,Ampin02,Ampov01,Amppe02,Aulam01,Calae01,Calba01,Coceu01,Cocli01,Cocpe01,Cocpl01,Crasu01,Cycat01,Cycdu01,Cycme02,Cycps01,Cymex01,Cymmi01,Cymsi01,Cymve01,Dente01,Diavu01,Dipse01,Exiva01,Fragr01,Frape01,Frave01,Fruco01,Fruvu01,Geiac01,Gombo02,Gomcu02,Gomel01,Gomex01,Gomin06,Gommi05,Gomol04,Gompa06,Gompu02,Gomte02,Gyrat01,Hipca02,Karcl01,Lutgo01,Melpu01,Melva01,Merci01,Navan05,Navat02,Navca07,Navca08,Navca11,Navco05,Navcr04,Navcr05,Navcr09,Navcr10,Navge02,Navgr01,Navla04,Navle02,Navmi09,Navmo05,Navoc01,Navpe05,Navre04,Navrh02,Navsa03,Navsi04,Navsu03,Navsu07,Navsu08,Navsu09,Navtr05,Navve03,Navvi01,Nitac04,Nitam01,Nitar01,Nitca03,Nitco07,Nitde03,Nitdi04,Nitfo01,Nitin02,Nitli03,Nitme01,Nitpa01,Nitpa02,Nitpu04,Nitre01,Nitso01,Nitso04,Nitsu01,Nitsu09,Plala02,Plaro04,Plesc01,Psebr01,Reisi01,Reiun01,Rhoab01,Selat01,Selni01,Selpu01,Selsa02,Stapi02,Steha01,Stein01,Suran01,Surbr01,Surla01,Synde01,Synul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D,Uncommon_Taxons
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,NaN,88.888889,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,187.654321,NaN,2.469136,NaN,44.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,2.469136,NaN,NaN,NaN,NaN,NaN,NaN,32.098765,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.728395,NaN,NaN,283.950617,NaN,NaN,NaN,NaN,19.753086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,7.407407,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,14.814815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.283951,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Moderate,High,High,High,NaN,NaN,NaN,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,0.000000
S02000008_20200708,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,12.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,10.000000,NaN,5.000000,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,NaN,NaN,NaN,NaN,7.5,137.500000,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,195.000000,10.0,NaN,432.500000,NaN,NaN,NaN,NaN,NaN,5.0,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,15.000000,12.5,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,22.500000,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,Good,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,5.000000
S02000010_20070906,400,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,12.500000,2.5,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,2.500000,NaN,NaN,NaN,NaN,15.000000,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,7.500000,5.000000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,27.5,NaN,10.000000,10.000000,35.00000,67.500000,NaN,NaN,NaN,NaN,117.500000,NaN,NaN,52.5,5.0,NaN,NaN,NaN,NaN,2.500000,25.0,NaN,17.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,147.500000,5.000000,NaN,NaN,12.5,75.0,NaN,NaN,NaN,25.000000,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,2.500000,155.000000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,80.000000
S02000010_20090721,400,NaN,NaN,NaN,NaN,NaN,20.000000,2.5,15.000000,5.0,NaN,135.000000,NaN,7.500000,NaN,NaN,2.500000,NaN,NaN,5.0,NaN,NaN,NaN,47.500000,22.5,NaN,7.500000,72.500000,NaN,32.500000,NaN,NaN,NaN,2.5,10.0,27.5,NaN,NaN,NaN,15.0,NaN,15.0,NaN,2.500000,NaN,NaN,10.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,65.0,2.5,2.5,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.500000,NaN,NaN,22.5,2.5,NaN,NaN,NaN,NaN,12.500000,NaN,NaN,7.500000,NaN,2.5,NaN,NaN,5.000000,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.500000,2.500000,NaN,NaN,NaN,NaN,32.5,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,7.5,NaN,2.500000,10.000000,NaN,32.500000,NaN,22.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,55.000000
S02000010_20110723,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.075377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.562814,NaN,5.025126,120.603015,NaN,NaN,5.025126,17.587940,NaN,NaN,7.537688,NaN,NaN,NaN,NaN,NaN,NaN,35.175879,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,22.613065,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,17.58794,2.512563,NaN,NaN,NaN,NaN,50.251256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,10.050251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.663317,10.050251,2.512563,5.025126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.703518,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Good,55.276382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.132420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,363.013699,NaN,NaN,11.415525,95.890411,NaN,4.566210,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.981735,NaN,66.210046,NaN,NaN,189.497717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.415525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,NaN,82.191781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,89.041096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.963470,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,Good,Good,Good,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN,2.283105
S06940940_20230623,408,NaN,NaN,NaN,NaN,NaN,4.901961,NaN,NaN,NaN,NaN,375.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.803922,NaN,22.058824,NaN,NaN,NaN,58.823529,NaN,4.901961,14.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.764706,17.156863,NaN,115.196078,2.450980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.019608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.313725,NaN,NaN,34.313725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.156863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,19.607843
S06960950_20160629,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.281796,NaN,812.967581,NaN,NaN,12.468828,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.443890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,High,High,High,High,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN,24.937656
S06960950_20180719,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.076923,NaN,598.557692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.807692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.480769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.615385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN,33.653846
S06970900_20150601,432,6.944444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.611111,NaN,706.018519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.092593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.407407,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.777778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,NaN,894594.0,6580272.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,309.0,M,High,High,High,Good,Good,Good,High,High,Good,High,High,High,Moderate,NaN,NaN,Bad,Bad,Good,Moderate,Good,Moderate,NaN,NaN,Good,NaN,NaN,0.000000

In [134]:
cleandf = Xclean.join(Y, how='left')
cleandf

,TotalAbundance_SamplingOperation,Achat02,Achca02,Achco02,Achde03,Achdr01,Acheu01,Achge01,Achla02,Achla04,Achli03,Achmi02,Achob01,Achpy01,Achri01,Achst03,Achsu01,Achsu03,Achth01,Ampat01,Ampin01,Ampin02,Ampov01,Amppe02,Aulam01,Calae01,Calba01,Coceu01,Cocli01,Cocpe01,Cocpl01,Crasu01,Cycat01,Cycdu01,Cycme02,Cycps01,Cymex01,Cymmi01,Cymsi01,Cymve01,Dente01,Diavu01,Dipse01,Exiva01,Fragr01,Frape01,Frave01,Fruco01,Fruvu01,Geiac01,Gombo02,Gomcu02,Gomel01,Gomex01,Gomin06,Gommi05,Gomol04,Gompa06,Gompu02,Gomte02,Gyrat01,Hipca02,Karcl01,Lutgo01,Melpu01,Melva01,Merci01,Navan05,Navat02,Navca07,Navca08,Navca11,Navco05,Navcr04,Navcr05,Navcr09,Navcr10,Navge02,Navgr01,Navla04,Navle02,Navmi09,Navmo05,Navoc01,Navpe05,Navre04,Navrh02,Navsa03,Navsi04,Navsu03,Navsu07,Navsu08,Navsu09,Navtr05,Navve03,Navvi01,Nitac04,Nitam01,Nitar01,Nitca03,Nitco07,Nitde03,Nitdi04,Nitfo01,Nitin02,Nitli03,Nitme01,Nitpa01,Nitpa02,Nitpu04,Nitre01,Nitso01,Nitso04,Nitsu01,Nitsu09,Plala02,Plaro04,Plesc01,Psebr01,Reisi01,Reiun01,Rhoab01,Selat01,Selni01,Selpu01,Selsa02,Stapi02,Steha01,Stein01,Suran01,Surbr01,Surla01,Synde01,Synul01,Vibtr01,Longitude_Lambert93,Latitude_Lambert93,Watershed,CodeDepartement,HERlvl1Code,HERlvl1Name,HERlvl2Code,Altitude,Streamsize,Nitrogencompounds_Status1Y,Nitrogencompounds_Status180D,Nitrogencompounds_Status90D,Nitrates_Status1Y,Nitrates_Status180D,Nitrates_Status90D,Phosphorouscompounds_Status1Y,Phosphorouscompounds_Status180D,Phosphorouscompounds_Status90D,Acidification_Status1Y,Acidification_Status180D,Acidification_Status90D,PAH_Status1Y,PAH_Status180D,PAH_Status90D,OrganicMatter_Status180D,OrganicMatter_Status90D,SuspendedMatter_Status1Y,SuspendedMatter_Status180D,SuspendedMatter_Status90D,OrganicMicropollutants_Status1Y,OrganicMicropollutants_Status180D,OrganicMicropollutants_Status90D,MineralMicropollutants_Status1Y,MineralMicropollutants_Status180D,MineralMicropollutants_Status90D,Uncommon_Taxons,IBD,IBD_EQR,IBD_EQR_Status
SamplingOperations_code,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
S02000008_20170703,405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,NaN,88.888889,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,187.654321,NaN,2.469136,NaN,44.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,2.469136,NaN,NaN,NaN,NaN,NaN,NaN,32.098765,4.938272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.728395,NaN,NaN,283.950617,NaN,NaN,NaN,NaN,19.753086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.469136,NaN,NaN,NaN,7.407407,NaN,NaN,NaN,NaN,NaN,7.407407,NaN,14.814815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.283951,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Good,Good,Moderate,High,High,High,NaN,NaN,NaN,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,0.000000,9.6,0.502924,Poor
S02000008_20200708,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,12.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,10.000000,NaN,5.000000,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,NaN,NaN,NaN,NaN,7.5,137.500000,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,195.000000,10.0,NaN,432.500000,NaN,NaN,NaN,NaN,NaN,5.0,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,15.000000,12.5,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,22.500000,1039055.0,6721258.0,Rhin-Meuse,68,18,ALSACE,73,0.0,TP,Good,Good,Good,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,Good,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Good,Good,Good,Good,Good,Good,5.000000,8.0,0.409357,Poor
S02000010_20070906,400,NaN,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,12.500000,2.5,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,2.500000,NaN,NaN,NaN,NaN,15.000000,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,7.500000,5.000000,2.500000,NaN,NaN,NaN,NaN,NaN,NaN,27.5,NaN,10.000000,10.000000,35.00000,67.500000,NaN,NaN,NaN,NaN,117.500000,NaN,NaN,52.5,5.0,NaN,NaN,NaN,NaN,2.500000,25.0,NaN,17.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,147.500000,5.000000,NaN,NaN,12.5,75.0,NaN,NaN,NaN,25.000000,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,2.500000,155.000000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,80.000000,14.3,0.777778,Moderate
S02000010_20090721,400,NaN,NaN,NaN,NaN,NaN,20.000000,2.5,15.000000,5.0,NaN,135.000000,NaN,7.500000,NaN,NaN,2.500000,NaN,NaN,5.0,NaN,NaN,NaN,47.500000,22.5,NaN,7.500000,72.500000,NaN,32.500000,NaN,NaN,NaN,2.5,10.0,27.5,NaN,NaN,NaN,15.0,NaN,15.0,NaN,2.500000,NaN,NaN,10.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,NaN,NaN,NaN,7.500000,NaN,NaN,NaN,NaN,65.0,2.5,2.5,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.500000,NaN,NaN,22.5,2.5,NaN,NaN,NaN,NaN,12.500000,NaN,NaN,7.500000,NaN,2.5,NaN,NaN,5.000000,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.500000,2.500000,NaN,NaN,NaN,NaN,32.5,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,7.5,NaN,2.500000,10.000000,NaN,32.500000,NaN,22.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.500000,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,High,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Moderate,55.000000,15.0,0.818713,Good
S02000010_20110723,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.075377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.562814,NaN,5.025126,120.603015,NaN,NaN,5.025126,17.587940,NaN,NaN,7.537688,NaN,NaN,NaN,NaN,NaN,NaN,35.175879,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,22.613065,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,NaN,2.512563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,17.58794,2.512563,NaN,NaN,NaN,NaN,50.251256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.512563,NaN,10.050251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.663317,10.050251,2.512563,5.025126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.703518,1039381.0,6737723.0,Rhin-Meuse,68,18,ALSACE,62,246.0,None,Good,Good,Good,Good,Good,Good,Good,High,High,High,Good,High,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Moderate,Moderate,Good,55.276382,16.0,0.877193,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S06940940_20100708,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.132420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,363.013699,NaN,NaN,11.415525,95.890411,NaN,4.566210,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,4.566210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.981735,NaN,66.210046,NaN,NaN,189.497717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.415525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,NaN,82.191781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,89.041096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.963470,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,Good,Good,Good,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN,2.283105,NaN,NaN,NaN
S06940940_20230623,408,NaN,NaN,NaN,NaN,NaN,4.901961,NaN,NaN,NaN,NaN,375.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.803922,NaN,22.058824,NaN,NaN,NaN,58.823529,NaN,4.901961,14.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.764706,17.156863,NaN,115.196078,2.450980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.019608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.313725,NaN,NaN,34.313725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.156863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.058824,916758.0,6659313.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,256.0,P,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,Moderate,Moderate,Moderate,Bad,Bad,High,High,High,Moderate,Moderate,Moderate,Good,Good,Good,19.607843,NaN,NaN,NaN
S06960950_20160629,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.281796,NaN,812.967581,NaN,NaN,12.468828,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.443890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.493766,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,High,High,High,High,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN,24.937656,NaN,NaN,NaN
S06960950_20180719,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298.076923,NaN,598.557692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.807692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.480769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.615385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.403846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,897170.0,6594575.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,366.0,TP,High,High,High,Good,Good,Good,High,High,High,Good,Good,Good,NaN,NaN,NaN,Bad,Bad,High,High,High,NaN,NaN,NaN,NaN,NaN,NaN,33.653846,NaN,NaN,NaN
S06970900_20150601,432,6.944444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.611111,NaN,706.018519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.092593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.407407,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.777778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,2.314815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.629630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314815,NaN,894594.0,6580272.0,Rhône-Méditerranée,39,5,JURA-PREALPES DU NORD,2,309.0,M,High,High,High,Good,Good,Good,High,High,Good,High,High,High,Moderate,NaN,NaN,Bad,Bad,Good,Moderate,Good,Moderate,NaN,NaN,Good,NaN,NaN,0.000000,NaN,NaN,NaN

In [135]:
cleandf.to_parquet(f"../../data/processed/03_CLEAN_COMPLETE_DF.parquet", index=True)