In [1]:
from scripts import mapping
import pandas as pd

In [2]:
ranges_continuous = mapping.get_ranges2()

In [3]:
preds = pd.read_csv('results/015_Catboost2/99_Catboost_InterpolatedFULL.csv')

C:\Users\herie\AppData\Local\Temp\ipykernel_4416\2240014572.py:1: DtypeWarning: Columns (3199) have mixed types. Specify dtype option on import or set low_memory=False.
  preds = pd.read_csv('results/015_Catboost2/99_Catboost_InterpolatedFULL.csv')

In [ ]:
preds = preds.rename(columns={"IBD_EQR_Status": "IBD_pred"})
preds

,SamplingOperations_code,CodeSite_SamplingOperations_x,Date_SamplingOperation,TotalAbundance_SamplingOperation,Achaa01,Achac01,Achaf01,Achaf02,Achal01,Acham01,...,Mean90Days_3336_ip,Mean90Days_5275_ip,Mean90Days_5474_ip,Mean90Days_5986_ip,Mean90Days_6372_ip,Mean90Days_6598_ip,Mean90Days_6600_ip,Mean90Days_7074_ip,Mean90Days_XOMP_ip,IBD_pred
0,S05235850_20070709,S05235850,20070709,400,NaN,NaN,2.5,NaN,NaN,NaN,...,1.927105e-24,1.107411e-04,0.065000,9.692319e-15,0.000650,0.000000e+00,0.000000e+00,0.001650,0.573500,20.841935
1,S05113000_20070723,S05113000,20070723,433,NaN,NaN,NaN,NaN,NaN,NaN,...,4.267023e-24,4.012233e-04,0.129358,1.028713e-06,0.000650,0.000000e+00,0.000000e+00,0.001650,0.573500,8.754865
2,S05111500_20070724,S05111500,20070724,414,NaN,NaN,NaN,NaN,NaN,NaN,...,2.836976e-26,4.619344e-04,0.211661,7.534479e-10,0.000650,0.000000e+00,0.000000e+00,0.001650,0.573500,10.500764
3,S05082000_20070724,S05082000,20070724,400,NaN,NaN,NaN,NaN,NaN,NaN,...,9.927179e-24,7.110141e-04,0.187330,1.127782e-14,0.000650,4.088550e-26,0.000000e+00,0.001650,0.573500,14.455557
4,S05025600_20070725,S05025600,20070725,417,NaN,NaN,NaN,NaN,NaN,NaN,...,1.379526e-14,3.031266e-04,0.065000,0.000000e+00,0.000650,3.363481e-12,0.000000e+00,0.001650,0.513006,11.302982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5658,S06173650_20230720,S06173650,20230720,416,NaN,NaN,NaN,NaN,NaN,NaN,...,1.353502e-02,3.000000e-01,0.065000,1.000000e-03,0.000397,6.500001e-02,0.000000e+00,0.000421,0.231249,14.459938
5659,S06076420_20230726,S06076420,20230726,399,NaN,NaN,NaN,NaN,NaN,NaN,...,1.401632e-02,2.163182e-22,0.065000,1.000000e-03,0.000395,6.500000e-02,2.190902e-05,0.000260,0.163500,17.285442
5660,S06830139_20230818,S06830139,20230818,394,NaN,NaN,NaN,NaN,NaN,NaN,...,1.496733e-02,1.859137e-26,0.065000,1.000000e-03,0.000419,6.500000e-02,3.596059e-16,0.000650,0.260054,17.583061
5661,S06178000_20230822,S06178000,20230822,411,NaN,NaN,NaN,NaN,NaN,NaN,...,1.350293e-02,3.000000e-01,0.065000,1.000000e-03,0.000395,6.500000e-02,0.000000e+00,0.000260,0.163500,13.402438
5662,S06830142_20230830,S06830142,20230830,404,NaN,NaN,NaN,NaN,NaN,NaN,...,1.409632e-02,0.000000e+00,0.065000,1.000000e-03,0.000395,6.500000e-02,3.999728e-24,0.000671,0.213712,19.852828

In [6]:
preds = preds[['IBD_pred', 'SamplingOperations_code']]
preds

       IBD_pred SamplingOperations_code
0     20.841935      S05235850_20070709
1      8.754865      S05113000_20070723
2     10.500764      S05111500_20070724
3     14.455557      S05082000_20070724
4     11.302982      S05025600_20070725
...         ...                     ...
5658  14.459938      S06173650_20230720
5659  17.285442      S06076420_20230726
5660  17.583061      S06830139_20230818
5661  13.402438      S06178000_20230822
5662  19.852828      S06830142_20230830

[5663 rows x 2 columns]

In [6]:
# preds = pd.read_parquet("results/013_Catboost_FullIBD_Training_pred.parquet")
# preds = preds[['SamplingOperations_code','IBD_pred']]
# # rename
# preds = preds.rename(columns={'IBD_pred':'IBD_EQR'})
# preds.to_csv("results/013_Catboost_Full_IBD_Training/013_IBD.csv", index=False)
# preds

In [7]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="IBD_pred", output_file="results/015_Catboost2/98_Status.csv")
send_results.head()

Assigned groups based on HERlvl1Name.
Saved predictions to results/015_Catboost2/98_Status.csv

                        IBD_EQR_Status
SamplingOperations_code
S05235850_20070709                High
S05113000_20070723                Poor
S05111500_20070724            Moderate
S05082000_20070724                Good
S05025600_20070725            Moderate

In [8]:
send_results['IBD_EQR_Status'].value_counts()

IBD_EQR_Status
Good        2205
Moderate    1824
High        1261
Poor         327
Bad           43
Name: count, dtype: int64

In [8]:
# count NaNs in send_results
send_results[send_results['IBD_EQR_Status'].isna()]

                        IBD_EQR_Status
SamplingOperations_code
S06135350_20130307                 NaN
S06150795_20140212                 NaN
S05225095_20200804                 NaN

In [9]:
preds = preds.set_index('SamplingOperations_code')
preds

                          IBD_pred
SamplingOperations_code
S05235850_20070709       20.841935
S05113000_20070723        8.754865
S05111500_20070724       10.500764
S05082000_20070724       14.455557
S05025600_20070725       11.302982
...                            ...
S06173650_20230720       14.459938
S06076420_20230726       17.285442
S06830139_20230818       17.583061
S06178000_20230822       13.402438
S06830142_20230830       19.852828

[5663 rows x 1 columns]

In [10]:
# replace the NaNs with High in send_results
send_results['IBD_EQR_Status'] = send_results['IBD_EQR_Status'].fillna('High')
send_results['IBD_EQR_Status'].value_counts()

IBD_EQR_Status
Good        2194
Moderate    1846
High        1266
Poor         316
Bad           41
Name: count, dtype: int64

In [11]:
send_results.to_csv("results/015_Catboost2/99_Status.csv", index=True)
send_results

                        IBD_EQR_Status
SamplingOperations_code
S05235850_20070709                High
S05113000_20070723                Poor
S05111500_20070724            Moderate
S05082000_20070724                Good
S05025600_20070725            Moderate
...                                ...
S06173650_20230720                Good
S06076420_20230726                Good
S06830139_20230818                Good
S06178000_20230822            Moderate
S06830142_20230830                High

[5663 rows x 1 columns]