In [1]:
from scripts import mapping
import pandas as pd

In [2]:
ranges_continuous = mapping.get_ranges2()

In [3]:
preds = pd.read_csv('results/015_Catboost2/99_Catboost_Based_on_08.csv  ')

In [4]:
preds = preds.rename(columns={"IBD_EQR_Status": "IBD_pred"})
preds

     SamplingOperations_code   IBD_pred
0         S05235850_20070709  20.760468
1         S05113000_20070723   8.663042
2         S05082000_20070724  14.338771
3         S05111500_20070724  10.711860
4         S05086000_20070725  14.799649
...                      ...        ...
5658      S06173650_20230720  14.705441
5659      S06076420_20230726  17.047472
5660      S06830139_20230818  17.399340
5661      S06178000_20230822  13.372991
5662      S06830142_20230830  19.902152

[5663 rows x 2 columns]

In [6]:
# preds = pd.read_parquet("results/013_Catboost_FullIBD_Training_pred.parquet")
# preds = preds[['SamplingOperations_code','IBD_pred']]
# # rename
# preds = preds.rename(columns={'IBD_pred':'IBD_EQR'})
# preds.to_csv("results/013_Catboost_Full_IBD_Training/013_IBD.csv", index=False)
# preds

In [7]:
send_results = mapping.get_results2(preds, ranges_continuous, pred_col="IBD_pred", output_file="results/015_Catboost2/99_Status.csv")
send_results.head()

Assigned groups based on HERlvl1Name.
Saved predictions to results/015_Catboost2/99_Status.csv

                        IBD_EQR_Status
SamplingOperations_code
S05235850_20070709                High
S05113000_20070723                Poor
S05082000_20070724            Moderate
S05111500_20070724            Moderate
S05086000_20070725                Good

In [8]:
send_results['IBD_EQR_Status'].value_counts()

IBD_EQR_Status
Good        2205
Moderate    1824
High        1261
Poor         327
Bad           43
Name: count, dtype: int64

In [9]:
# count NaNs in send_results
send_results[send_results['IBD_EQR_Status'].isna()]

                        IBD_EQR_Status
SamplingOperations_code
S06135350_20130307                 NaN
S05055150_20150624                 NaN
S06159930_20220221                 NaN

In [10]:
preds = preds.set_index('SamplingOperations_code')
preds

                          IBD_pred
SamplingOperations_code
S05235850_20070709       20.760468
S05113000_20070723        8.663042
S05082000_20070724       14.338771
S05111500_20070724       10.711860
S05086000_20070725       14.799649
...                            ...
S06173650_20230720       14.705441
S06076420_20230726       17.047472
S06830139_20230818       17.399340
S06178000_20230822       13.372991
S06830142_20230830       19.902152

[5663 rows x 1 columns]

In [11]:
# replace the NaNs with High in send_results
send_results['IBD_EQR_Status'] = send_results['IBD_EQR_Status'].fillna('High')
send_results['IBD_EQR_Status'].value_counts()

IBD_EQR_Status
Good        2205
Moderate    1824
High        1264
Poor         327
Bad           43
Name: count, dtype: int64

In [14]:
send_results.to_csv("results/015_Catboost2/99_Status.csv", index=True)
send_results

                        IBD_EQR_Status
SamplingOperations_code
S05235850_20070709                High
S05113000_20070723                Poor
S05082000_20070724            Moderate
S05111500_20070724            Moderate
S05086000_20070725                Good
...                                ...
S06173650_20230720                Good
S06076420_20230726                Good
S06830139_20230818                Good
S06178000_20230822            Moderate
S06830142_20230830                High

[5663 rows x 1 columns]