In [ ]:
quitar esto para correr JAOJA CASI MANDO UNA

In [11]:
import requests

BASE_URL = "https://datathon.digitalizados.mx/"
TEAM_KEY = "CAJY-QU4X-7A4T"

In [12]:
r = requests.get(f"{BASE_URL}/health", timeout=10)
r.status_code, r.json()

(200, {'status': 'ok'})

In [10]:
import pandas as pd

# read example submission
FILE_NAME = "results/015_Catboost2/98_Status.csv"
read_example = pd.read_csv(FILE_NAME)
read_example

     SamplingOperations_code IBD_EQR_Status
0         S05235850_20070709           High
1         S05113000_20070723           Poor
2         S05111500_20070724       Moderate
3         S05082000_20070724           Good
4         S05025600_20070725       Moderate
...                      ...            ...
5658      S06173650_20230720           Good
5659      S06076420_20230726           Good
5660      S06830139_20230818           Good
5661      S06178000_20230822       Moderate
5662      S06830142_20230830           High

[5663 rows x 2 columns]

In [13]:
read_example[read_example['IBD_EQR_Status'].isna()]

     SamplingOperations_code IBD_EQR_Status
1222      S06135350_20130307            NaN
1623      S06150795_20140212            NaN
4644      S05225095_20200804            NaN

In [14]:
# fill NaN with High
read_example['IBD_EQR_Status'] = read_example['IBD_EQR_Status'].fillna('High')
read_example

     SamplingOperations_code IBD_EQR_Status
0         S05235850_20070709           High
1         S05113000_20070723           Poor
2         S05111500_20070724       Moderate
3         S05082000_20070724           Good
4         S05025600_20070725       Moderate
...                      ...            ...
5658      S06173650_20230720           Good
5659      S06076420_20230726           Good
5660      S06830139_20230818           Good
5661      S06178000_20230822       Moderate
5662      S06830142_20230830           High

[5663 rows x 2 columns]

In [16]:
read_example[read_example['IBD_EQR_Status'].isna()]

Empty DataFrame
Columns: [SamplingOperations_code, IBD_EQR_Status]
Index: []

In [17]:
#    Asegúrate de que tu CSV tenga encabezados: SamplingOperations_code,IBD_EQR_Status
with open(FILE_NAME, "rb") as f:
    files = {"file": (FILE_NAME, f, "text/csv")}
    data = {"team_key": TEAM_KEY}
    r = requests.post(f"{BASE_URL}/submit", data=data, files=files, timeout=30)

print("submit:", r.status_code, r.text)

submit: 200 {"status":"ok","accuracy":0.914083,"n_correct":4628,"n_total":5063,"daily_limit":2,"used_today":2,"remaining_today":0}