# Comparacion de modelos de clasificacion HistGradientBoosting, LightGBM, CatBoost, XGBoost

In [1]:
# Standard libraries
import os
import warnings

In [2]:

# Data manipulation and numerical computation
import numpy as np
import pandas as pd

In [3]:
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Scikit-learn utilities
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, cross_val_predict
from sklearn.metrics import (
    balanced_accuracy_score, f1_score, confusion_matrix, classification_report
)
from sklearn.calibration import CalibratedClassifierCV

In [5]:

from typing import Dict, Any, List, Optional, Tuple
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import loguniform, randint, uniform
from sklearn.base import BaseEstimator, ClassifierMixin, clone
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, cross_val_predict
from sklearn.metrics import balanced_accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import HistGradientBoostingClassifier

# --- add near imports ---
import os, json, re
from pathlib import Path
from datetime import datetime
import joblib

import os, json
from pathlib import Path
from datetime import datetime
import joblib
import re

In [6]:
# Statistical distributions
from scipy.stats import loguniform, randint, uniform

# Typing utilities
from typing import Dict, Any, List, Optional, Tuple

In [7]:
sns.set(style="ticks", context="notebook", palette="deep")
pd.set_option('display.max_columns', None)
palette = {'Bad':'#b2182b','Poor':'#d6604d','Moderate':'#f1a340','Good':'#5aae61','High':'#1b7837'}

In [8]:
path = "../../../data/processed/"
dfs = {}

# read 03_CLEAN_COMPLETE_DF.parquet
df1 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_train.parquet"))
df2 = pd.read_parquet(os.path.join(path, "taxones_pressure_epm_predict.parquet"))
df = pd.concat([df1, df2], ignore_index=True)

In [9]:
# change unassessed values to NaN
df = df.replace("Unassessed", np.nan)
df = df.replace("None", np.nan)

# index SamplingOperations_code
df = df.set_index('SamplingOperations_code')
 
# DROP HERlvl2Code	Altitude Longitude_Lambert93	Latitude_Lambert93	Watershed	CodeDepartement	HERlvl1Code
df = df.drop(columns=['HERlvl2Code', 'HERlvl2Name', 'HERlvl1Name', 'Altitude','Longitude_Lambert93','Latitude_Lambert93','Watershed','CodeDepartement', 'Date_SamplingOperation'])
df

                        CodeSite_SamplingOperations_x  \
SamplingOperations_code
S02000008_20170703                          S02000008
S02000008_20200708                          S02000008
S02000010_20070906                          S02000010
S02000010_20090721                          S02000010
S02000010_20110723                          S02000010
...                                               ...
S06940940_20100708                          S06940940
S06940940_20230623                          S06940940
S06960950_20160629                          S06960950
S06960950_20180719                          S06960950
S06970900_20150601                          S06970900

                         TotalAbundance_SamplingOperation  Achaa01  Achac01  \
SamplingOperations_code
S02000008_20170703                                    405      NaN      NaN
S02000008_20200708                                    400      NaN      NaN
S02000010_20070906                                    400      NaN      NaN
S02000010_20090721                                    400      NaN      NaN
S02000010_20110723                                    398      NaN      NaN
...                                                   ...      ...      ...
S06940940_20100708                                    438      NaN      NaN
S06940940_20230623                                    408      NaN      NaN
S06960950_20160629                                    401      NaN      NaN
S06960950_20180719                                    416      NaN      NaN
S06970900_20150601                                    432      NaN      NaN

                         Achaf01    Achaf02  Achal01  Acham01  Achan01  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN      NaN      NaN
S02000008_20200708           NaN        NaN      NaN      NaN      NaN
S02000010_20070906           NaN        NaN      NaN      NaN      NaN
S02000010_20090721           NaN        NaN      NaN      NaN      NaN
S02000010_20110723           NaN        NaN      NaN      NaN      NaN
...                          ...        ...      ...      ...      ...
S06940940_20100708           NaN        NaN      NaN      NaN      NaN
S06940940_20230623           NaN        NaN      NaN      NaN      NaN
S06960950_20160629           NaN        NaN      NaN      NaN      NaN
S06960950_20180719           NaN  19.230769      NaN      NaN      NaN
S06970900_20150601           NaN        NaN      NaN      NaN      NaN

                         Achat01   Achat02  Achat03  Achba01  Achbi01  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN       NaN      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN  6.944444      NaN      NaN      NaN

                         Achbi02   Achbr01  Achca01  Achca02  Achca03  \
SamplingOperations_code
S02000008_20170703           NaN       NaN      NaN      NaN      NaN
S02000008_20200708           NaN       NaN      NaN      NaN      NaN
S02000010_20070906           NaN       NaN      NaN      NaN      NaN
S02000010_20090721           NaN       NaN      NaN      NaN      NaN
S02000010_20110723           NaN       NaN      NaN      NaN      NaN
...                          ...       ...      ...      ...      ...
S06940940_20100708           NaN  2.283105      NaN      NaN      NaN
S06940940_20230623           NaN       NaN      NaN      NaN      NaN
S06960950_20160629           NaN       NaN      NaN      NaN      NaN
S06960950_20180719           NaN       NaN      NaN      NaN      NaN
S06970900_20150601           NaN       NaN      NaN      NaN      NaN

                         Achca04  Achch01  Achcl01  Achco01  Achco02  Achco03  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achco04  Achcr01  Achcy01  Achda01  Achda02  Achde01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achde02  Achde03  Achdi01  Achdi02  Achdr01  Achel01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achen01    Acheu01  Achex01   Achex02  Achex03  \
SamplingOperations_code
S02000008_20170703           NaN        NaN      NaN       NaN      NaN
S02000008_20200708           NaN        NaN      NaN       NaN      NaN
S02000010_20070906           NaN   2.500000      NaN       NaN      NaN
S02000010_20090721           NaN  20.000000      5.0       NaN      NaN
S02000010_20110723           NaN        NaN      NaN       NaN      NaN
...                          ...        ...      ...       ...      ...
S06940940_20100708           NaN        NaN      NaN       NaN      NaN
S06940940_20230623           NaN   4.901961      NaN       NaN      NaN
S06960950_20160629           NaN        NaN      NaN  2.493766      NaN
S06960950_20180719           NaN        NaN      NaN       NaN      NaN
S06970900_20150601           NaN        NaN      NaN       NaN      NaN

                         Achfl01  Achfr01  Achfu01  Achge01  Achgr01  Achgr02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      2.5      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achgr03  Achha01  Achhe01  Achhi01  Achho01  Achho02  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achho03  Achhu01  Achim01  Achim02  Achim03  Achin01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achin02  Achja01  Achja02  Achjo01  Achko01  Achkr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                          Achkr02  Achkr03  Achkr04  Achku01  Achla01  \
SamplingOperations_code
S02000008_20170703            NaN      NaN      NaN      NaN      NaN
S02000008_20200708       5.000000      NaN      NaN      NaN      NaN
S02000010_20070906            NaN      NaN      NaN      NaN      NaN
S02000010_20090721            NaN      NaN      NaN      NaN      NaN
S02000010_20110723            NaN      NaN      NaN      NaN      NaN
...                           ...      ...      ...      ...      ...
S06940940_20100708            NaN      NaN      NaN      NaN      NaN
S06940940_20230623       4.901961      NaN      NaN      NaN      NaN
S06960950_20160629            NaN      NaN      NaN      NaN      NaN
S06960950_20180719            NaN      NaN      NaN      NaN      NaN
S06970900_20150601            NaN      NaN      NaN      NaN      NaN

                           Achla02  Achla03  Achla04  Achla05  Achla06  \
SamplingOperations_code
S02000008_20170703        7.407407      NaN      NaN      NaN      NaN
S02000008_20200708        7.500000      NaN      NaN      NaN      NaN
S02000010_20070906             NaN      NaN      NaN      NaN      NaN
S02000010_20090721       15.000000      NaN      5.0      NaN      NaN
S02000010_20110723             NaN      NaN      NaN      NaN      NaN
...                            ...      ...      ...      ...      ...
S06940940_20100708             NaN      NaN      NaN      NaN      NaN
S06940940_20230623             NaN      NaN      NaN      NaN      NaN
S06960950_20160629             NaN      NaN      NaN      NaN      NaN
S06960950_20180719             NaN      NaN      NaN      NaN      NaN
S06970900_20150601             NaN      NaN      NaN      NaN      NaN

                         Achle01  Achle02  Achli01  Achli02  Achli03  Achli04  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achlo01  Achlu01  Achlu02  Achma01  Achmi01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN

                            Achmi02    Achmi03  Achmo01  Achmo02  Achna01  \
SamplingOperations_code
S02000008_20170703        88.888889        NaN      NaN      NaN      NaN
S02000008_20200708        12.500000        NaN      NaN      NaN      NaN
S02000010_20070906              NaN        NaN      NaN      NaN      NaN
S02000010_20090721       135.000000        NaN      NaN      NaN      NaN
S02000010_20110723        15.075377        NaN      NaN      NaN      NaN
...                             ...        ...      ...      ...      ...
S06940940_20100708         9.132420        NaN      NaN      NaN      NaN
S06940940_20230623       375.000000  14.705882      NaN      NaN      NaN
S06960950_20160629        87.281796        NaN      NaN      NaN      NaN
S06960950_20180719       298.076923        NaN      NaN      NaN      NaN
S06970900_20150601       173.611111        NaN      NaN      NaN      NaN

                         Achna02  Achne01  Achni01  Achno01  Achob01  Achpa01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpe01  Achpe02  Achpf01  Achpl01  Achpo01  Achpr01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                         Achpr02  Achps01  Achps02  Achps03  Achps04  Achpu01  \
SamplingOperations_code
S02000008_20170703           NaN      NaN      NaN      NaN      NaN      NaN
S02000008_20200708           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20070906           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20090721           NaN      NaN      NaN      NaN      NaN      NaN
S02000010_20110723           NaN      NaN      NaN      NaN      NaN      NaN
...                          ...      ...      ...      ...      ...      ...
S06940940_20100708           NaN      NaN      NaN      NaN      NaN      NaN
S06940940_20230623           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20160629           NaN      NaN      NaN      NaN      NaN      NaN
S06960950_20180719           NaN      NaN      NaN      NaN      NaN      NaN
S06970900_20150601           NaN      NaN      NaN      NaN      NaN      NaN

                            Achpy01  Achre01  Achri01  Achro01  Achro02  \
SamplingOperations_code
S02000008_20170703              NaN      NaN      NaN      NaN      NaN
S02000008_20200708              NaN      NaN      NaN      NaN      NaN
S02000010_20070906              NaN      NaN      NaN      NaN      NaN
S02000010_20090721         7.500000      NaN      NaN      NaN      NaN
S02000010_20110723              NaN      NaN      NaN      NaN      NaN
...                             ...      ...      ...      ...      ...
S06940940_20100708              NaN      NaN      NaN      NaN      NaN
S06940940_20230623              NaN      NaN      NaN      NaN      NaN
S06960950_20160629       812.967581      NaN      NaN      NaN      NaN

Short answer: drop IBD* when fitting any imputer. Using the target to fill predictors creates leakage and over-optimistic CV; at inference the target is unknown so the imputer would use information you won’t have.

When you still want “best” fills for prediction, do this:

# For each region

In [10]:
import cleandf

In [11]:
# FastSISReducer: ultra-fast pre-imputation feature screener
# pip install numpy pandas scikit-learn
from __future__ import annotations
import re, numpy as np, pandas as pd
from dataclasses import dataclass
from typing import List, Optional, Tuple
from sklearn.base import BaseEstimator, TransformerMixin

# ---- column inference (same rules you used) ----
def _infer_columns(df: pd.DataFrame) -> Tuple[List[str], List[str], List[str], List[str], Optional[str]]:
    cols = df.columns.tolist()
    ibd_cols = [c for c in ["IBD","IBD_EQR","IBD_EQR_Status"] if c in cols]
    effort_col = "TotalAbundance_SamplingOperation" if "TotalAbundance_SamplingOperation" in cols else None
    status_cols = [c for c in cols if "Status" in c]
    chem_cols = [c for c in cols if c.startswith(("Mean90Days_","Mean180Days_","Mean1Y_")) or c.endswith("_XOMP")]
    group_cols = [c for c in ["HERlvl1Name","HERlvl1Code","CodeSite_SamplingOperations_x","CodeSite_SamplingOperations_y"] if c in cols]
    reserved = set(ibd_cols + status_cols + chem_cols + group_cols + ([effort_col] if effort_col else []))
    taxa_cols = [c for c in cols if c not in reserved and c and c[0].isalpha() and any(ch.isdigit() for ch in c)]
    if "Streamsize" in cols and "Streamsize" not in chem_cols:
        chem_cols.append("Streamsize")
    return taxa_cols, status_cols, chem_cols, group_cols, effort_col

# ---- fast helpers ----
def _spearman_on_pairs(x: pd.Series, y: pd.Series) -> float:
    # pairwise complete obs
    m = x.notna() & y.notna()
    if m.sum() < 25: 
        return 0.0
    xr = x[m].rank(method="average")
    yr = y[m].rank(method="average")
    return xr.corr(yr)

def _status_to_ord(s: pd.Series) -> pd.Series:
    return s.astype("object").map({"Bad":1,"Poor":2,"Moderate":3,"Good":4,"High":5}).fillna(0).astype(np.int16)

@dataclass
class SISConfig:
    # Hard filters
    max_missing: float = 0.98       # drop if >98% NaN
    min_n_pairs: int = 50           # need at least 50 (x,y) pairs
    min_presence_frac: float = 0.005 # drop taxa with <0.5% positives after struct zeros
    # Pooling
    pool_prefix_len: int = 3
    min_pool_size: int = 4
    min_pool_prev: float = 0.02
    # Ranking
    subsample_rows: int = 20000     # speed cap; set 0 for all rows
    top_k: int = 300                # final kept features
    corr_drop: float = 0.98         # drop redundant by |rho|>0.98 w.r.t. earlier-kept feature
    random_state: int = 42

class FastSISReducer(BaseEstimator, TransformerMixin):
    def __init__(self, cfg: SISConfig = SISConfig()):
        self.cfg = cfg

    def fit(self, X: pd.DataFrame, y: pd.Series):
        taxa_cols, status_cols, chem_cols, group_cols, effort_col = _infer_columns(X)
        self.group_cols_ = group_cols
        self.effort_col_ = effort_col

        # optional subsample for speed
        if self.cfg.subsample_rows and len(X) > self.cfg.subsample_rows:
            rng = np.random.RandomState(self.cfg.random_state)
            idx = rng.choice(len(X), size=self.cfg.subsample_rows, replace=False)
            Xs, ys = X.iloc[idx], y.iloc[idx]
        else:
            Xs, ys = X, y

        # structural zeros only to compute presence
        if effort_col and effort_col in Xs.columns:
            mask_zero_eff = pd.to_numeric(Xs[effort_col], errors="coerce").fillna(0) <= 0
        else:
            mask_zero_eff = pd.Series(False, index=Xs.index)

        X0 = Xs.copy()
        if mask_zero_eff.any():
            X0.loc[mask_zero_eff, taxa_cols] = 0.0

        # 1) Hard screens
        keep_taxa = []
        for c in taxa_cols:
            s = pd.to_numeric(X0[c], errors="coerce")
            if s.isna().mean() > self.cfg.max_missing:
                continue
            pres = (s.fillna(0) > 0).mean()
            if pres < self.cfg.min_presence_frac:
                continue
            keep_taxa.append(c)

        # Pool ultra-rare taxa by prefix to salvage signal cheaply
        rare_buckets = {}
        for c in set(taxa_cols) - set(keep_taxa):
            pfx = re.sub(r'[^A-Za-z].*$', '', c)[:self.cfg.pool_prefix_len] or "RARE"
            rare_buckets.setdefault(pfx, []).append(c)

        pool_cols = []
        for pfx, cols in rare_buckets.items():
            if len(cols) < self.cfg.min_pool_size:
                continue
            colname = f"POOL_{pfx}"
            X0[colname] = pd.to_numeric(X0[cols], errors="coerce").fillna(0).sum(axis=1)
            if (X0[colname] > 0).mean() >= self.cfg.min_pool_prev:
                pool_cols.append(colname)

        # Chemistry + statuses basic screen
        chem_keep = [c for c in chem_cols if X0[c].isna().mean() <= self.cfg.max_missing]
        # 2) Rank by fast Spearman with IBD on observed pairs
        cand = keep_taxa + pool_cols + chem_keep + status_cols
        ranks = []
        for c in cand:
            if c in status_cols:
                s = _status_to_ord(X0[c])
            else:
                s = pd.to_numeric(X0[c], errors="coerce")
            n_pairs = (s.notna() & ys.notna()).sum()
            if n_pairs < self.cfg.min_n_pairs:
                continue
            r = abs(_spearman_on_pairs(s, ys))
            # weight by sqrt(n_pairs/N) to prefer stable estimates
            w = np.sqrt(n_pairs / len(X0))
            ranks.append((c, r * w, r, n_pairs))
        if not ranks:
            # fallback: keep small safe core
            self.selected_ = chem_keep[: min(50, len(chem_keep))]
            self.pools_ = {pc: [] for pc in pool_cols}
            return self

        R = pd.DataFrame(ranks, columns=["col","score","rho","n"]).sort_values("score", ascending=False)

        # 3) Redundancy pruning (very cheap): greedy |rho|>corr_drop vs already kept
        selected = []
        corr_cache = {}
        for col in R["col"]:
            if len(selected) >= self.cfg.top_k:
                break
            s_col = X0[col] if col not in status_cols else _status_to_ord(X0[col])
            s_col = pd.to_numeric(s_col, errors="coerce")
            redundant = False
            for kept in selected:
                key = (kept, col)
                if key in corr_cache:
                    rkk = corr_cache[key]
                else:
                    a = pd.to_numeric(X0[kept] if kept not in status_cols else _status_to_ord(X0[kept]), errors="coerce")
                    m = a.notna() & s_col.notna()
                    if m.sum() < 25:
                        rkk = 0.0
                    else:
                        rkk = abs(a[m].rank().corr(s_col[m].rank()))
                    corr_cache[key] = rkk
                if rkk >= self.cfg.corr_drop:
                    redundant = True
                    break
            if not redundant:
                selected.append(col)

        self.selected_ = selected
        self.status_cols_ = status_cols
        self.pools_ = {pc: rare_buckets.get(pc.replace("POOL_",""), []) for pc in pool_cols}
        return self

    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        # materialize only what we kept + passthrough columns required later
        Z = X.copy()
        # structural zeros for pool building consistency
        taxa_cols, _, _, _, effort_col = _infer_columns(Z)
        if effort_col and effort_col in Z.columns:
            mask_zero_eff = pd.to_numeric(Z[effort_col], errors="coerce").fillna(0) <= 0
            if mask_zero_eff.any():
                Z.loc[mask_zero_eff, taxa_cols] = 0.0
        # build pools
        for pc, cols in self.pools_.items():
            if pc in self.selected_ and cols:
                Z[pc] = pd.to_numeric(Z[cols], errors="coerce").fillna(0).sum(axis=1)
        keep = list(dict.fromkeys(self.selected_ + self.group_cols_ + ([self.effort_col_] if self.effort_col_ else [])))
        return Z.reindex(columns=[c for c in keep if c in Z.columns])

In [12]:
# For all regions 1, 2, ..., 22
regiondfs = {}
for region in range(1, 23):
    print(f"Region: {region}")
    regiondf = df[df['HERlvl1Code'] == region]

    cleanregion = cleandf.IWANTMYXCLEAN(regiondf, thresh_high_missing=.90)
    regiondfs[region] = cleanregion

Region: 1
Dropped exact duplicate columns: ['Achac01', 'Achal01', 'Achca01', 'Achch01', 'Achcl01', 'Achco01', 'Achco03', 'Achcy01', 'Achde01', 'Achde02', 'Achdi01', 'Achdi02', 'Achel01', 'Achen01', 'Achex03', 'Achfl01', 'Achfr01', 'Achgr01', 'Achgr02', 'Achha01', 'Achhe01', 'Achhi01', 'Achho01', 'Achho02', 'Achim01', 'Achim02', 'Achim03', 'Achin01', 'Achin02', 'Achjo01', 'Achko01', 'Achkr01', 'Achkr03', 'Achkr04', 'Achku01', 'Achla01', 'Achla05', 'Achle01', 'Achle02', 'Achli02', 'Achli04', 'Achlo01', 'Achlu01', 'Achlu02', 'Achmo01', 'Achmo02', 'Achna01', 'Achna02', 'Achni01', 'Achno01', 'Achpa01', 'Achpe01', 'Achpe02', 'Achpl01', 'Achpo01', 'Achpr01', 'Achpr02', 'Achps01', 'Achps02', 'Achps03', 'Achpu01', 'Achro01', 'Achro03', 'Achru02', 'Achsc01', 'Achse01', 'Achse02', 'Achsi01', 'Achst01', 'Achst02', 'Achst04', 'Achsu02', 'Achsu04', 'Achtu01', 'Achzi01', 'Actde01', 'Actno01', 'Actro01', 'Actse01', 'Actsp01', 'Actsu01', 'Actvu01', 'Adlaq01', 'Adlbr01', 'Adlmu01', 'Adlmu02', 'Adlpa01', 'Afrre01', 'Ampae01', 'Ampaf01', 'Ampal01', 'Ampbi01', 'Ampbu01', 'Ampco01', 'Ampcu01', 'Ampde01', 'Ampdi01', 'Ampdi02', 'Ampdu01', 'Ampei01', 'Ampex01', 'Ampfo01', 'Ampfo02', 'Amphe01', 'Amphi01', 'Ampli01', 'Ampme01', 'Ampmi01', 'Ampmi02', 'Ampne01', 'Ampne02', 'Amppa01', 'Amppo01', 'Amppo02', 'Amppr01', 'Ampps01', 'Ampri01', 'Ampst01', 'Ampst02', 'Ampsu01', 'Ampsu02', 'Ampsu03', 'Ampsu04', 'Amptu01', 'Ampve02', 'Ampvi01', 'Anaba01', 'Anemi01', 'Anetu01', 'Anoeu01', 'Anoga01', 'Anoin01', 'Anosp01', 'Aulal01', 'Aulbr01', 'Aulcr01', 'Aulcr02', 'Auldi01', 'Aulis01', 'Aulit01', 'Aulli01', 'Aulpa01', 'Aulps01', 'Aulps02', 'Aulsu02', 'Aulva01', 'Azpno01', 'Bacul01', 'Braca01', 'Brali01', 'Brapr01', 'Braps01', 'Breke01', 'Calae02', 'Calal01', 'Calau01', 'Calbi01', 'Calfa01', 'Calfo02', 'Calhy01', 'Calla01', 'Calla02', 'Calla03', 'Calle01', 'Calmi01', 'Calpa01', 'Calpu01', 'Calsc01', 'Caltr01', 'Calve01', 'Calwe01', 'Camcy01', 'Camhi01', 'Capcr01', 'Catad01', 'Cavpa01', 'Cenre01', 'Cergr01', 'Chaal01', 'Chabe01', 'Chafa01', 'Chamu01', 'Chare01', 'Charh01', 'Chasc01', 'Chath01', 'Clico01', 'Cliin01', 'Cocbr01', 'Cocca01', 'Coccl01', 'Cocco01', 'Cocde01', 'Cocdi02', 'Cocgr01', 'Cochu02', 'Cocin01', 'Cocla01', 'Cocle01', 'Cocme01', 'Cocne01', 'Cocps01', 'Cocre01', 'Cocro01', 'Cocsc01', 'Cocse01', 'Cocsu01', 'Conwe01', 'Cosco01', 'Cosla01', 'Cosla02', 'Craac01', 'Craac02', 'Craha01', 'Crari01', 'Crasv01', 'Cravi01', 'Crazi01', 'Creru01', 'Creth01', 'Ctepu01', 'Cycbo01', 'Cyccy01', 'Cycde01', 'Cycde02', 'Cycgl01', 'Cycir01', 'Cyckr01', 'Cycku01', 'Cycop01', 'Cycpl01', 'Cycpl02', 'Cycsc01', 'Cycst02', 'Cycst03', 'Cycst04', 'Cycsu01', 'Cycth01', 'Cylgr01', 'Cymal01', 'Cymal02', 'Cyman01', 'Cyman02', 'Cyman03', 'Cyman04', 'Cymap01', 'Cymas01', 'Cymbe01', 'Cymbi01', 'Cymbr01', 'Cymbu01', 'Cymci01', 'Cymcu01', 'Cymcy01', 'Cymdi01', 'Cymdo01', 'Cymeh01', 'Cymel02', 'Cymex03', 'Cymfr01', 'Cymga01', 'Cymhe01', 'Cymhe02', 'Cymhu01', 'Cymin01', 'Cymin02', 'Cymin03', 'Cymka01', 'Cymko01', 'Cymku01', 'Cymla02', 'Cymla03', 'Cymlu01', 'Cymma01', 'Cymme02', 'Cymna02', 'Cymob01', 'Cymob02', 'Cympa01', 'Cympl01', 'Cympr01', 'Cympr02', 'Cympr03', 'Cympu01', 'Cymrh01', 'Cymru01', 'Cymsi02', 'Cymsp01', 'Cymst01', 'Cymsu01', 'Cymsu02', 'Cymsu03', 'Cymsu04', 'Cymsu06', 'Cymsu08', 'Cymsu09', 'Cymtr01', 'Cymtu04', 'Cymvu01', 'Delap01', 'Delco01', 'Delde01', 'Delkr01', 'Delve01', 'Dener01', 'Denfr01', 'Denpa01', 'Dense01', 'Densu01', 'Densu02', 'Diade01', 'Diapy01', 'Diate02', 'Diavi01', 'Dicda01', 'Dimna01', 'Dipab01', 'Dipae01', 'Dipbo01', 'Dipbo02', 'Dipbu01', 'Dipca01', 'Dipde01', 'Dipfo01', 'Dipfo02', 'Diphi01', 'Dipmi01', 'Dipmo01', 'Dippa01', 'Dipps01', 'Dippu01', 'Dipst01', 'Dipsu01', 'Dipti01', 'Disin01', 'Disst01', 'Encae01', 'Encaf01', 'Encal01', 'Encau01', 'Encbl01', 'Encbo01', 'Encel01', 'Encfa01', 'Encfo02', 'Encge01', 'Encgr01', 'Enche01', 'Encho01', 'Enchu01', 'Encin01', 'Enckr01', 'Enckr02', 'Encla01', 'Encla02', 'Enclu01', 'Encme01', 'Encmi01', 'Encmi02', 'Encmu01', 'Encne02', 'Encne03', 'Encno01', 'Encob01', 'Encpa01', 'Encpe01', 'Encpr02', 'Encre01', 'Encre02', 'Encro01', 'Encro02', 'Encsp01', 'Encsu01', 'Encsu02', 'Encsy01', 'Encth01', 'Encva01', 'Entor01', 'Entpa01', 'Eolar01', 'Eolbe01', 'Eolch01', 'Eolcr01', 'Eolin01', 'Epifr01', 'Epiin01', 'Epiop01', 'Epipa01', 'Epire01', 'Epiru01', 'Epism01', 'Epitu01', 'Ethpu01', 'Eucau01', 'Eucdi01', 'Eunam01', 'Eunar02', 'Eunar04', 'Eunau01', 'Eunbe01', 'Eunbi01', 'Eunbi02', 'Eunbi03', 'Eunbi04', 'Eunbo02', 'Eunch01', 'Eunci01', 'Eunci02', 'Eunci03', 'Euncu01', 'Eunde01', 'Eundi01', 'Eundi02', 'Eundo01', 'Eunel01', 'Eunen01', 'Eunfa01', 'Eunfl01', 'Eunfo02', 'Eunge01', 'Eunge02', 'Eungi01', 'Eungl01', 'Eungl02', 'Eungr01', 'Eunin02', 'Eunis01', 'Eunkr01', 'Eunla01', 'Eunla02', 'Eunme01', 'Eunme02', 'Eunme03', 'Eunmi01', 'Eunmi02', 'Eunmo01', 'Eunmu01', 'Eunmy01', 'Eunna01', 'Eunne01', 'Eunne02', 'Eunny01', 'Eunoc01', 'Eunor01', 'Eunpa01', 'Eunpa03', 'Eunpa04', 'Eunpa05', 'Eunpe01', 'Eunpe02', 'Eunpe03', 'Eunpr01', 'Eunps01', 'Eunps02', 'Eunrh01', 'Eunse01', 'Eunse02', 'Eunse03', 'Eunsi01', 'Eunso01', 'Eunst01', 'Eunsu01', 'Eunsu03', 'Eunsu04', 'Eunta01', 'Eunte02', 'Eunth01', 'Euntr01', 'Euntr02', 'Eunur01', 'Eunva01', 'Eunva02', 'Eunyb01', 'Exipu01', 'Falcl01', 'Falcr01', 'Falom01', 'Falpy01', 'Fraac01', 'Fraac02', 'Fraac03', 'Fraae01', 'Fraal01', 'Fraaq01', 'Fraat01', 'Frabi02', 'Frabi04', 'Frabi05', 'Frabo01', 'Fraca05', 'Fraco02', 'Fradi01', 'Frael01', 'Fraex01', 'Frafo01', 'Frafr01', 'Frage01', 'Frage02', 'Fragr02', 'Frahe01', 'Frain01', 'Frain02', 'Fraka01', 'Frala01', 'Frala03', 'Fralo01', 'Frame01', 'Frami01', 'Frami02', 'Frami04', 'Framu01', 'Frane01', 'Frane03', 'Frani01', 'Fraos01', 'Frapa02', 'Frape02', 'Frape03', 'Frapo01', 'Fraps01', 'Fraps02', 'Frapu01', 'Fraro01', 'Frasi01', 'Frasu01', 'Frasu02', 'Frate02', 'Frate03', 'Fratr01', 'Fraul01', 'Fraul02', 'Fraun01', 'Fruam01', 'Fruap01', 'Fruau01', 'Frucr01', 'Frucu01', 'Frudi01', 'Frukr01', 'Fruli01', 'Frune01', 'Frune02', 'Frupa01', 'Frupu01', 'Fruqu01', 'Frure01', 'Frurh01', 'Frusa01', 'Fruse01', 'Frusp01', 'Fruvi01', 'Fruwe01', 'Geige01', 'Geihi01', 'Geita01', 'Geren01', 'Glotr01', 'Gomae01', 'Gomam01', 'Goman01', 'Goman06', 'Gombo01', 'Gombo03', 'Gombr01', 'Gomca03', 'Gomca05', 'Gomcl03', 'Gomco01', 'Gomco02', 'Gomco03', 'Gomco05', 'Gomcu01', 'Gomcu03', 'Gomda01', 'Gomde01', 'Gomde02', 'Gomdi01', 'Gomdr01', 'Gomen01', 'Gomer01', 'Gomer02', 'Gomex02', 'Gomfo01', 'Gomfr01', 'Gomgr02', 'Gomgr03', 'Gomgr04', 'Gomha01', 'Gomhe01', 'Gomho01', 'Gomin01', 'Gomin02', 'Gomin04', 'Gomin05', 'Gomja01', 'Gomje01', 'Gomko01', 'Gomla02', 'Gomla03', 'Gomla06', 'Gomli01', 'Gomli02', 'Gomli03', 'Gomlo01', 'Gomlo02', 'Gomma01', 'Gomme01', 'Gomna01', 'Gomoa01', 'Gomob01', 'Gomob02', 'Gomoh01', 'Gomol01', 'Gomop01', 'Gompa02', 'Gompa03', 'Gompa04', 'Gompa05', 'Gompe01', 'Gompl01', 'Gompr01', 'Gompr02', 'Gomps01', 'Gomps02', 'Gomps03', 'Gompu01', 'Gompy01', 'Gomsa01', 'Gomsi01', 'Gomsp01', 'Gomsp02', 'Gomst01', 'Gomst02', 'Gomsu01', 'Gomsu02', 'Gomsu04', 'Gomsu05', 'Gomta01', 'Gomta02', 'Gomtr01', 'Gomtu01', 'Gomtu02', 'Gomun01', 'Gomva01', 'Gomva03', 'Gomva04', 'Gomva05', 'Gomve01', 'Gomvi01', 'Gomze01', 'Grama01', 'Grase01', 'Grusi01', 'Gyrli01', 'Gyrob01', 'Gyrsc01', 'Halac01', 'Halap01', 'Halbu01', 'Halcy01', 'Halho01', 'Halno01', 'Halol01', 'Halpe01', 'Halsu01', 'Halva01', 'Hanab01', 'Hanau01', 'Hanca01', 'Hanco01', 'Hanmo01', 'Hanps01', 'Hanre01', 'Hasdu01', 'Himfa01', 'Himso01', 'Hipar01', 'Hipca01', 'Hipco01', 'Hipco02', 'Hipge01', 'Hipne01', 'Hipol01', 'Hipps01', 'Hippu01', 'Hipru01', 'Hipsu01', 'Hombu01', 'Homca01', 'Homsu01', 'Humbr01', 'Humga01', 'Humsc01', 'Hydtr01', 'Hydwh01', 'Karam01', 'Karob01', 'Karpl01', 'Kobja01', 'Kobpa01', 'Kobps01', 'Kobsa01', 'Kobsu01', 'Kolsu01', 'Kurae01', 'Lacla01', 'Lemex01', 'Lemhu01', 'Lepmi01', 'Linau01', 'Linba01', 'Linbo01', 'Linco01', 'Linco02', 'Linfo01', 'Linpr01', 'Linte01', 'Lutac01', 'Lutco01', 'Lutfr01', 'Luthl01', 'Lutin01', 'Lutna01', 'Lutpe01', 'Lutpe02', 'Lutps01', 'Lutro01', 'Lutsa01', 'Lutsi01', 'Lutsp01', 'Lutve01', 'Masac01', 'Masba01', 'Masel01', 'Masex01', 'Masex02', 'Masin01', 'Masla01', 'Maspa01', 'Massm01', 'Masva01', 'Mayas01', 'Mayca01', 'Mayca02', 'Mayin01', 'Melcr01', 'Meldi01', 'Meldi02', 'Melgr01', 'Melit01', 'Melja01', 'Mello01', 'Melly01', 'Melmo01', 'Melmu01', 'Melny01', 'Melsc01', 'Melsp01', 'Melte02', 'Mesme01', 'Mickr01', 'Micpa01', 'Minch01', 'Muegi01', 'Muesp01', 'Nankr01', 'Nantr01', 'Navab01', 'Navab02', 'Navab03', 'Navac01', 'Navac03', 'Navad01', 'Navad02', 'Navag01', 'Navag02', 'Naval01', 'Naval02', 'Navam01', 'Navam02', 'Navam03', 'Navam04', 'Navam06', 'Navam07', 'Navan01', 'Navan03', 'Navan04', 'Navan06', 'Navap01', 'Navap02', 'Navaq02', 'Navar01', 'Navar03', 'Navat01', 'Navau01', 'Navba01', 'Navba02', 'Navbi01', 'Navbi02', 'Navbi03', 'Navbj01', 'Navbo01', 'Navbr01', 'Navbr03', 'Navbr04', 'Navbr05', 'Navbr06', 'Navbr07', 'Navbu01', 'Navbu02', 'Navca01', 'Navca02', 'Navca03', 'Navca04', 'Navca05', 'Navca06', 'Navca09', 'Navce01', 'Navch01', 'Navci02', 'Navcl01', 'Navcl02', 'Navcl03', 'Navcl04', 'Navco02', 'Navco03', 'Navco04', 'Navco06', 'Navcr01', 'Navcr02', 'Navcr03', 'Navcr06', 'Navcr08', 'Navcu01', 'Navcu02', 'Navde01', 'Navde02', 'Navde04', 'Navde05', 'Navde06', 'Navde07', 'Navdi01', 'Navdi02', 'Navdi05', 'Navdi07', 'Navdi08', 'Navdi09', 'Navdi10', 'Navdo01', 'Naveg01', 'Navei01', 'Navel01', 'Navel02', 'Navel03', 'Navev01', 'Navex03', 'Navfa01', 'Navfa02', 'Navfe01', 'Navfl01', 'Navfo01', 'Navfo02', 'Navfo03', 'Navfr01', 'Navga01', 'Navge01', 'Navge03', 'Navgi01', 'Navgl01', 'Navgo01', 'Navgr02', 'Navgr03', 'Navha01', 'Navha03', 'Navha04', 'Navha05', 'Navha06', 'Navha07', 'Navha08', 'Navhe01', 'Navhe03', 'Navho01', 'Navhu01', 'Navhu02', 'Navim01', 'Navin01', 'Navin02', 'Navin03', 'Navin04', 'Navin05', 'Navin07', 'Navin08', 'Navin09', 'Navin10', 'Navir01', 'Navir02', 'Navja02', 'Navja03', 'Navju01', 'Navko01', 'Navko02', 'Navkr01', 'Navku01', 'Navla02', 'Navla03', 'Navla05', 'Navla06', 'Navla07', 'Navle03', 'Navle04', 'Navle06', 'Navli01', 'Navli02', 'Navli03', 'Navlo01', 'Navlo02', 'Navlo03', 'Navlu01', 'Navlu03', 'Navma01', 'Navma02', 'Navma03', 'Navma04', 'Navma05', 'Navme01', 'Navme02', 'Navme03', 'Navme05', 'Navmi01', 'Navmi03', 'Navmi04', 'Navmi05', 'Navmi06', 'Navmi07', 'Navmi08', 'Navmo01', 'Navmo02', 'Navmo03', 'Navmo04', 'Navmo06', 'Navmo07', 'Navmo10', 'Navmu01', 'Navmu03', 'Navmu04', 'Navmu05', 'Navmu07', 'Navna01', 'Navne01', 'Navne02', 'Navni01', 'Navno01', 'Navnu01', 'Navny01', 'Navob01', 'Navob02', 'Navob03', 'Navob05', 'Navop01', 'Navop02', 'Navpa02', 'Navpa03', 'Navpa04', 'Navpa05', 'Navpa06', 'Navpa07', 'Navpe01', 'Navpe02', 'Navpe03', 'Navpe04', 'Navph01', 'Navph02', 'Navpl01', 'Navpr02', 'Navpr03', 'Navps03', 'Navps04', 'Navps05', 'Navps07', 'Navps09', 'Navps11', 'Navps12', 'Navpu01', 'Navpu02', 'Navpu03', 'Navpu04', 'Navpy01', 'Navqu01', 'Navra03', 'Navra04', 'Navre01', 'Navre02', 'Navre03', 'Navre05', 'Navre06', 'Navrh03', 'Navri01', 'Navri02', 'Navri03', 'Navri04', 'Navro01', 'Navro02', 'Navru01', 'Navsa01', 'Navsa02', 'Navsa04', 'Navsa05', 'Navsa07', 'Navsc01', 'Navsc02', 'Navsc03', 'Navsc05', 'Navsc06', 'Navsc07', 'Navsc08', 'Navse01', 'Navse03', 'Navse04', 'Navse06', 'Navse07', 'Navsi02', 'Navsi03', 'Navsl01', 'Navsm01', 'Navsp01', 'Navsp03', 'Navst01', 'Navst02', 'Navst03', 'Navst06', 'Navst07', 'Navsu01', 'Navsu02', 'Navsu04', 'Navsu06', 'Navsu10', 'Navsu11', 'Navsu12', 'Navsu13', 'Navsu14', 'Navsu16', 'Navsu17', 'Navsu18', 'Navsu19', 'Navsu20', 'Navsy02', 'Navta01', 'Navta02', 'Navte02', 'Navte03', 'Navth01', 'Navto01', 'Navtr01', 'Navtr03', 'Navtr04', 'Navtu01', 'Navtu02', 'Navul01', 'Navum01', 'Navum02', 'Navun01', 'Navva01', 'Navva02', 'Navva04', 'Navva05', 'Navva06', 'Navve01', 'Navve02', 'Navve05', 'Navve07', 'Navvi04', 'Navwe01', 'Navwi01', 'Navwi02', 'Navwi04', 'Navwy01', 'Navza01', 'Navze01', 'Neiaf01', 'Neiam01', 'Neiap01', 'Neibi01', 'Neibi02', 'Neibi03', 'Neibi04', 'Neica01', 'Neico01', 'Neicu01', 'Neide01', 'Neiel01', 'Neihe01', 'Neihu01', 'Neiin01', 'Neiir01', 'Neilo01', 'Neipe01', 'Neipr01', 'Neips01', 'Neise01', 'Neisu01', 'Neite01', 'Neive01', 'Neoco01', 'Nitac01', 'Nitac02', 'Nitac03', 'Nitac06', 'Nitae01', 'Nitae02', 'Nitag01', 'Nital01', 'Nital03', 'Nitam02', 'Nitam03', 'Nitam04', 'Nitan01', 'Nitau01', 'Nitau02', 'Nitba01', 'Nitba02', 'Nitba03', 'Nitba04', 'Nitbe02', 'Nitbi01', 'Nitbr01', 'Nitbr02', 'Nitbr03', 'Nitca01', 'Nitca02', 'Nitco01', 'Nitco03', 'Nitco04', 'Nitco06', 'Nitcu01', 'Nitcu02', 'Nitcu03', 'Nitde01', 'Nitde02', 'Nitde04', 'Nitde05', 'Nitde06', 'Nitdi01', 'Nitdi02', 'Nitdi03', 'Nitdi05', 'Nitdi06', 'Nitdu01', 'Nitep01', 'Nitet01', 'Niteu01', 'Nitfa01', 'Nitfi01', 'Nitfi02', 'Nitfl01', 'Nitfl02', 'Nitfo02', 'Nitfr01', 'Nitfu01', 'Nitge01', 'Nitgi01', 'Nitgo01', 'Nitgr01', 'Nitgr03', 'Nitha01', 'Nitho01', 'Nitho02', 'Nithu01', 'Nitin01', 'Nitin03', 'Nitin04', 'Nitin05', 'Nitju01', 'Nitla01', 'Nitla02', 'Nitla04', 'Nitla05', 'Nitla06', 'Nitla07', 'Nitle01', 'Nitle02', 'Nitli01', 'Nitli02', 'Nitli04', 'Nitma01', 'Nitmi02', 'Nitmi03', 'Nitmi04', 'Nitmo01', 'Nitmo02', 'Nitna01', 'Nitov01', 'Nitpa04', 'Nitpa05', 'Nitpa06', 'Nitpa07', 'Nitpa08', 'Nitpa09', 'Nitpe01', 'Nitpe02', 'Nitpe04', 'Nitpi01', 'Nitpl01', 'Nitps02', 'Nitpu01', 'Nitra01', 'Nitre02', 'Nitre03', 'Nitre04', 'Nitrh01', 'Nitro01', 'Nitro02', 'Nitro03', 'Nitsc01', 'Nitse01', 'Nitsi02', 'Nitsi03', 'Nitsp01', 'Nitst01', 'Nitsu02', 'Nitsu03', 'Nitsu04', 'Nitsu06', 'Nitsu07', 'Nitsu08', 'Nitsy01', 'Nitta01', 'Nitte01', 'Nitth01', 'Nitth02', 'Nittr02', 'Nittu01', 'Nitva01', 'Nitva02', 'Nitve01', 'Nitve02', 'Nitvi01', 'Nitvi02', 'Nitwu01', 'Nitzu01', 'Nupca01', 'Nupde01', 'Nupel01', 'Nupex01', 'Nupfe01', 'Nupim01', 'Nupim02', 'Nupma01', 'Nupne01', 'Nuppa01', 'Nuppa02', 'Nuppr01', 'Nuppr02', 'Nupru01', 'Nupsc01', 'Nupsi01', 'Nupsu01', 'Nuptr01', 'Nupvy01', 'Nupwe01', 'Odoau01', 'Odosp01', 'Opebu01', 'Opema01', 'Opemi01', 'Opepa01', 'Ortro01', 'Panps01', 'Panro01', 'Parde01', 'Parhe01', 'Parmi01', 'Parrh01', 'Parsu01', 'Perfi01', 'Perpe01', 'Pinac01', 'Pinac02', 'Pinac03', 'Pinac04', 'Pinam01', 'Pinan01', 'Pinan02', 'Pinan03', 'Pinap01', 'Pinbi01', 'Pinbr01', 'Pinbr02', 'Pinca01', 'Pincl01', 'Pinde01', 'Pindi01', 'Pindi02', 'Pindo01', 'Pindu01', 'Pinel01', 'Pinel02', 'Pinex01', 'Pinfa01', 'Pinfe01', 'Pinfr01', 'Pinfr02', 'Pingi01', 'Pingl01', 'Pingr01', 'Pingr02', 'Pinin02', 'Pinin03', 'Pinis01', 'Pinkn01', 'Pinkr01', 'Pinkr02', 'Pinku01', 'Pinla02', 'Pinle01', 'Pinlu01', 'Pinma01', 'Pinma02', 'Pinma03', 'Pinma05', 'Pinme01', 'Pinme02', 'Pinmi01', 'Pinmo01', 'Pinmo02', 'Pinmo03', 'Pinmu01', 'Pinna01', 'Pinne01', 'Pinno01', 'Pinno02', 'Pinpa01', 'Pinpa02', 'Pinpe01', 'Pinpe02', 'Pinpe04', 'Pinpe05', 'Pinpl01', 'Pinpo01', 'Pinpo02', 'Pinps01', 'Pinra01', 'Pinre01', 'Pinrh01', 'Pinrh02', 'Pinrh03', 'Pinru01', 'Pinru02', 'Pinsa01', 'Pinsa02', 'Pinsa03', 'Pinsc01', 'Pinsc02', 'Pinsc03', 'Pinsc04', 'Pinsi01', 'Pinsi02', 'Pinsi03', 'Pinsi04', 'Pinst01', 'Pinst02', 'Pinsu01', 'Pinsu02', 'Pinsu03', 'Pinsu04', 'Pinsu05', 'Pinsu06', 'Pinsu07', 'Pinsu08', 'Pinsu09', 'Pinsu10', 'Pinsu11', 'Pinte01', 'Pinth01', 'Pintr01', 'Pinvi01', 'Pinvi02', 'Plaab01', 'Plaam01', 'Plaat01', 'Plaau01', 'Plaba02', 'Plabi01', 'Plabr01', 'Placa01', 'Placl01', 'Placl02', 'Pladi01', 'Plaga01', 'Plaga02', 'Plaga03', 'Plaha01', 'Plaha02', 'Plahi01', 'Plain01', 'Plaki01', 'Plala01', 'Plalu01', 'Plama01', 'Plame01', 'Plami01', 'Plana01', 'Plaob01', 'Plapa02', 'Plape01', 'Plape02', 'Plapo01', 'Plaps01', 'Plapu01', 'Plaro01', 'Plaro02', 'Plaro05', 'Plasi01', 'Plast01', 'Plata01', 'Plats01', 'Plava01', 'Plava02', 'Plavi01', 'Plean01', 'Plebr01', 'Plede01', 'Pleku01', 'Plela01', 'Pleob01', 'Plepr01', 'Plesa01', 'Plesp01', 'Plewo01', 'Pretu01', 'Prohu01', 'Psaab01', 'Psaal01', 'Psabr01', 'Psabu01', 'Psaco01', 'Psafr01', 'Psapu01', 'Psasa01', 'Pse(a01', 'Psebi01', 'Psebo01', 'Pseca01', 'Pseco01', 'Psege01', 'Pseoc01', 'Pseop01', 'Psepa02', 'Psepo01', 'Psero01', 'Psesm01', 'Psevu01', 'Punbo01', 'Pungl01', 'Pyxco01', 'Rhaam01', 'Rhami01', 'Rhasu01', 'Rhipr01', 'Rhobr01', 'Rhogi01', 'Rhogi02', 'Rhote01', 'Rhova01', 'Scema01', 'Scemu01', 'Schbr01', 'Schcr01', 'Schex01', 'Schla01', 'Selab01', 'Selar01', 'Selar02', 'Selau01', 'Selba01', 'Selbl01', 'Selbo01', 'Selca01', 'Selch01', 'Selco01', 'Selda01', 'Seldi01', 'Selel01', 'Sella01', 'Sella02', 'Selpa01', 'Selps01', 'Selps02', 'Selps03', 'Selra01', 'Selre01', 'Selrh02', 'Selro01', 'Selru01', 'Selsc01', 'Selsu01', 'Selsu02', 'Selut01', 'Selve01', 'Semin01', 'Semro01', 'Skaoe01', 'Skape01', 'Skepe01', 'Skesu01', 'Spisp01', 'Staac01', 'Staac02', 'Staac03', 'Staac04', 'Staag01', 'Staal01', 'Staam01', 'Staam02', 'Staam03', 'Stabo01', 'Stabo02', 'Stabo03', 'Stabr01', 'Stach01', 'Staco01', 'Stacr01', 'Stadi01', 'Stadu01', 'Stadu02', 'Staex01', 'Stagr01', 'Stagr02', 'Stahe01', 'Stain01', 'Stain02', 'Stain03', 'Stakr02', 'Stala01', 'Stala02', 'Stala03', 'Stale01', 'Stale04', 'Stalo01', 'Stama01', 'Stami01', 'Stamu01', 'Stana01', 'Stane01', 'Staob01', 'Staol01', 'Staol02', 'Staph01', 'Stapl01', 'Stapo01', 'Stapr01', 'Stapu01', 'Stare01', 'Stare02', 'Staro01', 'Stasa01', 'Stase01', 'Stasi01', 'Stasm01', 'Stasp01', 'Stast01', 'Stasu01', 'Stasv01', 'State01', 'Staun01', 'Stave01', 'Stawi01', 'Steal01', 'Stebr01', 'Steco01', 'Stede01', 'Stedu01', 'Steme01', 'Stemi01', 'Stena01', 'Stene01', 'Stero01', 'Steve01', 'Surac01', 'Sural01', 'Suram01', 'Surbi01', 'Surbi02', 'Surbi03', 'Surbo01', 'Surbr02', 'Surca01', 'Surch01', 'Surcr01', 'Surde01', 'Surel01', 'Surhe01', 'Surhi01', 'Surli01', 'Surma01', 'Surna01', 'Surol01', 'Surov01', 'Surpa01', 'Surre01', 'Surro02', 'Surst01', 'Surst02', 'Sursu01', 'Sursu02', 'Surte01', 'Surun01', 'Surve01', 'Survi01', 'Synac01', 'Synaf01', 'Synam01', 'Synam02', 'Synba01', 'Synbe01', 'Synca01', 'Syncr01', 'Synda01', 'Synde02', 'Synfa01', 'Synfa02', 'Synfl01', 'Synla01', 'Synma01', 'Synmo01', 'Synmo02', 'Synna01', 'Synpa01', 'Synpl01', 'Synva01', 'Tabfe01', 'Tabin01', 'Tabta01', 'Tetgl01', 'Tetla01', 'Thaba01', 'Thabr01', 'Thadu01', 'Thage01', 'Thani01', 'Thaps01', 'Thavi01', 'Traac01', 'Traas01', 'Traau01', 'Trire01', 'Trybr01', 'Tryca01', 'Tryco01', 'Tryde01', 'Trygr01', 'Tryku01', 'Tryle01', 'Trysu01', 'Tryvi01', 'Tscmi01', 'Ulngr01', 'Witan01', 'Withu01', 'Witps01', 'Witsu01', 'Witsy01', 'Zygsu01', 'Mean180Days_1166', 'Mean180Days_1592', 'Mean180Days_1593', 'Mean180Days_1644', 'Mean180Days_1647', 'Mean180Days_1648', 'Mean180Days_1770', 'Mean180Days_2923', 'Mean180Days_6249', 'Mean180Days_6600', 'Mean1Y_1166', 'Mean1Y_1644', 'Mean1Y_1647', 'Mean1Y_1648', 'Mean1Y_1770', 'Mean1Y_2923', 'Mean1Y_6249', 'Mean1Y_6600', 'Mean90Days_1166', 'Mean90Days_1173', 'Mean90Days_1207', 'Mean90Days_1592', 'Mean90Days_1593', 'Mean90Days_1644', 'Mean90Days_1647', 'Mean90Days_1648', 'Mean90Days_1723', 'Mean90Days_1770', 'Mean90Days_1777', 'Mean90Days_1811', 'Mean90Days_2539', 'Mean90Days_2923', 'Mean90Days_3336', 'Mean90Days_5275', 'Mean90Days_5986', 'Mean90Days_6249', 'Mean90Days_6598', 'Mean90Days_6600']

In [13]:
# df = regiondfs[1]
# df

In [14]:
# X = df.drop(columns=[c for c in ["IBD","IBD_EQR","IBD_EQR_Status"] if c in df])
# y = df["IBD"].astype(float)

# reducer.fit(X, y)
# X_small = reducer.transform(X)

In [15]:
# reducer = FastSISReducer(SISConfig(
#     subsample_rows=20000,  # set 0 to use all
#     top_k=250,             # adjust budget
#     max_missing=0.98,
#     min_n_pairs=50,
#     corr_drop=0.98
# ))

In [16]:
# ============================================================
# MultiRegionBoostedClassifier (accuracy-focused) + selectable models
# + persistence + auto-visuals + per-region reports
# Patched: classifier wrapper (_estimator_type, decision_function) + safe calibration
# ============================================================

from typing import Dict, Any, List, Optional, Tuple
import warnings
import os, json, re
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import joblib

from scipy.stats import loguniform, randint, uniform
from sklearn.base import BaseEstimator, ClassifierMixin, clone, is_classifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, cross_val_predict
from sklearn.metrics import (
    accuracy_score, f1_score, confusion_matrix, classification_report,
    roc_curve, roc_auc_score, precision_recall_curve, average_precision_score
)
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.ensemble import HistGradientBoostingClassifier

# ---------- utilities ----------

def _slug(s) -> str:
    s = str(s).strip().lower()
    s = re.sub(r"[^\w\-]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "region"

def _normalize_model_names(models: Optional[List[str]]) -> Optional[set]:
    if not models:
        return None
    alias = {
        "HGB": "HGB",
        "HISTGRADIENTBOOSTING": "HGB",
        "LIGHTGBM": "LIGHTGBM", "LGBM": "LIGHTGBM",
        "XGBOOST": "XGBOOST", "XGB": "XGBOOST",
        "CATBOOST": "CATBOOST", "CAT": "CATBOOST",
    }
    out = set()
    for m in models:
        key = str(m).upper().replace(" ", "")
        out.add(alias.get(key, key))
    return out

def _resolve_col_case(df: pd.DataFrame, name: str) -> str:
    if name in df.columns:
        return name
    low = name.lower()
    for c in df.columns:
        if c.lower() == low:
            return c
    raise KeyError(f"Column '{name}' not found (case-insensitive).")

def _build_preprocessor(X: pd.DataFrame) -> Tuple[ColumnTransformer, List[str], List[str]]:
    num_cols = X.select_dtypes(include=["number"]).columns.tolist()
    cat_cols = [c for c in X.columns if c not in num_cols]
    pre = ColumnTransformer(
        transformers=[
            ("num", Pipeline([("imp", SimpleImputer(strategy="median"))]), num_cols),
            ("cat", Pipeline([
                ("imp", SimpleImputer(strategy="constant", fill_value="None")),
                ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]), cat_cols),
        ],
        remainder="drop",
    )
    return pre, num_cols, cat_cols

def _feature_names_from_pre(pre: ColumnTransformer, num_cols: List[str], cat_cols: List[str]) -> List[str]:
    names: List[str] = []
    if num_cols:
        names.extend(num_cols)
    if cat_cols and "cat" in pre.named_transformers_:
        ohe = pre.named_transformers_["cat"].named_steps["ohe"]
        names.extend(ohe.get_feature_names_out(cat_cols).tolist())
    return names

def _cv_for(y: pd.Series, max_splits: int = 5) -> StratifiedKFold:
    min_class = int(y.value_counts(dropna=False).min())
    n_splits = max(2, min(max_splits, max(1, min_class)))
    return StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

def _can_kfold(y: pd.Series, cv: Optional[StratifiedKFold]) -> bool:
    if cv is None:
        return False
    return int(y.value_counts().min()) >= cv.get_n_splits()

# ---------- wrapper: contiguous labels per fit + fixed-width predict_proba ----------

class ContiguousLabelWrapper(BaseEstimator, ClassifierMixin):
    """
    Remap TRAIN labels to {0..k-1}. Predictions map back to global-encoded ints.
    If global_n_classes_ is set, predict_proba returns fixed K columns in global-id order.
    """
    _estimator_type = "classifier"  # ensure sklearn treats this as a classifier

    def __init__(self, estimator: BaseEstimator, global_n_classes_: Optional[int] = None):
        self.estimator = estimator
        self.global_n_classes_ = global_n_classes_
        self.estimator_ = None
        self.classes_ = None  # global int labels present in this fit

    def get_params(self, deep=True):
        params = {"estimator": self.estimator, "global_n_classes_": self.global_n_classes_}
        if deep and hasattr(self.estimator, "get_params"):
            for k, v in self.estimator.get_params(deep=True).items():
                params[f"estimator__{k}"] = v
        return params

    def set_params(self, **params):
        est_params = {}
        for k, v in list(params.items()):
            if k == "estimator":
                self.estimator = v
            elif k == "global_n_classes_":
                self.global_n_classes_ = v
            elif k.startswith("estimator__"):
                est_params[k.split("__", 1)[1]] = v
            else:
                setattr(self, k, v)
            params.pop(k, None)
        if est_params and hasattr(self.estimator, "set_params"):
            self.estimator.set_params(**est_params)
        return self

    def fit(self, X, y, **fit_params):
        y = np.asarray(y)
        uniq = np.unique(y)                 # global-encoded ints present in TRAIN
        to_local = {g: i for i, g in enumerate(uniq)}
        y_local = np.array([to_local[val] for val in y], dtype=int)
        est = clone(self.estimator)
        est.fit(X, y_local, **fit_params)
        self.estimator_ = est
        self.classes_ = uniq
        return self

    def predict(self, X):
        y_local = self.estimator_.predict(X)
        return self.classes_[np.asarray(y_local, dtype=int)]

    def predict_proba(self, X):
        if not hasattr(self.estimator_, "predict_proba"):
            raise AttributeError("Underlying estimator has no predict_proba.")
        P_local = self.estimator_.predict_proba(X)  # (n, k_local)
        if self.global_n_classes_ is None:
            return P_local
        n, k_glob = P_local.shape[0], int(self.global_n_classes_)
        P = np.zeros((n, k_glob), dtype=float)
        for j, g in enumerate(self.classes_):
            if 0 <= int(g) < k_glob:
                P[:, int(g)] = P_local[:, j]
        row_sums = P.sum(axis=1, keepdims=True)
        fix = (row_sums == 0).flatten()
        if np.any(fix):
            P[fix, :] = 1.0 / k_glob
        else:
            P /= np.where(row_sums == 0, 1, row_sums)
        return P

    def decision_function(self, X):
        if hasattr(self.estimator_, "decision_function"):
            return self.estimator_.decision_function(X)
        raise AttributeError("Underlying estimator has no decision_function.")

# ---------- main class (accuracy-focused boosted selection) ----------

class MultiRegionBoostedClassifier:
    """
    Per-region selection among boosted trees with label remapping and visuals:
      - HGB, LightGBM*, XGBoost*, CatBoost* (*if installed)
    Select models via constructor or per-call `models=[...]` (e.g., ["HGB","XGBoost"]).
    """

    def __init__(self, xcleans: Dict[Any, pd.DataFrame], random_state: int = 42,
                 verbose: bool = True, models: Optional[List[str]] = None):
        self.xcleans = xcleans
        self.random_state = random_state
        self.verbose = verbose
        self.results: Dict[Any, Dict[str, Any]] = {}
        self.target_column: Optional[str] = None
        self.models_allowed = _normalize_model_names(models)  # None => all available

    def _candidate_spaces(self, n_classes: Optional[int], allowed: Optional[set]) -> Dict[str, Tuple[Any, dict]]:
        rng = self.random_state
        spaces: Dict[str, Tuple[Any, dict]] = {}

        def ok(tag: str) -> bool:
            return allowed is None or tag in allowed

        # HGB
        if ok("HGB"):
            hgb = ContiguousLabelWrapper(
                HistGradientBoostingClassifier(random_state=rng),
                global_n_classes_=n_classes
            )
            hgb_grid = {
                "model__estimator__learning_rate": loguniform(1e-2, 3e-1),
                "model__estimator__max_depth": randint(2, 13),
                "model__estimator__max_leaf_nodes": randint(16, 257),
                "model__estimator__min_samples_leaf": randint(10, 201),
                "model__estimator__l2_regularization": loguniform(1e-4, 10.0),
                "model__estimator__max_bins": randint(64, 257),
            }
            spaces["HGB"] = (hgb, hgb_grid)

        # LightGBM
        if ok("LIGHTGBM"):
            try:
                from lightgbm import LGBMClassifier
                lgb = ContiguousLabelWrapper(
                    LGBMClassifier(objective="multiclass", random_state=rng, n_jobs=-1, verbose=-1),
                    global_n_classes_=n_classes
                )
                lgb_grid = {
                    "model__estimator__n_estimators": randint(300, 1201),
                    "model__estimator__learning_rate": loguniform(1e-2, 3e-1),
                    "model__estimator__num_leaves": randint(16, 257),
                    "model__estimator__max_depth": randint(-1, 16),
                    "model__estimator__min_child_samples": randint(5, 201),
                    "model__estimator__subsample": uniform(0.5, 0.5),
                    "model__estimator__colsample_bytree": uniform(0.5, 0.5),
                    "model__estimator__reg_alpha": loguniform(1e-6, 10.0),
                    "model__estimator__reg_lambda": loguniform(1e-6, 10.0),
                }
                spaces["LightGBM"] = (lgb, lgb_grid)
            except Exception:
                if self.verbose: print("[warn] LightGBM not available; skipping.")

        # XGBoost
        if ok("XGBOOST"):
            try:
                from xgboost import XGBClassifier
                xgb = ContiguousLabelWrapper(
                    XGBClassifier(objective="multi:softprob", random_state=rng, tree_method="hist",
                                  eval_metric="mlogloss", n_jobs=-1, verbosity=0),
                    global_n_classes_=n_classes
                )
                xgb_grid = {
                    "model__estimator__n_estimators": randint(300, 1201),
                    "model__estimator__learning_rate": loguniform(1e-2, 3e-1),
                    "model__estimator__max_depth": randint(3, 13),
                    "model__estimator__min_child_weight": loguniform(1e-1, 10.0),
                    "model__estimator__subsample": uniform(0.5, 0.5),
                    "model__estimator__colsample_bytree": uniform(0.5, 0.5),
                    "model__estimator__gamma": loguniform(1e-6, 10.0),
                    "model__estimator__reg_alpha": loguniform(1e-6, 10.0),
                    "model__estimator__reg_lambda": loguniform(1e-6, 10.0),
                }
                spaces["XGBoost"] = (xgb, xgb_grid)
            except Exception:
                if self.verbose: print("[warn] XGBoost not available; skipping.")

        # CatBoost
        if ok("CATBOOST"):
            try:
                from catboost import CatBoostClassifier
                cb = ContiguousLabelWrapper(
                    CatBoostClassifier(loss_function="MultiClass", random_seed=rng,
                                       verbose=False, allow_writing_files=False, thread_count=-1),
                    global_n_classes_=n_classes
                )
                cb_grid = {
                    "model__estimator__iterations": randint(300, 1201),
                    "model__estimator__learning_rate": loguniform(1e-2, 3e-1),
                    "model__estimator__depth": randint(4, 11),
                    "model__estimator__l2_leaf_reg": loguniform(1e-3, 30.0),
                    "model__estimator__bagging_temperature": loguniform(1e-2, 10.0),
                }
                spaces["CatBoost"] = (cb, cb_grid)
            except Exception:
                if self.verbose: print("[warn] CatBoost not available; skipping.")

        return spaces

    def process_missing_class(
        self,
        target_column: str = "IBD_EQR_Status",
        max_splits: int = 5,
        n_iter_per_model: int = 25,
        scoring: str = "accuracy",
        calibrate: bool = True,
        prob_method: str = "predict_proba",
        models: Optional[List[str]] = None,
    ):
        self.results.clear()
        self.target_column = target_column

        for key, Xclean in self.xcleans.items():
            try:
                y_col = _resolve_col_case(Xclean, target_column)
            except KeyError:
                if self.verbose: print(f"[skip {key}] missing target '{target_column}'"); continue
            if len(Xclean) < 5:
                if self.verbose: print(f"[skip {key}] too few rows: {len(Xclean)}"); continue

            y = Xclean[y_col]
            leak = {y_col, "IBD", "IBD_EQR", "IBD_EQR_Status", "IBD_EQR_STATUS"}
            X = Xclean.drop(columns=[c for c in leak if c in Xclean.columns], errors="ignore")

            mask_tr = y.notna()
            mask_te = ~mask_tr
            if mask_tr.sum() == 0:
                if self.verbose: print(f"[skip {key}] no labeled rows"); continue

            le = LabelEncoder()
            y_tr = y.loc[mask_tr]
            y_tr_enc = pd.Series(le.fit_transform(y_tr), index=y_tr.index)
            K = len(le.classes_)

            pre, num_cols, cat_cols = _build_preprocessor(X)
            cv = _cv_for(y_tr, max_splits=max_splits)

            allowed = _normalize_model_names(models) or self.models_allowed
            candidates = self._candidate_spaces(n_classes=K, allowed=allowed)
            if not candidates:
                raise RuntimeError("No boosted candidates available with the given 'models' setting.")

            best = {"name": None, "estimator": None, "cv_score": -np.inf, "cv_results_": None}
            for name, (estimator, grid) in candidates.items():
                pipe = Pipeline([("pre", pre), ("model", estimator)])
                search = RandomizedSearchCV(
                    estimator=pipe,
                    param_distributions=grid,
                    n_iter=n_iter_per_model,
                    scoring=scoring,
                    cv=cv,
                    refit=True,
                    n_jobs=-1,
                    verbose=0,
                    random_state=self.random_state,
                    error_score=np.nan,
                )
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    search.fit(X.loc[mask_tr], y_tr_enc)

                mean_score = np.nanmax(search.cv_results_["mean_test_score"])
                if self.verbose:
                    print(f"[{key}] {name}: best {scoring}={mean_score:.3f}")
                if np.isfinite(mean_score) and mean_score > best["cv_score"]:
                    best.update({"name": name, "estimator": search.best_estimator_, "cv_score": float(mean_score),
                                 "cv_results_": search.cv_results_})

            if best["estimator"] is None:
                if self.verbose: print(f"[skip {key}] no model selected")
                continue

            best_pipe: Pipeline = best["estimator"]

            # OOF diagnostics
            have_proba = False
            oof_proba = None
            if _can_kfold(y_tr, cv):
                try:
                    oof_pred_enc = cross_val_predict(best_pipe, X.loc[mask_tr], y_tr_enc, cv=cv, method="predict", n_jobs=-1)
                except Exception:
                    oof_pred_enc = cross_val_predict(best_pipe, X.loc[mask_tr], y_tr_enc, cv=cv, method="predict", n_jobs=-1)
                try:
                    oof_proba = cross_val_predict(best_pipe, X.loc[mask_tr], y_tr_enc, cv=cv, method="predict_proba", n_jobs=-1)
                    have_proba = True
                except Exception:
                    have_proba = False
                oof_pred = pd.Series(le.inverse_transform(oof_pred_enc.astype(int)), index=y_tr.index)
                oof_acc = accuracy_score(y_tr, oof_pred)
                oof_f1_macro = f1_score(y_tr, oof_pred, average="macro")
                cm = confusion_matrix(y_tr, oof_pred, labels=le.classes_)
            else:
                if self.verbose:
                    print(f"[{key}] skip OOF: min_class={int(y_tr.value_counts().min())} < folds={cv.get_n_splits()}")
                best_pipe.fit(X.loc[mask_tr], y_tr_enc)
                oof_pred_enc = best_pipe.predict(X.loc[mask_tr])
                oof_pred = pd.Series(le.inverse_transform(oof_pred_enc.astype(int)), index=y_tr.index)
                if hasattr(best_pipe, "predict_proba"):
                    try:
                        oof_proba = best_pipe.predict_proba(X.loc[mask_tr])
                        have_proba = True
                    except Exception:
                        have_proba = False
                oof_acc = accuracy_score(y_tr, oof_pred)
                oof_f1_macro = f1_score(y_tr, oof_pred, average="macro")
                cm = confusion_matrix(y_tr, oof_pred, labels=le.classes_)

            cm_df = pd.DataFrame(cm, index=[f"true_{c}" for c in le.classes_],
                                 columns=[f"pred_{c}" for c in le.classes_])

            # Refit on all labeled rows
            best_pipe.fit(X.loc[mask_tr], y_tr_enc)

            # Calibration (safe)
            calibrated_pipe = best_pipe
            if calibrate and _can_kfold(y_tr, cv):
                base = best_pipe
                final_est = base.named_steps["model"]
                if is_classifier(final_est) and (hasattr(final_est, "predict_proba") or hasattr(final_est, "decision_function")):
                    calib = CalibratedClassifierCV(final_est, cv=cv, method="isotonic")
                    calibrated_pipe = Pipeline([("pre", base.named_steps["pre"]), ("model", calib)])
                    calibrated_pipe.fit(X.loc[mask_tr], y_tr_enc)
                else:
                    if self.verbose: print(f"[{key}] skip calibration: estimator lacks proba/decision_function")
            else:
                if calibrate and self.verbose:
                    print(f"[{key}] skip calibration: min_class={int(y_tr.value_counts().min())} < folds={cv.get_n_splits()}")

            # Predict missing rows
            if mask_te.any():
                X_te = X.loc[mask_te]
                yhat_enc = calibrated_pipe.predict(X_te)
                yhat_te = pd.Series(le.inverse_transform(yhat_enc.astype(int)), index=X_te.index, name="yhat_te")

                proba_te = pd.DataFrame(index=X_te.index)
                if hasattr(calibrated_pipe, "predict_proba"):
                    P = calibrated_pipe.predict_proba(X_te)
                    inner = calibrated_pipe.named_steps["model"]
                    classes_enc = getattr(inner, "classes_", None)
                    if classes_enc is None and hasattr(inner, "base_estimator"):
                        classes_enc = getattr(inner.base_estimator, "classes_", None)
                    if classes_enc is None:
                        try:
                            classes_enc = inner.estimators_[0].classes_
                        except Exception:
                            classes_enc = np.arange(P.shape[1])
                    classes = le.inverse_transform(np.array(classes_enc, dtype=int))
                    proba_te = pd.DataFrame(P, index=X_te.index, columns=[f"proba_{c}" for c in classes])
            else:
                yhat_te = pd.Series(dtype=object, name="yhat_te")
                proba_te = pd.DataFrame()

            # Feature importances (if available)
            final_est = best_pipe.named_steps["model"]
            pre_fitted = best_pipe.named_steps["pre"]
            feat_names = _feature_names_from_pre(pre_fitted, num_cols, cat_cols)
            fi = pd.Series(dtype=float)
            try:
                est_inner = getattr(final_est, "estimator_", None)
                if est_inner is None and hasattr(final_est, "estimator"):
                    est_inner = final_est.estimator
                if est_inner is not None and hasattr(est_inner, "feature_importances_"):
                    fi = pd.Series(est_inner.feature_importances_, index=feat_names).sort_values(ascending=False)
            except Exception:
                pass

            # Filled target
            y_filled = y.copy()
            if mask_te.any():
                y_filled.loc[mask_te] = yhat_te.values

            # Store
            res = {
                "best_name": best["name"],
                "best_cv_score_acc": float(best["cv_score"]),
                "oof_acc": oof_acc,
                "oof_f1_macro": oof_f1_macro,
                "oof_confusion": cm_df,
                "classes_": le.classes_,
                "label_encoder": le,
                "model": calibrated_pipe,
                "uncalibrated_model": best_pipe,
                "n_train": int(mask_tr.sum()),
                "n_infer": int(mask_te.sum()),
                "y_tr": y_tr,
                "y_tr_enc": y_tr_enc,
                "oof_pred": pd.Series(oof_pred, index=y_tr.index, name="oof_pred"),
                "oof_proba": (oof_proba if have_proba else None),
                "proba_available": bool(have_proba),
                "yhat_te": yhat_te,
                "proba_te": proba_te,
                "y_filled": y_filled,
                "feature_importances": fi,
                "cv_results_": best.get("cv_results_", None),
            }
            # Back-compat aliases
            res["best_cv_score_bal_acc"] = res["best_cv_score_acc"]
            res["oof_bal_acc"] = res["oof_acc"]

            self.results[key] = res

            if self.verbose:
                print(f"[done {key}] best={best['name']}  OOF_acc={oof_acc:.3f}  "
                      f"OOF_f1_macro={oof_f1_macro:.3f}  infer={int(mask_te.sum())}")

    # ---- convenience ----

    def infer_table(self, key: Any) -> pd.DataFrame:
        r = self.results[key]
        idx = self.xcleans[key].index
        out = pd.DataFrame(index=idx)
        out["y_true"] = r["y_tr"]
        out["oof_pred"] = r["oof_pred"]
        out["yhat_te"] = r["yhat_te"]
        out["y_filled"] = r["y_filled"]
        out = out.join(r["proba_te"], how="left")
        return out

    def all_inferred(self) -> pd.DataFrame:
        frames = []
        for k in self.results:
            df = self.infer_table(k).reset_index().rename(columns={"index": "row_id"})
            df.insert(0, "region", k)
            frames.append(df)
        return pd.concat(frames, ignore_index=True)

    def filled_dataframe(self, key: Any) -> pd.DataFrame:
        if self.target_column is None:
            raise RuntimeError("Run process_missing_class first.")
        df = self.xcleans[key].copy()
        col = _resolve_col_case(df, self.target_column)
        df[col] = self.results[key]["y_filled"]
        return df

    def top_features(self, key: Any, k: int = 20) -> pd.DataFrame:
        fi = self.results[key]["feature_importances"]
        if fi.empty:
            raise ValueError("Feature importances unavailable for the selected model.")
        return fi.head(k).reset_index().rename(columns={"index": "feature", 0: "importance"})

    def print_report(self, key: Any):
        r = self.results[key]
        y_tr = r["y_tr"]
        y_pred = r["oof_pred"].reindex(y_tr.index)
        print(classification_report(y_tr, y_pred, digits=3))
        print("OOF confusion matrix:")
        print(r["oof_confusion"])

    def plot_oof_confusion(self, key: Any, savepath: Optional[str] = None, normalize: Optional[str] = None):
        cm = self.results[key]["oof_confusion"].copy()
        if normalize == "row":
            cm = cm.div(cm.sum(axis=1).replace(0, 1), axis=0)
            title = f"OOF confusion (row-norm) — region {key}"
        elif normalize == "col":
            cm = cm.div(cm.sum(axis=0).replace(0, 1), axis=1)
            title = f"OOF confusion (col-norm) — region {key}"
        else:
            title = f"OOF confusion — region {key}"
        plt.figure(figsize=(5, 4))
        plt.imshow(cm.values, interpolation="nearest")
        plt.xticks(range(len(cm.columns)), cm.columns, rotation=45, ha="right")
        plt.yticks(range(len(cm.index)), cm.index)
        plt.title(title)
        plt.colorbar()
        plt.tight_layout()
        if savepath:
            Path(savepath).parent.mkdir(parents=True, exist_ok=True)
            plt.savefig(savepath, dpi=150)
            plt.close()
        else:
            plt.show()

    def predict_new(self, key: Any, X_new: pd.DataFrame) -> np.ndarray:
        return self.results[key]["model"].predict(X_new)

    def predict_labels_new(self, key: Any, X_new: pd.DataFrame) -> np.ndarray:
        enc = self.results[key]["model"].predict(X_new)
        le: LabelEncoder = self.results[key]["label_encoder"]
        return le.inverse_transform(enc.astype(int))

    def predict_proba_new(self, key: Any, X_new: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
        mdl = self.results[key]["model"]
        if not hasattr(mdl, "predict_proba"):
            raise AttributeError("Model does not support predict_proba.")
        P = mdl.predict_proba(X_new)
        inner = mdl.named_steps["model"]
        classes_enc = getattr(inner, "classes_", None)
        if classes_enc is None:
            try:
                classes_enc = inner.estimators_[0].classes_
            except Exception:
                classes_enc = np.arange(P.shape[1])
        le: LabelEncoder = self.results[key]["label_encoder"]
        classes = le.inverse_transform(np.array(classes_enc, dtype=int))
        return P, classes

    # ---------- visuals helpers ----------

    @staticmethod
    def _savefig(path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        plt.tight_layout()
        plt.savefig(path, dpi=150)
        plt.close()

    def _export_visuals(self, key: Any, r: Dict[str, Any], viz_dir: Path, top_k_classes: int = 6, top_k_feats: int = 20):
        viz_dir.mkdir(parents=True, exist_ok=True)
        # 1) Confusion matrix (counts)
        cm = r["oof_confusion"]
        plt.figure(figsize=(6, 5))
        plt.imshow(cm.values, interpolation="nearest")
        plt.xticks(range(len(cm.columns)), cm.columns, rotation=45, ha="right")
        plt.yticks(range(len(cm.index)), cm.index)
        plt.title(f"OOF Confusion — {key}")
        plt.colorbar()
        self._savefig(viz_dir / "confusion_counts.png")

        # 1b) Confusion matrix (row-normalized)
        cm_norm = cm.div(cm.sum(axis=1).replace(0, 1), axis=0)
        plt.figure(figsize=(6, 5))
        plt.imshow(cm_norm.values, interpolation="nearest")
        plt.xticks(range(len(cm_norm.columns)), cm_norm.columns, rotation=45, ha="right")
        plt.yticks(range(len(cm_norm.index)), cm_norm.index)
        plt.title(f"OOF Confusion (row-normalized) — {key}")
        plt.colorbar()
        self._savefig(viz_dir / "confusion_row_norm.png")

        # 2) Classification report table -> CSV and F1 bar
        y_tr = r["y_tr"]
        y_pred = r["oof_pred"].reindex(y_tr.index)
        rep = classification_report(y_tr, y_pred, output_dict=True, zero_division=0)
        pd.DataFrame(rep).to_csv(viz_dir / "classification_report.csv", index=True)
        cls = [c for c in rep.keys() if c not in {"accuracy", "macro avg", "weighted avg"}]
        f1_vals = [rep[c]["f1-score"] for c in cls]
        plt.figure(figsize=(max(6, 0.4*len(cls)), 3.6))
        ax = plt.gca()
        ax.yaxis.set_major_locator(MaxNLocator(integer=True))
        plt.bar(cls, f1_vals)
        plt.xticks(rotation=45, ha="right")
        plt.ylabel("F1-score")
        plt.title(f"Per-class F1 — {key}")
        self._savefig(viz_dir / "per_class_f1.png")

        # 3) ROC and PR (if probabilities available)
        if r.get("proba_available", False) and r["oof_proba"] is not None:
            P = np.asarray(r["oof_proba"])
            classes = r["classes_"]
            y_bin = label_binarize(y_tr, classes=classes)
            if P.shape[1] == len(classes) and y_bin.shape[0] == P.shape[0]:
                try:
                    auc_macro = roc_auc_score(y_bin, P, average="macro", multi_class="ovr")
                except Exception:
                    auc_macro = np.nan
                try:
                    ap_scores = [average_precision_score(y_bin[:, j], P[:, j]) for j in range(P.shape[1])]
                    ap_macro = float(np.nanmean(ap_scores))
                except Exception:
                    ap_macro = np.nan
                with open(viz_dir / "prob_metrics.json", "w", encoding="utf-8") as f:
                    json.dump({"roc_auc_macro_ovr": auc_macro, "avg_precision_macro": ap_macro}, f, indent=2)

                support = y_tr.value_counts().reindex(classes, fill_value=0)
                top_idx = np.argsort(-support.values)[:min(top_k_classes, len(classes))]

                plt.figure(figsize=(6, 5))
                for j in top_idx:
                    fpr, tpr, _ = roc_curve(y_bin[:, j], P[:, j])
                    plt.plot(fpr, tpr, label=f"ROC {classes[j]}")
                plt.plot([0, 1], [0, 1], linestyle="--")
                plt.xlabel("FPR"); plt.ylabel("TPR")
                plt.title(f"ROC OVR (top-{len(top_idx)}) — {key}")
                plt.legend(fontsize=8)
                self._savefig(viz_dir / "roc_ovr_topk.png")

                plt.figure(figsize=(6, 5))
                for j in top_idx:
                    pr, rc, _ = precision_recall_curve(y_bin[:, j], P[:, j])
                    plt.plot(rc, pr, label=f"PR {classes[j]}")
                plt.xlabel("Recall"); plt.ylabel("Precision")
                plt.title(f"PR OVR (top-{len(top_idx)}) — {key}")
                plt.legend(fontsize=8)
                self._savefig(viz_dir / "pr_ovr_topk.png")

                plt.figure(figsize=(6, 5))
                for j in top_idx:
                    prob_true, prob_pred = calibration_curve(y_bin[:, j], P[:, j], n_bins=10, strategy="uniform")
                    plt.plot(prob_pred, prob_true, marker="o", label=f"Cal {classes[j]}")
                plt.plot([0, 1], [0, 1], linestyle="--")
                plt.xlabel("Predicted probability"); plt.ylabel("Observed frequency")
                plt.title(f"Reliability (top-{len(top_idx)}) — {key}")
                plt.legend(fontsize=8)
                self._savefig(viz_dir / "calibration_topk.png")

        # 4) Feature importances
        fi = r["feature_importances"]
        if isinstance(fi, pd.Series) and not fi.empty:
            k = min(top_k_feats, len(fi))
            plt.figure(figsize=(8, max(3.5, 0.25*k)))
            fi.head(k)[::-1].plot(kind="barh")
            plt.xlabel("Importance")
            plt.title(f"Top-{k} feature importances — {key}")
            self._savefig(viz_dir / "feature_importances_topk.png")

        # 5) CV score trace
        cvres = r.get("cv_results_", None)
        if cvres is not None:
            dfcv = pd.DataFrame(cvres)
            dfcv.to_csv(viz_dir / "cv_results.csv", index=False)
            if "mean_test_score" in dfcv:
                plt.figure(figsize=(6, 4))
                plt.plot(np.arange(len(dfcv["mean_test_score"])), dfcv["mean_test_score"], marker="o", linestyle="-")
                plt.xlabel("Candidate #"); plt.ylabel("mean_test_score")
                plt.title(f"RandomizedSearch scores — {key}")
                self._savefig(viz_dir / "cv_scores.png")

        # 6) Save compact metrics JSON
        metrics = {
            "oof_acc": float(r["oof_acc"]),
            "oof_f1_macro": float(r["oof_f1_macro"]),
            "n_train": int(r["n_train"]),
            "n_infer": int(r["n_infer"]),
        }
        with open(viz_dir / "metrics_summary.json", "w", encoding="utf-8") as f:
            json.dump(metrics, f, indent=2)

    # ---------- persistence ----------

    def save_all(self, outdir: str = "models", compress: int = 3, make_figs: bool = True,
                 figs_folder_suffix: str = "_viz", top_k_classes: int = 6, top_k_feats: int = 20) -> pd.DataFrame:
        Path(outdir).mkdir(parents=True, exist_ok=True)
        rows = []
        for key, r in self.results.items():
            best_name = (r["best_name"] or "model").lower()
            base = Path(outdir) / f"best_{best_name}_{_slug(key)}"

            joblib.dump(r["model"], f"{base}.joblib", compress=compress)
            joblib.dump(r["uncalibrated_model"], f"{base}_uncal.joblib", compress=compress)
            joblib.dump(r["label_encoder"], f"{base}_label_encoder.joblib", compress=compress)

            scores = {
                "best_cv_score_acc": r.get("best_cv_score_acc", r.get("best_cv_score_bal_acc")),
                "oof_acc": r.get("oof_acc", r.get("oof_bal_acc")),
                "oof_f1_macro": r["oof_f1_macro"],
            }
            meta = {
                "region": str(key),
                "best_name": r["best_name"],
                "paths": {
                    "calibrated": f"{base}.joblib",
                    "uncalibrated": f"{base}_uncal.joblib",
                    "label_encoder": f"{base}_label_encoder.joblib",
                    "meta": f"{base}_meta.json",
                },
                "scores": scores,
                "classes": list(map(str, r["classes_"])),
                "n_train": r["n_train"],
                "n_infer": r["n_infer"],
                "saved_at": datetime.now().isoformat(timespec="seconds"),
                "target_column": self.target_column,
            }
            with open(f"{base}_meta.json", "w", encoding="utf-8") as f:
                json.dump(meta, f, indent=2, ensure_ascii=False)

            if make_figs:
                viz_dir = Path(str(base) + figs_folder_suffix)
                try:
                    self._export_visuals(key, r, viz_dir=viz_dir, top_k_classes=top_k_classes, top_k_feats=top_k_feats)
                except Exception as e:
                    if self.verbose:
                        print(f"[warn] visuals for {key} failed: {e}")

            rows.append({
                "region": key,
                "best_name": r["best_name"],
                "calibrated_path": f"{base}.joblib",
                "encoder_path": f"{base}_label_encoder.joblib",
                "meta_path": f"{base}_meta.json",
                "viz_dir": (str(Path(str(base) + figs_folder_suffix)) if make_figs else None),
                "oof_acc": scores["oof_acc"],
                "oof_f1_macro": scores["oof_f1_macro"],
            })
        return pd.DataFrame(rows)

    @staticmethod
    def load_bundle(basepath: str):
        pipe = joblib.load(basepath + ".joblib")
        le = joblib.load(basepath + "_label_encoder.joblib")
        with open(basepath + "_meta.json", "r", encoding="utf-8") as f:
            meta = json.load(f)
        return pipe, le, meta

    # ---------- report helpers ----------

    def save_oof_report(self, key: Any, outdir: str = "models",
                        figs_folder_suffix: str = "_viz",
                        top_k_classes: int = 6, top_k_feats: int = 20) -> str:
        if key not in self.results:
            raise KeyError(f"Unknown region key: {key}")
        r = self.results[key]
        best_name = (r["best_name"] or "model").lower()
        base = Path(outdir) / f"best_{best_name}_{_slug(key)}"
        viz_dir = Path(str(base) + figs_folder_suffix)
        viz_dir.mkdir(parents=True, exist_ok=True)

        self._export_visuals(key, r, viz_dir=viz_dir,
                             top_k_classes=top_k_classes, top_k_feats=top_k_feats)

        r["oof_confusion"].to_csv(viz_dir / "confusion_matrix.csv")
        y_tr = r["y_tr"]
        y_pred = r["oof_pred"].reindex(y_tr.index)
        with open(viz_dir / "classification_report.txt", "w", encoding="utf-8") as f:
            f.write(classification_report(y_tr, y_pred, digits=4, zero_division=0))

        df = pd.DataFrame({"y_true": y_tr, "oof_pred": y_pred})
        if r.get("proba_available", False) and r["oof_proba"] is not None:
            P = np.asarray(r["oof_proba"])
            classes = r["classes_"]
            for j, c in enumerate(classes):
                df[f"proba_{c}"] = P[:, j]
        df.to_csv(viz_dir / "oof_predictions.csv", index=True)

        manifest = {
            "region": str(key),
            "best_name": r["best_name"],
            "report_dir": str(viz_dir),
            "n_train": int(r["n_train"]),
            "n_infer": int(r["n_infer"]),
            "oof_acc": float(r["oof_acc"]),
            "oof_f1_macro": float(r["oof_f1_macro"]),
        }
        with open(viz_dir / "manifest.json", "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)
        return str(viz_dir)

    def save_all_reports(self, outdir: str = "models",
                         figs_folder_suffix: str = "_viz",
                         top_k_classes: int = 6, top_k_feats: int = 20) -> pd.DataFrame:
        rows = []
        for key in self.results:
            path = self.save_oof_report(key, outdir=outdir,
                                        figs_folder_suffix=figs_folder_suffix,
                                        top_k_classes=top_k_classes, top_k_feats=top_k_feats)
            r = self.results[key]
            rows.append({
                "region": key,
                "best_name": r["best_name"],
                "report_dir": path,
                "oof_acc": float(r["oof_acc"]),
                "oof_f1_macro": float(r["oof_f1_macro"]),
            })
        return pd.DataFrame(rows)

# ----------------- usage example -----------------
# xcleans = {"region1": df1, "region2": df2, ...}
# # Skip CatBoost globally:
# auto = MultiRegionBoostedClassifier(xcleans, random_state=42, verbose=True,
#                                     models=["HGB", "LightGBM", "XGBoost"])
# auto.process_missing_class(scoring="accuracy", n_iter_per_model=25, max_splits=5, calibrate=True)
# manifest = auto.save_all(outdir="models", compress=3, make_figs=True)
# reports = auto.save_all_reports(outdir="models")
# print(manifest)
# print(reports)

In [17]:
auto = MultiRegionBoostedClassifier(regiondfs, random_state=42, verbose=True, models=["CatBoost"])
auto.process_missing_class(scoring="accuracy", n_iter_per_model=3, max_splits=5, calibrate=True)

[1] CatBoost: best accuracy=0.860
[1] skip OOF: min_class=1 < folds=2

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[1] skip calibration: min_class=1 < folds=2
[done 1] best=CatBoost  OOF_acc=1.000  OOF_f1_macro=1.000  infer=172

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[2] CatBoost: best accuracy=0.922
[2] skip OOF: min_class=1 < folds=2

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[2] skip calibration: min_class=1 < folds=2
[done 2] best=CatBoost  OOF_acc=1.000  OOF_f1_macro=1.000  infer=44

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[3] CatBoost: best accuracy=0.813

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[3] skip calibration: estimator lacks proba/decision_function
[done 3] best=CatBoost  OOF_acc=0.813  OOF_f1_macro=0.741  infer=566

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[4] CatBoost: best accuracy=0.704

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[4] skip calibration: estimator lacks proba/decision_function
[done 4] best=CatBoost  OOF_acc=0.704  OOF_f1_macro=0.612  infer=102

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[5] CatBoost: best accuracy=0.860

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[5] skip calibration: estimator lacks proba/decision_function
[done 5] best=CatBoost  OOF_acc=0.860  OOF_f1_macro=0.749  infer=244

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[6] CatBoost: best accuracy=0.827

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[6] skip calibration: estimator lacks proba/decision_function
[done 6] best=CatBoost  OOF_acc=0.827  OOF_f1_macro=0.732  infer=236

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[7] CatBoost: best accuracy=0.886

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[7] skip calibration: estimator lacks proba/decision_function
[done 7] best=CatBoost  OOF_acc=0.886  OOF_f1_macro=0.715  infer=58

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[8] CatBoost: best accuracy=0.789
[8] skip OOF: min_class=1 < folds=2

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[8] skip calibration: min_class=1 < folds=2
[done 8] best=CatBoost  OOF_acc=1.000  OOF_f1_macro=1.000  infer=79

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[9] CatBoost: best accuracy=0.884

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[9] skip calibration: estimator lacks proba/decision_function

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[done 9] best=CatBoost  OOF_acc=0.884  OOF_f1_macro=0.631  infer=1118
[10] CatBoost: best accuracy=0.849

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[10] skip calibration: estimator lacks proba/decision_function
[done 10] best=CatBoost  OOF_acc=0.849  OOF_f1_macro=0.710  infer=537

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[11] CatBoost: best accuracy=0.836

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[11] skip calibration: estimator lacks proba/decision_function
[done 11] best=CatBoost  OOF_acc=0.836  OOF_f1_macro=0.604  infer=148

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[12] CatBoost: best accuracy=0.865

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[12] skip calibration: estimator lacks proba/decision_function
[done 12] best=CatBoost  OOF_acc=0.865  OOF_f1_macro=0.683  infer=489

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[13] CatBoost: best accuracy=0.787

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[13] skip calibration: estimator lacks proba/decision_function
[done 13] best=CatBoost  OOF_acc=0.787  OOF_f1_macro=0.663  infer=115

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[14] CatBoost: best accuracy=0.866

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[14] skip calibration: estimator lacks proba/decision_function
[done 14] best=CatBoost  OOF_acc=0.866  OOF_f1_macro=0.647  infer=826

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[15] CatBoost: best accuracy=0.811

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[15] skip calibration: estimator lacks proba/decision_function
[done 15] best=CatBoost  OOF_acc=0.811  OOF_f1_macro=0.648  infer=124

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[16] CatBoost: best accuracy=0.785

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[16] skip calibration: estimator lacks proba/decision_function
[done 16] best=CatBoost  OOF_acc=0.785  OOF_f1_macro=0.381  infer=48

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[17] CatBoost: best accuracy=0.782

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[17] skip calibration: estimator lacks proba/decision_function
[done 17] best=CatBoost  OOF_acc=0.782  OOF_f1_macro=0.575  infer=87

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[18] CatBoost: best accuracy=0.822

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[18] skip calibration: estimator lacks proba/decision_function
[done 18] best=CatBoost  OOF_acc=0.822  OOF_f1_macro=0.535  infer=187

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[19] CatBoost: best accuracy=0.830
[19] skip OOF: min_class=1 < folds=2

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[19] skip calibration: min_class=1 < folds=2
[done 19] best=CatBoost  OOF_acc=1.000  OOF_f1_macro=1.000  infer=60

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[20] CatBoost: best accuracy=0.761

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[20] skip calibration: estimator lacks proba/decision_function
[done 20] best=CatBoost  OOF_acc=0.761  OOF_f1_macro=0.684  infer=60

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[21] CatBoost: best accuracy=0.791

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[21] skip calibration: estimator lacks proba/decision_function
[done 21] best=CatBoost  OOF_acc=0.791  OOF_f1_macro=0.664  infer=331

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[22] CatBoost: best accuracy=0.675

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[22] skip calibration: estimator lacks proba/decision_function
[done 22] best=CatBoost  OOF_acc=0.675  OOF_f1_macro=0.504  infer=32

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\preprocessing\_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [18]:
manifest = auto.save_all(outdir="models", compress=3, make_figs=True)
manifest

,region,best_name,calibrated_path,encoder_path,meta_path,viz_dir,oof_acc,oof_f1_macro
0,1,CatBoost,models\best_catboost_1.joblib,models\best_catboost_1_label_encoder.joblib,models\best_catboost_1_meta.json,models\best_catboost_1_viz,1.000000,1.000000
1,2,CatBoost,models\best_catboost_2.joblib,models\best_catboost_2_label_encoder.joblib,models\best_catboost_2_meta.json,models\best_catboost_2_viz,1.000000,1.000000
2,3,CatBoost,models\best_catboost_3.joblib,models\best_catboost_3_label_encoder.joblib,models\best_catboost_3_meta.json,models\best_catboost_3_viz,0.813318,0.741343
3,4,CatBoost,models\best_catboost_4.joblib,models\best_catboost_4_label_encoder.joblib,models\best_catboost_4_meta.json,models\best_catboost_4_viz,0.704453,0.611561
4,5,CatBoost,models\best_catboost_5.joblib,models\best_catboost_5_label_encoder.joblib,models\best_catboost_5_meta.json,models\best_catboost_5_viz,0.859836,0.749431
5,6,CatBoost,models\best_catboost_6.joblib,models\best_catboost_6_label_encoder.joblib,models\best_catboost_6_meta.json,models\best_catboost_6_viz,0.827187,0.732432
6,7,CatBoost,models\best_catboost_7.joblib,models\best_catboost_7_label_encoder.joblib,models\best_catboost_7_meta.json,models\best_catboost_7_viz,0.886266,0.714921
7,8,CatBoost,models\best_catboost_8.joblib,models\best_catboost_8_label_encoder.joblib,models\best_catboost_8_meta.json,models\best_catboost_8_viz,1.000000,1.000000
8,9,CatBoost,models\best_catboost_9.joblib,models\best_catboost_9_label_encoder.joblib,models\best_catboost_9_meta.json,models\best_catboost_9_viz,0.883538,0.631213
9,10,CatBoost,models\best_catboost_10.joblib,models\best_catboost_10_label_encoder.joblib,models\best_catboost_10_meta.json,models\best_catboost_10_viz,0.848628,0.709646
10,11,CatBoost,models\best_catboost_11.joblib,models\best_catboost_11_label_encoder.joblib,models\best_catboost_11_meta.json,models\best_catboost_11_viz,0.836109,0.603738
11,12,CatBoost,models\best_catboost_12.joblib,models\best_catboost_12_label_encoder.joblib,models\best_catboost_12_meta.json,models\best_catboost_12_viz,0.864852,0.683393
12,13,CatBoost,models\best_catboost_13.joblib,models\best_catboost_13_label_encoder.joblib,models\best_catboost_13_meta.json,models\best_catboost_13_viz,0.787162,0.663124
13,14,CatBoost,models\best_catboost_14.joblib,models\best_catboost_14_label_encoder.joblib,models\best_catboost_14_meta.json,models\best_catboost_14_viz,0.865963,0.646812
14,15,CatBoost,models\best_catboost_15.joblib,models\best_catboost_15_label_encoder.joblib,models\best_catboost_15_meta.json,models\best_catboost_15_viz,0.810737,0.648396
15,16,CatBoost,models\best_catboost_16.joblib,models\best_catboost_16_label_encoder.joblib,models\best_catboost_16_meta.json,models\best_catboost_16_viz,0.785498,0.380761
16,17,CatBoost,models\best_catboost_17.joblib,models\best_catboost_17_label_encoder.joblib,models\best_catboost_17_meta.json,models\best_catboost_17_viz,0.782123,0.574958
17,18,CatBoost,models\best_catboost_18.joblib,models\best_catboost_18_label_encoder.joblib,models\best_catboost_18_meta.json,models\best_catboost_18_viz,0.821904,0.535216
18,19,CatBoost,models\best_catboost_19.joblib,models\best_catboost_19_label_encoder.joblib,models\best_catboost_19_meta.json,models\best_catboost_19_viz,1.000000,1.000000
19,20,CatBoost,models\best_catboost_20.joblib,models\best_catboost_20_label_encoder.joblib,models\best_catboost_20_meta.json,models\best_catboost_20_viz,0.761161,0.684471
20,21,CatBoost,models\best_catboost_21.joblib,models\best_catboost_21_label_encoder.joblib,models\best_catboost_21_meta.json,models\best_catboost_21_viz,0.791166,0.663903
21,22,CatBoost,models\best_catboost_22.joblib,models\best_catboost_22_label_encoder.joblib,models\best_catboost_22_meta.json,models\best_catboost_22_viz,0.675000,0.504341

In [19]:
# all regions
reports = auto.save_all_reports(outdir="models")
reports

    region best_name                   report_dir   oof_acc  oof_f1_macro
0        1  CatBoost   models\best_catboost_1_viz  1.000000      1.000000
1        2  CatBoost   models\best_catboost_2_viz  1.000000      1.000000
2        3  CatBoost   models\best_catboost_3_viz  0.813318      0.741343
3        4  CatBoost   models\best_catboost_4_viz  0.704453      0.611561
4        5  CatBoost   models\best_catboost_5_viz  0.859836      0.749431
5        6  CatBoost   models\best_catboost_6_viz  0.827187      0.732432
6        7  CatBoost   models\best_catboost_7_viz  0.886266      0.714921
7        8  CatBoost   models\best_catboost_8_viz  1.000000      1.000000
8        9  CatBoost   models\best_catboost_9_viz  0.883538      0.631213
9       10  CatBoost  models\best_catboost_10_viz  0.848628      0.709646
10      11  CatBoost  models\best_catboost_11_viz  0.836109      0.603738
11      12  CatBoost  models\best_catboost_12_viz  0.864852      0.683393
12      13  CatBoost  models\best_catboost_13_viz  0.787162      0.663124
13      14  CatBoost  models\best_catboost_14_viz  0.865963      0.646812
14      15  CatBoost  models\best_catboost_15_viz  0.810737      0.648396
15      16  CatBoost  models\best_catboost_16_viz  0.785498      0.380761
16      17  CatBoost  models\best_catboost_17_viz  0.782123      0.574958
17      18  CatBoost  models\best_catboost_18_viz  0.821904      0.535216
18      19  CatBoost  models\best_catboost_19_viz  1.000000      1.000000
19      20  CatBoost  models\best_catboost_20_viz  0.761161      0.684471
20      21  CatBoost  models\best_catboost_21_viz  0.791166      0.663903
21      22  CatBoost  models\best_catboost_22_viz  0.675000      0.504341

In [20]:
all_preds = auto.all_inferred()
all_preds.to_csv("all_regions_inferred.csv", index=False)

# reportes

In [21]:
for i in range(3, 23):
    print(f"\n Region {i} report:")
    auto.print_report(i)
    print("\n")

 Region 3 report:
              precision    recall  f1-score   support

         Bad      0.711     0.432     0.538        74
        Good      0.768     0.769     0.768      1249
        High      0.880     0.870     0.875      1180
    Moderate      0.815     0.875     0.844      1522
        Poor      0.756     0.620     0.681       405

    accuracy                          0.813      4430
   macro avg      0.786     0.713     0.741      4430
weighted avg      0.812     0.813     0.811      4430

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad             32          0          0              1         41
true_Good             0        961        133            155          0
true_High             0        148       1027              5          0
true_Moderate         1        142          7           1332         40
true_Poor            12          1          0            141        251



 Region 4 report:
              precision    recall  f1-score   support

         Bad      1.000     0.333     0.500         6
        Good      0.691     0.667     0.679       141
        High      0.773     0.786     0.780       117
    Moderate      0.690     0.817     0.748       180
        Poor      0.542     0.260     0.351        50

    accuracy                          0.704       494
   macro avg      0.739     0.573     0.612       494
weighted avg      0.699     0.704     0.693       494

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              2          0          0              3          1
true_Good             0         94         24             23          0
true_High             0         22         92              3          0
true_Moderate         0         20          3            147         10
true_Poor             0          0          0             37         13



 Region 5 report:
              precision    recall  f1-score   support

         Bad      0.900     0.450     0.600        20
        Good      0.775     0.628     0.694       401
        High      0.925     0.954     0.939       825
    Moderate      0.833     0.933     0.880       729
        Poor      0.761     0.543     0.634        94

    accuracy                          0.860      2069
   macro avg      0.839     0.702     0.749      2069
weighted avg      0.856     0.860     0.854      2069

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              9          0          0              2          9
true_Good             0        252         61             88          0
true_High             0         35        787              3          0
true_Moderate         1         38          3            680          7
true_Poor             0          0          0             43         51



 Region 6 report:
              precision    recall  f1-score   support

         Bad      1.000     0.353     0.522        17
        Good      0.819     0.845     0.832       690
        High      0.894     0.917     0.905       564
    Moderate      0.775     0.802     0.788       489
        Poor      0.750     0.522     0.615       138

    accuracy                          0.827      1898
   macro avg      0.848     0.688     0.732      1898
weighted avg      0.827     0.827     0.824      1898

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              6          0          0              0         11
true_Good             0        583         58             49          0
true_High             0         45        517              2          0
true_Moderate         0         82          2            392         13
true_Poor             0          2          1             63         72



 Region 7 report:
              precision    recall  f1-score   support

         Bad      1.000     0.667     0.800         6
        Good      0.560     0.538     0.549        52
        High      0.940     0.971     0.955       373
    Moderate      0.667     0.552     0.604        29
        Poor      1.000     0.500     0.667         6

    accuracy                          0.886       466
   macro avg      0.833     0.645     0.715       466
weighted avg      0.882     0.886     0.882       466

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              4          1          1              0          0
true_Good             0         28         18              6          0
true_High             0         11        362              0          0
true_Moderate         0         10          3             16          0
true_Poor             0          0          1              2          3



 Region 8 report:
              precision    recall  f1-score   support

         Bad      1.000     1.000     1.000         1
        Good      1.000     1.000     1.000        83
        High      1.000     1.000     1.000       324
    Moderate      1.000     1.000     1.000        52
        Poor      1.000     1.000     1.000         9

    accuracy                          1.000       469
   macro avg      1.000     1.000     1.000       469
weighted avg      1.000     1.000     1.000       469

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              1          0          0              0          0
true_Good             0         83          0              0          0
true_High             0          0        324              0          0
true_Moderate         0          0          0             52          0
true_Poor             0          0          0              0          9



 Region 9 report:
              precision    recall  f1-score   support

         Bad      0.000     0.000     0.000        14
        Good      0.899     0.948     0.923      5813
        High      0.882     0.784     0.830       731
    Moderate      0.846     0.798     0.821      2375
        Poor      0.814     0.453     0.582       203

    accuracy                          0.884      9136
   macro avg      0.688     0.597     0.631      9136
weighted avg      0.880     0.884     0.880      9136

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              0          0          0              4         10
true_Good             0       5512         69            232          0
true_High             0        157        573              1          0
true_Moderate         0        461          8           1895         11
true_Poor             0          2          0            109         92



 Region 10 report:
              precision    recall  f1-score   support

         Bad      0.667     0.211     0.320        19
        Good      0.849     0.894     0.871      1437
        High      0.919     0.885     0.902       714
    Moderate      0.819     0.828     0.824      1020
        Poor      0.738     0.553     0.632       199

    accuracy                          0.849      3389
   macro avg      0.798     0.674     0.710      3389
weighted avg      0.847     0.849     0.846      3389

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              4          1          0              0         14
true_Good             0       1285         52             99          1
true_High             0         79        632              3          0
true_Moderate         0        148          3            845         24
true_Poor             2          1          1             85        110



 Region 11 report:
              precision    recall  f1-score   support

        Good      0.821     0.912     0.864       612
        High      0.891     0.831     0.860       354
    Moderate      0.785     0.618     0.692       165
        Poor      0.000     0.000     0.000        10

    accuracy                          0.836      1141
   macro avg      0.624     0.590     0.604      1141
weighted avg      0.830     0.836     0.830      1141

OOF confusion matrix:
               pred_Good  pred_High  pred_Moderate  pred_Poor
true_Good            558         35             19          0
true_High             60        294              0          0
true_Moderate         61          1            102          1
true_Poor              1          0              9          0



 Region 12 report:
              precision    recall  f1-score   support

         Bad      0.500     0.125     0.200         8
        Good      0.846     0.817     0.831      1291
        High      0.910     0.842     0.874       442
    Moderate      0.869     0.938     0.902      2226
        Poor      0.835     0.480     0.609       221

    accuracy                          0.865      4188
   macro avg      0.792     0.640     0.683      4188
weighted avg      0.864     0.865     0.861      4188

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              1          0          0              0          7
true_Good             0       1055         32            203          1
true_High             0         68        372              1          1
true_Moderate         0        124          2           2088         12
true_Poor             1          0          3            111        106



 Region 13 report:
              precision    recall  f1-score   support

         Bad      0.750     0.500     0.600        12
        Good      0.674     0.395     0.498       152
        High      0.843     0.959     0.897       415
    Moderate      0.740     0.849     0.791       245
        Poor      0.711     0.422     0.529        64

    accuracy                          0.787       888
   macro avg      0.744     0.625     0.663       888
weighted avg      0.775     0.787     0.769       888

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              6          0          0              3          3
true_Good             0         60         59             32          1
true_High             0         11        398              6          0
true_Moderate         1         16         13            208          7
true_Poor             1          2          2             32         27



 Region 14 report:
              precision    recall  f1-score   support

         Bad      0.000     0.000     0.000        19
        Good      0.870     0.908     0.888      3283
        High      0.909     0.869     0.889      1052
    Moderate      0.846     0.856     0.851      2295
        Poor      0.802     0.487     0.606       267

    accuracy                          0.866      6916
   macro avg      0.686     0.624     0.647      6916
weighted avg      0.863     0.866     0.863      6916

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              0          1          0              6         12
true_Good             0       2980         86            217          0
true_High             0        131        914              7          0
true_Moderate         0        308          2           1965         20
true_Poor             0          5          3            129        130



 Region 15 report:
              precision    recall  f1-score   support

         Bad      1.000     0.192     0.323        26
        Good      0.621     0.415     0.498       130
        High      0.726     0.779     0.752        68
    Moderate      0.839     0.941     0.887       642
        Poor      0.818     0.751     0.783       233

    accuracy                          0.811      1099
   macro avg      0.801     0.616     0.648      1099
weighted avg      0.805     0.811     0.797      1099

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              5          0          0              1         20
true_Good             0         54         19             57          0
true_High             0         15         53              0          0
true_Moderate         0         18          1            604         19
true_Poor             0          0          0             58        175



 Region 16 report:
              precision    recall  f1-score   support

         Bad      0.000     0.000     0.000         2
        Good      0.531     0.327     0.405        52
        High      0.843     0.969     0.902       227
    Moderate      0.622     0.575     0.597        40
        Poor      0.000     0.000     0.000        10

    accuracy                          0.785       331
   macro avg      0.399     0.374     0.381       331
weighted avg      0.737     0.785     0.754       331

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              0          0          0              2          0
true_Good             0         17         31              4          0
true_High             0          6        220              0          1
true_Moderate         0          8          9             23          0
true_Poor             0          1          1              8          0



 Region 17 report:
              precision    recall  f1-score   support

         Bad      0.000     0.000     0.000        10
        Good      0.785     0.681     0.729       188
        High      0.750     0.522     0.615        23
    Moderate      0.784     0.910     0.842       390
        Poor      0.774     0.619     0.688       105

    accuracy                          0.782       716
   macro avg      0.619     0.546     0.575       716
weighted avg      0.771     0.782     0.771       716

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              0          0          0              0         10
true_Good             0        128          4             56          0
true_High             0          9         12              2          0
true_Moderate         0         26          0            355          9
true_Poor             0          0          0             40         65



 Region 18 report:
              precision    recall  f1-score   support

         Bad      0.000     0.000     0.000         5
        Good      0.831     0.733     0.779       296
        High      0.844     0.628     0.720        43
    Moderate      0.822     0.943     0.878       582
        Poor      0.625     0.196     0.299        51

    accuracy                          0.822       977
   macro avg      0.624     0.500     0.535       977
weighted avg      0.811     0.822     0.807       977

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              0          0          0              3          2
true_Good             0        217          5             74          0
true_High             0         15         27              1          0
true_Moderate         0         29          0            549          4
true_Poor             0          0          0             41         10



 Region 19 report:
              precision    recall  f1-score   support

        Good      1.000     1.000     1.000       121
        High      1.000     1.000     1.000       296
    Moderate      1.000     1.000     1.000        22
        Poor      1.000     1.000     1.000         1

    accuracy                          1.000       440
   macro avg      1.000     1.000     1.000       440
weighted avg      1.000     1.000     1.000       440

OOF confusion matrix:
               pred_Good  pred_High  pred_Moderate  pred_Poor
true_Good            121          0              0          0
true_High              0        296              0          0
true_Moderate          0          0             22          0
true_Poor              0          0              0          1



 Region 20 report:
              precision    recall  f1-score   support

        Good      0.714     0.654     0.683       130
        High      0.821     0.653     0.727        49
    Moderate      0.778     0.905     0.837       232
        Poor      0.700     0.378     0.491        37

    accuracy                          0.761       448
   macro avg      0.753     0.648     0.684       448
weighted avg      0.758     0.761     0.751       448

OOF confusion matrix:
               pred_Good  pred_High  pred_Moderate  pred_Poor
true_Good             85          7             38          0
true_High             17         32              0          0
true_Moderate         16          0            210          6
true_Poor              1          0             22         14



 Region 21 report:
              precision    recall  f1-score   support

         Bad      0.833     0.143     0.244        35
        Good      0.718     0.683     0.700       586
        High      0.854     0.831     0.842       498
    Moderate      0.805     0.903     0.851       971
        Poor      0.764     0.616     0.682       242

    accuracy                          0.791      2332
   macro avg      0.795     0.635     0.664      2332
weighted avg      0.790     0.791     0.785      2332

OOF confusion matrix:
               pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
true_Bad              5          0          0              0         30
true_Good             0        400         69            117          0
true_High             0         80        414              4          0
true_Moderate         0         76          2            877         16
true_Poor             1          1          0             91        149



 Region 22 report:
              precision    recall  f1-score   support

        Good      0.643     0.750     0.692        48
        High      0.784     0.763     0.773        38
    Moderate      0.593     0.516     0.552        31
        Poor      0.000     0.000     0.000         3

    accuracy                          0.675       120
   macro avg      0.505     0.507     0.504       120
weighted avg      0.658     0.675     0.664       120

OOF confusion matrix:
               pred_Good  pred_High  pred_Moderate  pred_Poor
true_Good             36          4              8          0
true_High              7         29              2          0
true_Moderate         11          4             16          0
true_Poor              2          0              1          0

c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\175199\.conda\envs\a\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# results

In [22]:
auto.results

{1: {'best_name': 'CatBoost',
  'best_cv_score_acc': 0.8598628280803355,
  'oof_acc': 1.0,
  'oof_f1_macro': 1.0,
  'oof_confusion':                pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
  true_Bad              1          0          0              0          0
  true_Good             0        232          0              0          0
  true_High             0          0        988              0          0
  true_Moderate         0          0          0             86          0
  true_Poor             0          0          0              0          6,
  'classes_': array(['Bad', 'Good', 'High', 'Moderate', 'Poor'], dtype=object),
  'label_encoder': LabelEncoder(),
  'model': Pipeline(steps=[('pre',
                   ColumnTransformer(transformers=[('num',
                                                    Pipeline(steps=[('imp',
                                                                     SimpleImputer(strategy='median'))]),
                                                    ['TotalAbundance_SamplingOperation',
                                                     'Achat02', 'Achde03',
                                                     'Achla02', 'Achli03',
                                                     'Achmi02', 'Achpy01',
                                                     'Achri01', 'Achsu01',
                                                     'Achth01', 'Amppe02',
                                                     'Coceu01', 'Cocli01',
                                                     'Cocpe01', 'Cocpl01',
                                                     'Cymmi01', 'Cymsi01',
                                                     'Cymve01', 'Dente01',
                                                     'Diaeh01', 'Di...
                                                     'SuspendedMatter_Status90D',
                                                     'OrganicMicropollutants_Status1Y',
                                                     'OrganicMicropollutants_Status180D',
                                                     'OrganicMicropollutants_Status90D',
                                                     'MineralMicropollutants_Status1Y',
                                                     'MineralMicropollutants_Status180D',
                                                     'MineralMicropollutants_Status90D'])])),
                  ('model',
                   ContiguousLabelWrapper(estimator=<catboost.core.CatBoostClassifier object at 0x0000016A75387B50>,
                                          global_n_classes_=5))]),
  'uncalibrated_model': Pipeline(steps=[('pre',
                   ColumnTransformer(transformers=[('num',
                                                    Pipeline(steps=[('imp',
                                                                     SimpleImputer(strategy='median'))]),
                                                    ['TotalAbundance_SamplingOperation',
                                                     'Achat02', 'Achde03',
                                                     'Achla02', 'Achli03',
                                                     'Achmi02', 'Achpy01',
                                                     'Achri01', 'Achsu01',
                                                     'Achth01', 'Amppe02',
                                                     'Coceu01', 'Cocli01',
                                                     'Cocpe01', 'Cocpl01',
                                                     'Cymmi01', 'Cymsi01',
                                                     'Cymve01', 'Dente01',
                                                     'Diaeh01', 'Di...
                                                     'SuspendedMatter_Status90D',
                                                     'OrganicMicropollutants_Status1Y',
                                                     'OrganicMicropollutants_Status180D',
                                                     'OrganicMicropollutants_Status90D',
                                                     'MineralMicropollutants_Status1Y',
                                                     'MineralMicropollutants_Status180D',
                                                     'MineralMicropollutants_Status90D'])])),
                  ('model',
                   ContiguousLabelWrapper(estimator=<catboost.core.CatBoostClassifier object at 0x0000016A75387B50>,
                                          global_n_classes_=5))]),
  'n_train': 1313,
  'n_infer': 172,
  'y_tr': SamplingOperations_code
  S05168100_20070809        High
  S05168100_20080806        High
  S05168100_20090625        High
  S05168100_20100629        High
  S05168100_20110809        High
                          ...
  S06175820_20220601        High
  S06175840_20100630    Moderate
  S06175840_20110629        Good
  S06175840_20130625        Good
  S06175840_20140609        High
  Name: IBD_EQR_Status, Length: 1313, dtype: object,
  'y_tr_enc': SamplingOperations_code
  S05168100_20070809    2
  S05168100_20080806    2
  S05168100_20090625    2
  S05168100_20100629    2
  S05168100_20110809    2
                       ..
  S06175820_20220601    2
  S06175840_20100630    3
  S06175840_20110629    1
  S06175840_20130625    1
  S06175840_20140609    2
  Length: 1313, dtype: int64,
  'oof_pred': SamplingOperations_code
  S05168100_20070809        High
  S05168100_20080806        High
  S05168100_20090625        High
  S05168100_20100629        High
  S05168100_20110809        High
                          ...
  S06175820_20220601        High
  S06175840_20100630    Moderate
  S06175840_20110629        Good
  S06175840_20130625        Good
  S06175840_20140609        High
  Name: oof_pred, Length: 1313, dtype: object,
  'oof_proba': array([[1.57817629e-11, 2.35901154e-07, 9.99999758e-01, 6.09272190e-09,
          4.28399281e-11],
         [7.04915175e-11, 4.18134459e-07, 9.99999534e-01, 4.71858389e-08,
          4.13065650e-10],
         [2.40466640e-11, 1.57699004e-07, 9.99999841e-01, 7.42987926e-10,
          1.04529554e-10],
         ...,
         [4.14021571e-09, 9.99945171e-01, 4.86394156e-06, 4.99571309e-05,
          4.24526853e-09],
         [9.32277568e-09, 9.99968095e-01, 1.10757932e-05, 2.07877235e-05,
          3.19502310e-08],
         [1.72458993e-10, 1.22391556e-06, 9.99998746e-01, 3.00941673e-08,
          2.21208575e-10]], shape=(1313, 5)),
  'proba_available': True,
  'yhat_te': SamplingOperations_code
  S05169000_20130911    High
  S05169000_20200819    High
  S05172000_20210813    Good
  S05172050_20210824    Good
  S05172350_20120827    High
                        ...
  S06175540_20150728    High
  S06175600_20170904    High
  S06175600_20180926    High
  S06175645_20220809    High
  S06175840_20090624    Good
  Name: yhat_te, Length: 172, dtype: object,
  'proba_te':                             proba_Bad    proba_Good  proba_High  \
  SamplingOperations_code
  S05169000_20130911       4.405332e-11  6.480379e-07    0.999999
  S05169000_20200819       5.531844e-08  8.629586e-03    0.991122
  S05172000_20210813       8.710433e-08  9.999065e-01    0.000015
  S05172050_20210824       2.698265e-07  9.917607e-01    0.007020
  S05172350_20120827       4.295195e-11  6.003390e-07    0.999999
  ...                               ...           ...         ...
  S06175540_20150728       2.107145e-10  1.265554e-05    0.999987
  S06175600_20170904       3.212544e-09  3.365720e-05    0.999959
  S06175600_20180926       6.290797e-08  2.383134e-02    0.975875
  S06175645_20220809       7.009929e-09  1.186843e-04    0.999725
  S06175840_20090624       9.989926e-08  9.912003e-01    0.004245

                           proba_Moderate    proba_Poor
  SamplingOperations_code
  S05169000_20130911         5.524558e-08  5.483217e-11
  S05169000_20200819         2.476250e-04  4.129562e-07
  S05172000_20210813         7.794203e-05  2.354208e-07
  S05172050_20210824         1.217610e-03  1.273471e-06
  S05172350_20120827         1.379213e-08  1.665204e-10
  ...                                 ...           ...
  S06175540_20150728         3.551245e-08  2.126066e-09
  S06175600_20170904         7.211774e-06  3.671931e-08
  S06175600_20180926         2.928291e-04  1.178899e-06
  S06175645_20220809         1.565707e-04  9.644921e-08
  S06175840_20090624         4.553687e-03  1.115975e-06

  [172 rows x 5 columns],
  'y_filled': SamplingOperations_code
  S05168100_20070809    High
  S05168100_20080806    High
  S05168100_20090625    High
  S05168100_20100629    High
  S05168100_20110809    High
                        ...
  S06175540_20150728    High
  S06175600_20170904    High
  S06175600_20180926    High
  S06175645_20220809    High
  S06175840_20090624    Good
  Name: IBD_EQR_Status, Length: 1485, dtype: object,
  'feature_importances': Achpy01                                      15.629603
  Achmi02                                       4.037348
  Coceu01                                       3.682205
  Selni01                                       3.240835
  Achsu01                                       2.956763
                                                 ...
  MineralMicropollutants_Status90D_Good         0.000000
  MineralMicropollutants_Status90D_High         0.000000
  MineralMicropollutants_Status90D_Moderate     0.000000
  MineralMicropollutants_Status90D_None         0.000000
  MineralMicropollutants_Status90D_Poor         0.000000
  Length: 343, dtype: float64,
  'cv_results_': {'mean_fit_time': array([72.93035603, 40.85073018, 66.30948722]),
   'std_fit_time': array([0.32385159, 1.33139682, 1.43640316]),
   'mean_score_time': array([0.08383858, 0.14492929, 0.12352455]),
   'std_score_time': array([0.04364002, 0.00389779, 0.03235519]),
   'param_model__estimator__bagging_temperature': masked_array(data=[0.13292918943162169, 0.02938027938703535,
                      0.6358358856676253],
                mask=[False, False, False],
          fill_value=1e+20),
   'param_model__estimator__depth': masked_array(data=[8, 6, 6],
                mask=[False, False, False],
          fill_value=999999),
   'param_model__estimator__iterations': masked_array(data=[570, 514, 961],
                mask=[False, False, False],
          fill_value=999999),
   'param_model__estimator__l2_leaf_reg': masked_array(data=[1.893327030371083, 0.001819899369726822,
                      0.0017887987366138093],
                mask=[False, False, False],
          fill_value=1e+20),
   'param_model__estimator__learning_rate': masked_array(data=[0.07661100707771368, 0.19030368381735815,
                      0.11654126622287461],
                mask=[False, False, False],
          fill_value=1e+20),
   'params': [{'model__estimator__bagging_temperature': np.float64(0.13292918943162169),
     'model__estimator__depth': 8,
     'model__estimator__iterations': 570,
     'model__estimator__l2_leaf_reg': np.float64(1.893327030371083),
     'model__estimator__learning_rate': np.float64(0.07661100707771368)},
    {'model__estimator__bagging_temperature': np.float64(0.02938027938703535),
     'model__estimator__depth': 6,
     'model__estimator__iterations': 514,
     'model__estimator__l2_leaf_reg': np.float64(0.001819899369726822),
     'model__estimator__learning_rate': np.float64(0.19030368381735815)},
    {'model__estimator__bagging_temperature': np.float64(0.6358358856676253),
     'model__estimator__depth': 6,
     'model__estimator__iterations': 961,
     'model__estimator__l2_leaf_reg': np.float64(0.0017887987366138093),
     'model__estimator__learning_rate': np.float64(0.11654126622287461)}],
   'split0_test_score': array([0.85540335, 0.85388128, 0.85996956]),
   'split1_test_score': array([0.85365854, 0.85365854, 0.8597561 ]),
   'mean_test_score': array([0.85453094, 0.85376991, 0.85986283]),
   'std_test_score': array([0.00087241, 0.00011137, 0.00010673]),
   'rank_test_score': array([2, 3, 1], dtype=int32)},
  'best_cv_score_bal_acc': 0.8598628280803355,
  'oof_bal_acc': 1.0},
 2: {'best_name': 'CatBoost',
  'best_cv_score_acc': 0.922077922077922,
  'oof_acc': 1.0,
  'oof_f1_macro': 1.0,
  'oof_confusion':                pred_Bad  pred_Good  pred_High  pred_Moderate  pred_Poor
  true_Bad              1          0          0              0          0
  true_Good             0         19          0              0          0
  true_High             0          0        279              0          0
  true_Moderate         0          0          0              7          0
  true_Poor             0          0          0              0          2,
  'classes_': array(['Bad', 'Good', 'High', 'Moderate', 'Poor'], dtype=object),
  'label_encoder': LabelEncoder(),
  'model': Pipeline(steps=[('pre',
                   ColumnTransformer(transformers=[('num',
                                                    Pipeline(steps=[('imp',
                                                                     SimpleImputer(strategy='median'))]),
                                                    ['TotalAbundance_SamplingOperation',
                                                     'Achaf02', 'Achat02',
                                                     'Achli03', 'Achmi02',
                                                     'Achmi03', 'Achpy01',
                                                     'Achsu01', 'Amppe02',
                                                     'Coceu01', 'Cocli01',
                                                     'Cocpe01', 'Cocpl01',
                                                     'Cymco01', 'Cymex01',
                                                     'Cymex02', 'Cymmi01',
                                                     'Cymsi01', 'Cymve01',
                                                     'Dente01', 'Di...
                                                     'SuspendedMatter_Status90D',
                                                     'OrganicMicropollutants_Status1Y',
                                                     'OrganicMicropollutants_Status180D',
                                                     'OrganicMicropollutants_Status90D',
                                                     'MineralMicropollutants_Status1Y',
                                                     'MineralMicropollutants_Status180D',
                                                     'MineralMicropollutants_Status90D'])])),
                  ('model',
                   ContiguousLabelWrapper(estimator=<catboost.core.CatBoostClassifier object at 0x0000016A755574D0>,
                                          global_n_classes_=5))]),
  'uncalibrated_model': Pipeline(steps=[('pre',
                   ColumnTransformer(transformers=[('num',
                                                    Pipeline(steps=[('imp',
                                                                     SimpleImputer(strategy='median'))]),
                                                    ['TotalAbundance_SamplingOperation',
                                                     'Achaf02', 'Achat02',
                                                     'Achli03', 'Achmi02',
                                                     'Achmi03', 'Achpy01',
                                                     'Achsu01', 'Amppe02',
                                                     'Coceu01', 'Cocli01',
                                                     'Cocpe01', 'Cocpl01',
                                                     'Cymco01', 'Cymex01',
                                                     'Cymex02', 'Cymmi01',
                                                     'Cymsi01', 'Cymve01',
                                                     'Dente01', 'Di...
                                                     'SuspendedMatter_Status90D',
                                                     'OrganicMicropollutants_Status1Y',
                                                     'OrganicMicropollutants_Status180D',
                                                     'OrganicMicropollutants_Status90D',
                                                     'MineralMicropollutants_Status1Y',
                                                     'MineralMicropollutants_Status180D',
                                                     'MineralMicropollutants_Status90D'])])),
                  ('model',
                   ContiguousLabelWrapper(estimator=<catboost.core.CatBoostClassifier object at 0x0000016A755574D0>,
                                          global_n_classes_=5))]),
  'n_train': 308,
  'n_infer': 44,
  'y_tr': SamplingOperations_code
  S06000754_20210217    High
  S06000754_20220208    High
  S06000754_20230206    High
  S06000755_20210223    High
  S06000755_20220215    High
                        ...
  S06820089_20190222    High
  S06820089_20200220    High
  S06820089_20210218    High
  S06820089_20220208    High
  S06820089_20230213    High
  Name: IBD_EQR_Status, Length: 308, dtype: object,
  'y_tr_enc': SamplingOperations_code
  S06000754_20210217    2
  S06000754_20220208    2
  S06000754_20230206    2
  S06000755_20210223    2
  S06000755_20220215    2
                       ..
  S06820089_20190222    2
  S06820089_20200220    2
  S06820089_20210218    2
  S06820089_20220208    2
  S06820089_20230213    2
  Length: 308, dtype: int64,
  'oof_pred': SamplingOperations_code
  S06000754_20210217    High
  S06000754_20220208    High
  S06000754_20230206    High
  S06000755_20210223    High
  S06000755_20220215    High
                        ...
  S06820089_20190222    High
  S06820089_20200220    High
  S06820089_20210218    High
  S06820089_20220208    High
  S06820089_20230213    High
  Name: oof_pred, Length: 308, dtype: object,
  'oof_proba': array([[5.70055821e-09, 1.04094378e-07, 9.99999856e-01, 3.08190330e-08,
          3.44919615e-09],
         [1.01784348e-08, 9.52103019e-08, 9.99999861e-01, 2.86970460e-08,
          4.77826358e-09],
         [4.33637452e-09, 3.04601407e-08, 9.99999955e-01, 8.95037317e-09,
          1.62058045e-09],
         ...,
         [7.98120906e-09, 6.37901654e-08, 9.99999907e-01, 1.71445142e-08,
          4.05312164e-09],
         [4.79100643e-09, 8.33981338e-09, 9.99999976e-01, 8.49383293e-09,
          1.99437700e-09],
         [1.86125702e-08, 1.47347711e-07, 9.99999757e-01, 6.69118988e-08,
          1.02567417e-08]], shape=(308, 5)),
  'proba_available': True,
  'yhat_te': SamplingOperations_code
  S06132900_20150216        High
  S06133000_20170222        High
  S06133560_20110209        High
  S06133560_20140210        High
  S06134300_20120228        High
  S06135350_20130307        High
  S06135350_20160822        High
  S06135350_20220207        High
  S06137020_20120221        High
  S06139080_20210819        Good
  S06139400_20150803        Good
  S06139405_20150803        Good
  S06139500_20090319        Good
  S06139500_20100317    Moderate
  S06139500_20160817        Good
  S06139700_20150803        Good
  S06140010_20160830        High
  S06150795_20130314        High
  S06150795_20140212        High
  S06150795_20160801        High
  S06151000_20100823        High
  S06151000_20110726        High
  S06152400_20190207        High
  S06154250_20090324        High
  S06154250_20110309        High
  S06154250_20230207        High
  S06159930_20200218        High
  S06159930_20220221        High
  S06159930_20230214        High
  S06210640_20210906        Good
  S06211700_20090721        High
  S06300010_20090825        High
  S06300010_20180828        High
  S06300010_20220705        High
  S06580713_20220608        High
  S06592020_20120222        High
  S06700007_20210831        High
  S06700070_20090825        High
  S06700070_20160620        High
  S06700075_20120611        High
  S06700094_20210830        High

In [23]:
for i in range(3, 23):
    print(f"Region {i}:")
    print(auto.results[i]["best_name"], auto.results[i]["oof_bal_acc"])

Region 3:
CatBoost 0.8133182844243793
Region 4:
CatBoost 0.7044534412955465
Region 5:
CatBoost 0.8598356694055099
Region 6:
CatBoost 0.827186512118019
Region 7:
CatBoost 0.8862660944206009
Region 8:
CatBoost 1.0
Region 9:
CatBoost 0.8835376532399299
Region 10:
CatBoost 0.8486279138388906
Region 11:
CatBoost 0.8361086765994742
Region 12:
CatBoost 0.8648519579751671
Region 13:
CatBoost 0.7871621621621622
Region 14:
CatBoost 0.8659629843840371
Region 15:
CatBoost 0.8107370336669699
Region 16:
CatBoost 0.7854984894259819
Region 17:
CatBoost 0.7821229050279329
Region 18:
CatBoost 0.8219037871033776
Region 19:
CatBoost 1.0
Region 20:
CatBoost 0.7611607142857143
Region 21:
CatBoost 0.7911663807890223
Region 22:
CatBoost 0.675

# Get predictions

In [24]:
all_cls = all_preds.set_index('SamplingOperations_code')
yhat_te = all_cls['yhat_te'][all_cls['yhat_te'].notna()]
yhat_te = yhat_te.to_frame()
yhat_te.to_csv('Status_2_region.csv')
yhat_te

                          yhat_te
SamplingOperations_code
S05169000_20130911           High
S05169000_20200819           High
S05172000_20210813           Good
S05172050_20210824           Good
S05172350_20120827           High
...                           ...
S03128500_20120723       Moderate
S03128640_20130718       Moderate
S03128640_20181011       Moderate
S03128732_20210817           Good
S03129170_20150630           High

[5663 rows x 1 columns]

In [25]:
# For all regions 1, 2, ..., 22
regiondfs = {}
for region in range(1, 3):
    print(f"Region: {region}")
    regiondf = df[df['HERlvl1Code'] == region]

    cleanregion = cleandf.IWANTMYXCLEAN(regiondf, thresh_high_missing=.90)
    regiondfs[region] = cleanregion

auto = MultiRegionBoostedClassifier(regiondfs, random_state=42, verbose=True, models=["XGBoost"])
auto.process_missing_class(scoring="accuracy", n_iter_per_model=3, max_splits=5, calibrate=True)

Region: 1
Dropped exact duplicate columns: ['Achac01', 'Achal01', 'Achca01', 'Achch01', 'Achcl01', 'Achco01', 'Achco03', 'Achcy01', 'Achde01', 'Achde02', 'Achdi01', 'Achdi02', 'Achel01', 'Achen01', 'Achex03', 'Achfl01', 'Achfr01', 'Achgr01', 'Achgr02', 'Achha01', 'Achhe01', 'Achhi01', 'Achho01', 'Achho02', 'Achim01', 'Achim02', 'Achim03', 'Achin01', 'Achin02', 'Achjo01', 'Achko01', 'Achkr01', 'Achkr03', 'Achkr04', 'Achku01', 'Achla01', 'Achla05', 'Achle01', 'Achle02', 'Achli02', 'Achli04', 'Achlo01', 'Achlu01', 'Achlu02', 'Achmo01', 'Achmo02', 'Achna01', 'Achna02', 'Achni01', 'Achno01', 'Achpa01', 'Achpe01', 'Achpe02', 'Achpl01', 'Achpo01', 'Achpr01', 'Achpr02', 'Achps01', 'Achps02', 'Achps03', 'Achpu01', 'Achro01', 'Achro03', 'Achru02', 'Achsc01', 'Achse01', 'Achse02', 'Achsi01', 'Achst01', 'Achst02', 'Achst04', 'Achsu02', 'Achsu04', 'Achtu01', 'Achzi01', 'Actde01', 'Actno01', 'Actro01', 'Actse01', 'Actsp01', 'Actsu01', 'Actvu01', 'Adlaq01', 'Adlbr01', 'Adlmu01', 'Adlmu02', 'Adlpa01', 'Afrre01', 'Ampae01', 'Ampaf01', 'Ampal01', 'Ampbi01', 'Ampbu01', 'Ampco01', 'Ampcu01', 'Ampde01', 'Ampdi01', 'Ampdi02', 'Ampdu01', 'Ampei01', 'Ampex01', 'Ampfo01', 'Ampfo02', 'Amphe01', 'Amphi01', 'Ampli01', 'Ampme01', 'Ampmi01', 'Ampmi02', 'Ampne01', 'Ampne02', 'Amppa01', 'Amppo01', 'Amppo02', 'Amppr01', 'Ampps01', 'Ampri01', 'Ampst01', 'Ampst02', 'Ampsu01', 'Ampsu02', 'Ampsu03', 'Ampsu04', 'Amptu01', 'Ampve02', 'Ampvi01', 'Anaba01', 'Anemi01', 'Anetu01', 'Anoeu01', 'Anoga01', 'Anoin01', 'Anosp01', 'Aulal01', 'Aulbr01', 'Aulcr01', 'Aulcr02', 'Auldi01', 'Aulis01', 'Aulit01', 'Aulli01', 'Aulpa01', 'Aulps01', 'Aulps02', 'Aulsu02', 'Aulva01', 'Azpno01', 'Bacul01', 'Braca01', 'Brali01', 'Brapr01', 'Braps01', 'Breke01', 'Calae02', 'Calal01', 'Calau01', 'Calbi01', 'Calfa01', 'Calfo02', 'Calhy01', 'Calla01', 'Calla02', 'Calla03', 'Calle01', 'Calmi01', 'Calpa01', 'Calpu01', 'Calsc01', 'Caltr01', 'Calve01', 'Calwe01', 'Camcy01', 'Camhi01', 'Capcr01', 'Catad01', 'Cavpa01', 'Cenre01', 'Cergr01', 'Chaal01', 'Chabe01', 'Chafa01', 'Chamu01', 'Chare01', 'Charh01', 'Chasc01', 'Chath01', 'Clico01', 'Cliin01', 'Cocbr01', 'Cocca01', 'Coccl01', 'Cocco01', 'Cocde01', 'Cocdi02', 'Cocgr01', 'Cochu02', 'Cocin01', 'Cocla01', 'Cocle01', 'Cocme01', 'Cocne01', 'Cocps01', 'Cocre01', 'Cocro01', 'Cocsc01', 'Cocse01', 'Cocsu01', 'Conwe01', 'Cosco01', 'Cosla01', 'Cosla02', 'Craac01', 'Craac02', 'Craha01', 'Crari01', 'Crasv01', 'Cravi01', 'Crazi01', 'Creru01', 'Creth01', 'Ctepu01', 'Cycbo01', 'Cyccy01', 'Cycde01', 'Cycde02', 'Cycgl01', 'Cycir01', 'Cyckr01', 'Cycku01', 'Cycop01', 'Cycpl01', 'Cycpl02', 'Cycsc01', 'Cycst02', 'Cycst03', 'Cycst04', 'Cycsu01', 'Cycth01', 'Cylgr01', 'Cymal01', 'Cymal02', 'Cyman01', 'Cyman02', 'Cyman03', 'Cyman04', 'Cymap01', 'Cymas01', 'Cymbe01', 'Cymbi01', 'Cymbr01', 'Cymbu01', 'Cymci01', 'Cymcu01', 'Cymcy01', 'Cymdi01', 'Cymdo01', 'Cymeh01', 'Cymel02', 'Cymex03', 'Cymfr01', 'Cymga01', 'Cymhe01', 'Cymhe02', 'Cymhu01', 'Cymin01', 'Cymin02', 'Cymin03', 'Cymka01', 'Cymko01', 'Cymku01', 'Cymla02', 'Cymla03', 'Cymlu01', 'Cymma01', 'Cymme02', 'Cymna02', 'Cymob01', 'Cymob02', 'Cympa01', 'Cympl01', 'Cympr01', 'Cympr02', 'Cympr03', 'Cympu01', 'Cymrh01', 'Cymru01', 'Cymsi02', 'Cymsp01', 'Cymst01', 'Cymsu01', 'Cymsu02', 'Cymsu03', 'Cymsu04', 'Cymsu06', 'Cymsu08', 'Cymsu09', 'Cymtr01', 'Cymtu04', 'Cymvu01', 'Delap01', 'Delco01', 'Delde01', 'Delkr01', 'Delve01', 'Dener01', 'Denfr01', 'Denpa01', 'Dense01', 'Densu01', 'Densu02', 'Diade01', 'Diapy01', 'Diate02', 'Diavi01', 'Dicda01', 'Dimna01', 'Dipab01', 'Dipae01', 'Dipbo01', 'Dipbo02', 'Dipbu01', 'Dipca01', 'Dipde01', 'Dipfo01', 'Dipfo02', 'Diphi01', 'Dipmi01', 'Dipmo01', 'Dippa01', 'Dipps01', 'Dippu01', 'Dipst01', 'Dipsu01', 'Dipti01', 'Disin01', 'Disst01', 'Encae01', 'Encaf01', 'Encal01', 'Encau01', 'Encbl01', 'Encbo01', 'Encel01', 'Encfa01', 'Encfo02', 'Encge01', 'Encgr01', 'Enche01', 'Encho01', 'Enchu01', 'Encin01', 'Enckr01', 'Enckr02', 'Encla01', 'Encla02', 'Enclu01', 'Encme01', 'Encmi01', 'Encmi02', 'Encmu01', 'Encne02', 'Encne03', 'Encno01', 'Encob01', 'Encpa01', 'Encpe01', 'Encpr02', 'Encre01', 'Encre02', 'Encro01', 'Encro02', 'Encsp01', 'Encsu01', 'Encsu02', 'Encsy01', 'Encth01', 'Encva01', 'Entor01', 'Entpa01', 'Eolar01', 'Eolbe01', 'Eolch01', 'Eolcr01', 'Eolin01', 'Epifr01', 'Epiin01', 'Epiop01', 'Epipa01', 'Epire01', 'Epiru01', 'Epism01', 'Epitu01', 'Ethpu01', 'Eucau01', 'Eucdi01', 'Eunam01', 'Eunar02', 'Eunar04', 'Eunau01', 'Eunbe01', 'Eunbi01', 'Eunbi02', 'Eunbi03', 'Eunbi04', 'Eunbo02', 'Eunch01', 'Eunci01', 'Eunci02', 'Eunci03', 'Euncu01', 'Eunde01', 'Eundi01', 'Eundi02', 'Eundo01', 'Eunel01', 'Eunen01', 'Eunfa01', 'Eunfl01', 'Eunfo02', 'Eunge01', 'Eunge02', 'Eungi01', 'Eungl01', 'Eungl02', 'Eungr01', 'Eunin02', 'Eunis01', 'Eunkr01', 'Eunla01', 'Eunla02', 'Eunme01', 'Eunme02', 'Eunme03', 'Eunmi01', 'Eunmi02', 'Eunmo01', 'Eunmu01', 'Eunmy01', 'Eunna01', 'Eunne01', 'Eunne02', 'Eunny01', 'Eunoc01', 'Eunor01', 'Eunpa01', 'Eunpa03', 'Eunpa04', 'Eunpa05', 'Eunpe01', 'Eunpe02', 'Eunpe03', 'Eunpr01', 'Eunps01', 'Eunps02', 'Eunrh01', 'Eunse01', 'Eunse02', 'Eunse03', 'Eunsi01', 'Eunso01', 'Eunst01', 'Eunsu01', 'Eunsu03', 'Eunsu04', 'Eunta01', 'Eunte02', 'Eunth01', 'Euntr01', 'Euntr02', 'Eunur01', 'Eunva01', 'Eunva02', 'Eunyb01', 'Exipu01', 'Falcl01', 'Falcr01', 'Falom01', 'Falpy01', 'Fraac01', 'Fraac02', 'Fraac03', 'Fraae01', 'Fraal01', 'Fraaq01', 'Fraat01', 'Frabi02', 'Frabi04', 'Frabi05', 'Frabo01', 'Fraca05', 'Fraco02', 'Fradi01', 'Frael01', 'Fraex01', 'Frafo01', 'Frafr01', 'Frage01', 'Frage02', 'Fragr02', 'Frahe01', 'Frain01', 'Frain02', 'Fraka01', 'Frala01', 'Frala03', 'Fralo01', 'Frame01', 'Frami01', 'Frami02', 'Frami04', 'Framu01', 'Frane01', 'Frane03', 'Frani01', 'Fraos01', 'Frapa02', 'Frape02', 'Frape03', 'Frapo01', 'Fraps01', 'Fraps02', 'Frapu01', 'Fraro01', 'Frasi01', 'Frasu01', 'Frasu02', 'Frate02', 'Frate03', 'Fratr01', 'Fraul01', 'Fraul02', 'Fraun01', 'Fruam01', 'Fruap01', 'Fruau01', 'Frucr01', 'Frucu01', 'Frudi01', 'Frukr01', 'Fruli01', 'Frune01', 'Frune02', 'Frupa01', 'Frupu01', 'Fruqu01', 'Frure01', 'Frurh01', 'Frusa01', 'Fruse01', 'Frusp01', 'Fruvi01', 'Fruwe01', 'Geige01', 'Geihi01', 'Geita01', 'Geren01', 'Glotr01', 'Gomae01', 'Gomam01', 'Goman01', 'Goman06', 'Gombo01', 'Gombo03', 'Gombr01', 'Gomca03', 'Gomca05', 'Gomcl03', 'Gomco01', 'Gomco02', 'Gomco03', 'Gomco05', 'Gomcu01', 'Gomcu03', 'Gomda01', 'Gomde01', 'Gomde02', 'Gomdi01', 'Gomdr01', 'Gomen01', 'Gomer01', 'Gomer02', 'Gomex02', 'Gomfo01', 'Gomfr01', 'Gomgr02', 'Gomgr03', 'Gomgr04', 'Gomha01', 'Gomhe01', 'Gomho01', 'Gomin01', 'Gomin02', 'Gomin04', 'Gomin05', 'Gomja01', 'Gomje01', 'Gomko01', 'Gomla02', 'Gomla03', 'Gomla06', 'Gomli01', 'Gomli02', 'Gomli03', 'Gomlo01', 'Gomlo02', 'Gomma01', 'Gomme01', 'Gomna01', 'Gomoa01', 'Gomob01', 'Gomob02', 'Gomoh01', 'Gomol01', 'Gomop01', 'Gompa02', 'Gompa03', 'Gompa04', 'Gompa05', 'Gompe01', 'Gompl01', 'Gompr01', 'Gompr02', 'Gomps01', 'Gomps02', 'Gomps03', 'Gompu01', 'Gompy01', 'Gomsa01', 'Gomsi01', 'Gomsp01', 'Gomsp02', 'Gomst01', 'Gomst02', 'Gomsu01', 'Gomsu02', 'Gomsu04', 'Gomsu05', 'Gomta01', 'Gomta02', 'Gomtr01', 'Gomtu01', 'Gomtu02', 'Gomun01', 'Gomva01', 'Gomva03', 'Gomva04', 'Gomva05', 'Gomve01', 'Gomvi01', 'Gomze01', 'Grama01', 'Grase01', 'Grusi01', 'Gyrli01', 'Gyrob01', 'Gyrsc01', 'Halac01', 'Halap01', 'Halbu01', 'Halcy01', 'Halho01', 'Halno01', 'Halol01', 'Halpe01', 'Halsu01', 'Halva01', 'Hanab01', 'Hanau01', 'Hanca01', 'Hanco01', 'Hanmo01', 'Hanps01', 'Hanre01', 'Hasdu01', 'Himfa01', 'Himso01', 'Hipar01', 'Hipca01', 'Hipco01', 'Hipco02', 'Hipge01', 'Hipne01', 'Hipol01', 'Hipps01', 'Hippu01', 'Hipru01', 'Hipsu01', 'Hombu01', 'Homca01', 'Homsu01', 'Humbr01', 'Humga01', 'Humsc01', 'Hydtr01', 'Hydwh01', 'Karam01', 'Karob01', 'Karpl01', 'Kobja01', 'Kobpa01', 'Kobps01', 'Kobsa01', 'Kobsu01', 'Kolsu01', 'Kurae01', 'Lacla01', 'Lemex01', 'Lemhu01', 'Lepmi01', 'Linau01', 'Linba01', 'Linbo01', 'Linco01', 'Linco02', 'Linfo01', 'Linpr01', 'Linte01', 'Lutac01', 'Lutco01', 'Lutfr01', 'Luthl01', 'Lutin01', 'Lutna01', 'Lutpe01', 'Lutpe02', 'Lutps01', 'Lutro01', 'Lutsa01', 'Lutsi01', 'Lutsp01', 'Lutve01', 'Masac01', 'Masba01', 'Masel01', 'Masex01', 'Masex02', 'Masin01', 'Masla01', 'Maspa01', 'Massm01', 'Masva01', 'Mayas01', 'Mayca01', 'Mayca02', 'Mayin01', 'Melcr01', 'Meldi01', 'Meldi02', 'Melgr01', 'Melit01', 'Melja01', 'Mello01', 'Melly01', 'Melmo01', 'Melmu01', 'Melny01', 'Melsc01', 'Melsp01', 'Melte02', 'Mesme01', 'Mickr01', 'Micpa01', 'Minch01', 'Muegi01', 'Muesp01', 'Nankr01', 'Nantr01', 'Navab01', 'Navab02', 'Navab03', 'Navac01', 'Navac03', 'Navad01', 'Navad02', 'Navag01', 'Navag02', 'Naval01', 'Naval02', 'Navam01', 'Navam02', 'Navam03', 'Navam04', 'Navam06', 'Navam07', 'Navan01', 'Navan03', 'Navan04', 'Navan06', 'Navap01', 'Navap02', 'Navaq02', 'Navar01', 'Navar03', 'Navat01', 'Navau01', 'Navba01', 'Navba02', 'Navbi01', 'Navbi02', 'Navbi03', 'Navbj01', 'Navbo01', 'Navbr01', 'Navbr03', 'Navbr04', 'Navbr05', 'Navbr06', 'Navbr07', 'Navbu01', 'Navbu02', 'Navca01', 'Navca02', 'Navca03', 'Navca04', 'Navca05', 'Navca06', 'Navca09', 'Navce01', 'Navch01', 'Navci02', 'Navcl01', 'Navcl02', 'Navcl03', 'Navcl04', 'Navco02', 'Navco03', 'Navco04', 'Navco06', 'Navcr01', 'Navcr02', 'Navcr03', 'Navcr06', 'Navcr08', 'Navcu01', 'Navcu02', 'Navde01', 'Navde02', 'Navde04', 'Navde05', 'Navde06', 'Navde07', 'Navdi01', 'Navdi02', 'Navdi05', 'Navdi07', 'Navdi08', 'Navdi09', 'Navdi10', 'Navdo01', 'Naveg01', 'Navei01', 'Navel01', 'Navel02', 'Navel03', 'Navev01', 'Navex03', 'Navfa01', 'Navfa02', 'Navfe01', 'Navfl01', 'Navfo01', 'Navfo02', 'Navfo03', 'Navfr01', 'Navga01', 'Navge01', 'Navge03', 'Navgi01', 'Navgl01', 'Navgo01', 'Navgr02', 'Navgr03', 'Navha01', 'Navha03', 'Navha04', 'Navha05', 'Navha06', 'Navha07', 'Navha08', 'Navhe01', 'Navhe03', 'Navho01', 'Navhu01', 'Navhu02', 'Navim01', 'Navin01', 'Navin02', 'Navin03', 'Navin04', 'Navin05', 'Navin07', 'Navin08', 'Navin09', 'Navin10', 'Navir01', 'Navir02', 'Navja02', 'Navja03', 'Navju01', 'Navko01', 'Navko02', 'Navkr01', 'Navku01', 'Navla02', 'Navla03', 'Navla05', 'Navla06', 'Navla07', 'Navle03', 'Navle04', 'Navle06', 'Navli01', 'Navli02', 'Navli03', 'Navlo01', 'Navlo02', 'Navlo03', 'Navlu01', 'Navlu03', 'Navma01', 'Navma02', 'Navma03', 'Navma04', 'Navma05', 'Navme01', 'Navme02', 'Navme03', 'Navme05', 'Navmi01', 'Navmi03', 'Navmi04', 'Navmi05', 'Navmi06', 'Navmi07', 'Navmi08', 'Navmo01', 'Navmo02', 'Navmo03', 'Navmo04', 'Navmo06', 'Navmo07', 'Navmo10', 'Navmu01', 'Navmu03', 'Navmu04', 'Navmu05', 'Navmu07', 'Navna01', 'Navne01', 'Navne02', 'Navni01', 'Navno01', 'Navnu01', 'Navny01', 'Navob01', 'Navob02', 'Navob03', 'Navob05', 'Navop01', 'Navop02', 'Navpa02', 'Navpa03', 'Navpa04', 'Navpa05', 'Navpa06', 'Navpa07', 'Navpe01', 'Navpe02', 'Navpe03', 'Navpe04', 'Navph01', 'Navph02', 'Navpl01', 'Navpr02', 'Navpr03', 'Navps03', 'Navps04', 'Navps05', 'Navps07', 'Navps09', 'Navps11', 'Navps12', 'Navpu01', 'Navpu02', 'Navpu03', 'Navpu04', 'Navpy01', 'Navqu01', 'Navra03', 'Navra04', 'Navre01', 'Navre02', 'Navre03', 'Navre05', 'Navre06', 'Navrh03', 'Navri01', 'Navri02', 'Navri03', 'Navri04', 'Navro01', 'Navro02', 'Navru01', 'Navsa01', 'Navsa02', 'Navsa04', 'Navsa05', 'Navsa07', 'Navsc01', 'Navsc02', 'Navsc03', 'Navsc05', 'Navsc06', 'Navsc07', 'Navsc08', 'Navse01', 'Navse03', 'Navse04', 'Navse06', 'Navse07', 'Navsi02', 'Navsi03', 'Navsl01', 'Navsm01', 'Navsp01', 'Navsp03', 'Navst01', 'Navst02', 'Navst03', 'Navst06', 'Navst07', 'Navsu01', 'Navsu02', 'Navsu04', 'Navsu06', 'Navsu10', 'Navsu11', 'Navsu12', 'Navsu13', 'Navsu14', 'Navsu16', 'Navsu17', 'Navsu18', 'Navsu19', 'Navsu20', 'Navsy02', 'Navta01', 'Navta02', 'Navte02', 'Navte03', 'Navth01', 'Navto01', 'Navtr01', 'Navtr03', 'Navtr04', 'Navtu01', 'Navtu02', 'Navul01', 'Navum01', 'Navum02', 'Navun01', 'Navva01', 'Navva02', 'Navva04', 'Navva05', 'Navva06', 'Navve01', 'Navve02', 'Navve05', 'Navve07', 'Navvi04', 'Navwe01', 'Navwi01', 'Navwi02', 'Navwi04', 'Navwy01', 'Navza01', 'Navze01', 'Neiaf01', 'Neiam01', 'Neiap01', 'Neibi01', 'Neibi02', 'Neibi03', 'Neibi04', 'Neica01', 'Neico01', 'Neicu01', 'Neide01', 'Neiel01', 'Neihe01', 'Neihu01', 'Neiin01', 'Neiir01', 'Neilo01', 'Neipe01', 'Neipr01', 'Neips01', 'Neise01', 'Neisu01', 'Neite01', 'Neive01', 'Neoco01', 'Nitac01', 'Nitac02', 'Nitac03', 'Nitac06', 'Nitae01', 'Nitae02', 'Nitag01', 'Nital01', 'Nital03', 'Nitam02', 'Nitam03', 'Nitam04', 'Nitan01', 'Nitau01', 'Nitau02', 'Nitba01', 'Nitba02', 'Nitba03', 'Nitba04', 'Nitbe02', 'Nitbi01', 'Nitbr01', 'Nitbr02', 'Nitbr03', 'Nitca01', 'Nitca02', 'Nitco01', 'Nitco03', 'Nitco04', 'Nitco06', 'Nitcu01', 'Nitcu02', 'Nitcu03', 'Nitde01', 'Nitde02', 'Nitde04', 'Nitde05', 'Nitde06', 'Nitdi01', 'Nitdi02', 'Nitdi03', 'Nitdi05', 'Nitdi06', 'Nitdu01', 'Nitep01', 'Nitet01', 'Niteu01', 'Nitfa01', 'Nitfi01', 'Nitfi02', 'Nitfl01', 'Nitfl02', 'Nitfo02', 'Nitfr01', 'Nitfu01', 'Nitge01', 'Nitgi01', 'Nitgo01', 'Nitgr01', 'Nitgr03', 'Nitha01', 'Nitho01', 'Nitho02', 'Nithu01', 'Nitin01', 'Nitin03', 'Nitin04', 'Nitin05', 'Nitju01', 'Nitla01', 'Nitla02', 'Nitla04', 'Nitla05', 'Nitla06', 'Nitla07', 'Nitle01', 'Nitle02', 'Nitli01', 'Nitli02', 'Nitli04', 'Nitma01', 'Nitmi02', 'Nitmi03', 'Nitmi04', 'Nitmo01', 'Nitmo02', 'Nitna01', 'Nitov01', 'Nitpa04', 'Nitpa05', 'Nitpa06', 'Nitpa07', 'Nitpa08', 'Nitpa09', 'Nitpe01', 'Nitpe02', 'Nitpe04', 'Nitpi01', 'Nitpl01', 'Nitps02', 'Nitpu01', 'Nitra01', 'Nitre02', 'Nitre03', 'Nitre04', 'Nitrh01', 'Nitro01', 'Nitro02', 'Nitro03', 'Nitsc01', 'Nitse01', 'Nitsi02', 'Nitsi03', 'Nitsp01', 'Nitst01', 'Nitsu02', 'Nitsu03', 'Nitsu04', 'Nitsu06', 'Nitsu07', 'Nitsu08', 'Nitsy01', 'Nitta01', 'Nitte01', 'Nitth01', 'Nitth02', 'Nittr02', 'Nittu01', 'Nitva01', 'Nitva02', 'Nitve01', 'Nitve02', 'Nitvi01', 'Nitvi02', 'Nitwu01', 'Nitzu01', 'Nupca01', 'Nupde01', 'Nupel01', 'Nupex01', 'Nupfe01', 'Nupim01', 'Nupim02', 'Nupma01', 'Nupne01', 'Nuppa01', 'Nuppa02', 'Nuppr01', 'Nuppr02', 'Nupru01', 'Nupsc01', 'Nupsi01', 'Nupsu01', 'Nuptr01', 'Nupvy01', 'Nupwe01', 'Odoau01', 'Odosp01', 'Opebu01', 'Opema01', 'Opemi01', 'Opepa01', 'Ortro01', 'Panps01', 'Panro01', 'Parde01', 'Parhe01', 'Parmi01', 'Parrh01', 'Parsu01', 'Perfi01', 'Perpe01', 'Pinac01', 'Pinac02', 'Pinac03', 'Pinac04', 'Pinam01', 'Pinan01', 'Pinan02', 'Pinan03', 'Pinap01', 'Pinbi01', 'Pinbr01', 'Pinbr02', 'Pinca01', 'Pincl01', 'Pinde01', 'Pindi01', 'Pindi02', 'Pindo01', 'Pindu01', 'Pinel01', 'Pinel02', 'Pinex01', 'Pinfa01', 'Pinfe01', 'Pinfr01', 'Pinfr02', 'Pingi01', 'Pingl01', 'Pingr01', 'Pingr02', 'Pinin02', 'Pinin03', 'Pinis01', 'Pinkn01', 'Pinkr01', 'Pinkr02', 'Pinku01', 'Pinla02', 'Pinle01', 'Pinlu01', 'Pinma01', 'Pinma02', 'Pinma03', 'Pinma05', 'Pinme01', 'Pinme02', 'Pinmi01', 'Pinmo01', 'Pinmo02', 'Pinmo03', 'Pinmu01', 'Pinna01', 'Pinne01', 'Pinno01', 'Pinno02', 'Pinpa01', 'Pinpa02', 'Pinpe01', 'Pinpe02', 'Pinpe04', 'Pinpe05', 'Pinpl01', 'Pinpo01', 'Pinpo02', 'Pinps01', 'Pinra01', 'Pinre01', 'Pinrh01', 'Pinrh02', 'Pinrh03', 'Pinru01', 'Pinru02', 'Pinsa01', 'Pinsa02', 'Pinsa03', 'Pinsc01', 'Pinsc02', 'Pinsc03', 'Pinsc04', 'Pinsi01', 'Pinsi02', 'Pinsi03', 'Pinsi04', 'Pinst01', 'Pinst02', 'Pinsu01', 'Pinsu02', 'Pinsu03', 'Pinsu04', 'Pinsu05', 'Pinsu06', 'Pinsu07', 'Pinsu08', 'Pinsu09', 'Pinsu10', 'Pinsu11', 'Pinte01', 'Pinth01', 'Pintr01', 'Pinvi01', 'Pinvi02', 'Plaab01', 'Plaam01', 'Plaat01', 'Plaau01', 'Plaba02', 'Plabi01', 'Plabr01', 'Placa01', 'Placl01', 'Placl02', 'Pladi01', 'Plaga01', 'Plaga02', 'Plaga03', 'Plaha01', 'Plaha02', 'Plahi01', 'Plain01', 'Plaki01', 'Plala01', 'Plalu01', 'Plama01', 'Plame01', 'Plami01', 'Plana01', 'Plaob01', 'Plapa02', 'Plape01', 'Plape02', 'Plapo01', 'Plaps01', 'Plapu01', 'Plaro01', 'Plaro02', 'Plaro05', 'Plasi01', 'Plast01', 'Plata01', 'Plats01', 'Plava01', 'Plava02', 'Plavi01', 'Plean01', 'Plebr01', 'Plede01', 'Pleku01', 'Plela01', 'Pleob01', 'Plepr01', 'Plesa01', 'Plesp01', 'Plewo01', 'Pretu01', 'Prohu01', 'Psaab01', 'Psaal01', 'Psabr01', 'Psabu01', 'Psaco01', 'Psafr01', 'Psapu01', 'Psasa01', 'Pse(a01', 'Psebi01', 'Psebo01', 'Pseca01', 'Pseco01', 'Psege01', 'Pseoc01', 'Pseop01', 'Psepa02', 'Psepo01', 'Psero01', 'Psesm01', 'Psevu01', 'Punbo01', 'Pungl01', 'Pyxco01', 'Rhaam01', 'Rhami01', 'Rhasu01', 'Rhipr01', 'Rhobr01', 'Rhogi01', 'Rhogi02', 'Rhote01', 'Rhova01', 'Scema01', 'Scemu01', 'Schbr01', 'Schcr01', 'Schex01', 'Schla01', 'Selab01', 'Selar01', 'Selar02', 'Selau01', 'Selba01', 'Selbl01', 'Selbo01', 'Selca01', 'Selch01', 'Selco01', 'Selda01', 'Seldi01', 'Selel01', 'Sella01', 'Sella02', 'Selpa01', 'Selps01', 'Selps02', 'Selps03', 'Selra01', 'Selre01', 'Selrh02', 'Selro01', 'Selru01', 'Selsc01', 'Selsu01', 'Selsu02', 'Selut01', 'Selve01', 'Semin01', 'Semro01', 'Skaoe01', 'Skape01', 'Skepe01', 'Skesu01', 'Spisp01', 'Staac01', 'Staac02', 'Staac03', 'Staac04', 'Staag01', 'Staal01', 'Staam01', 'Staam02', 'Staam03', 'Stabo01', 'Stabo02', 'Stabo03', 'Stabr01', 'Stach01', 'Staco01', 'Stacr01', 'Stadi01', 'Stadu01', 'Stadu02', 'Staex01', 'Stagr01', 'Stagr02', 'Stahe01', 'Stain01', 'Stain02', 'Stain03', 'Stakr02', 'Stala01', 'Stala02', 'Stala03', 'Stale01', 'Stale04', 'Stalo01', 'Stama01', 'Stami01', 'Stamu01', 'Stana01', 'Stane01', 'Staob01', 'Staol01', 'Staol02', 'Staph01', 'Stapl01', 'Stapo01', 'Stapr01', 'Stapu01', 'Stare01', 'Stare02', 'Staro01', 'Stasa01', 'Stase01', 'Stasi01', 'Stasm01', 'Stasp01', 'Stast01', 'Stasu01', 'Stasv01', 'State01', 'Staun01', 'Stave01', 'Stawi01', 'Steal01', 'Stebr01', 'Steco01', 'Stede01', 'Stedu01', 'Steme01', 'Stemi01', 'Stena01', 'Stene01', 'Stero01', 'Steve01', 'Surac01', 'Sural01', 'Suram01', 'Surbi01', 'Surbi02', 'Surbi03', 'Surbo01', 'Surbr02', 'Surca01', 'Surch01', 'Surcr01', 'Surde01', 'Surel01', 'Surhe01', 'Surhi01', 'Surli01', 'Surma01', 'Surna01', 'Surol01', 'Surov01', 'Surpa01', 'Surre01', 'Surro02', 'Surst01', 'Surst02', 'Sursu01', 'Sursu02', 'Surte01', 'Surun01', 'Surve01', 'Survi01', 'Synac01', 'Synaf01', 'Synam01', 'Synam02', 'Synba01', 'Synbe01', 'Synca01', 'Syncr01', 'Synda01', 'Synde02', 'Synfa01', 'Synfa02', 'Synfl01', 'Synla01', 'Synma01', 'Synmo01', 'Synmo02', 'Synna01', 'Synpa01', 'Synpl01', 'Synva01', 'Tabfe01', 'Tabin01', 'Tabta01', 'Tetgl01', 'Tetla01', 'Thaba01', 'Thabr01', 'Thadu01', 'Thage01', 'Thani01', 'Thaps01', 'Thavi01', 'Traac01', 'Traas01', 'Traau01', 'Trire01', 'Trybr01', 'Tryca01', 'Tryco01', 'Tryde01', 'Trygr01', 'Tryku01', 'Tryle01', 'Trysu01', 'Tryvi01', 'Tscmi01', 'Ulngr01', 'Witan01', 'Withu01', 'Witps01', 'Witsu01', 'Witsy01', 'Zygsu01', 'Mean180Days_1166', 'Mean180Days_1592', 'Mean180Days_1593', 'Mean180Days_1644', 'Mean180Days_1647', 'Mean180Days_1648', 'Mean180Days_1770', 'Mean180Days_2923', 'Mean180Days_6249', 'Mean180Days_6600', 'Mean1Y_1166', 'Mean1Y_1644', 'Mean1Y_1647', 'Mean1Y_1648', 'Mean1Y_1770', 'Mean1Y_2923', 'Mean1Y_6249', 'Mean1Y_6600', 'Mean90Days_1166', 'Mean90Days_1173', 'Mean90Days_1207', 'Mean90Days_1592', 'Mean90Days_1593', 'Mean90Days_1644', 'Mean90Days_1647', 'Mean90Days_1648', 'Mean90Days_1723', 'Mean90Days_1770', 'Mean90Days_1777', 'Mean90Days_1811', 'Mean90Days_2539', 'Mean90Days_2923', 'Mean90Days_3336', 'Mean90Days_5275', 'Mean90Days_5986', 'Mean90Days_6249', 'Mean90Days_6598', 'Mean90Days_6600']

In [26]:
manifest = auto.save_all(outdir="models", compress=3, make_figs=True)
manifest

,region,best_name,calibrated_path,encoder_path,meta_path,viz_dir,oof_acc,oof_f1_macro
0,1,XGBoost,models\best_xgboost_1.joblib,models\best_xgboost_1_label_encoder.joblib,models\best_xgboost_1_meta.json,models\best_xgboost_1_viz,0.99543,0.729089
1,2,XGBoost,models\best_xgboost_2.joblib,models\best_xgboost_2_label_encoder.joblib,models\best_xgboost_2_meta.json,models\best_xgboost_2_viz,1.00000,1.000000

In [27]:
# all regions
reports = auto.save_all_reports(outdir="models")
reports

   region best_name                 report_dir  oof_acc  oof_f1_macro
0       1   XGBoost  models\best_xgboost_1_viz  0.99543      0.729089
1       2   XGBoost  models\best_xgboost_2_viz  1.00000      1.000000

In [28]:
all_preds = auto.all_inferred()
all_preds.to_csv("all_regions_inferred.csv", index=False)

In [29]:
all_cls = all_preds.set_index('SamplingOperations_code')
yhat_te = all_cls['yhat_te'][all_cls['yhat_te'].notna()]
yhat_te = yhat_te.to_frame()
yhat_te.to_csv('Status_catboost.csv')
yhat_te

                          yhat_te
SamplingOperations_code
S05169000_20130911           High
S05169000_20200819           High
S05172000_20210813           Good
S05172050_20210824           Good
S05172350_20120827           High
...                           ...
S06700075_20120611           High
S06700094_20210830           High
S06700590_20210830       Moderate
S06710014_20210823           High
S06820089_20120217           High

[216 rows x 1 columns]